### ISSUE TITLE
Invalid queue ownership image barrier validation errors

### ISSUE THREAD

**Issue by danginsburg** [KhronosGroup/Vulkan-ValidationLayers#307] opened 2018-09-04 12:49 UTC
In working on SteamVR I'm seeing the following validation error in command buffers that both acquire and release an image from an external queue:

```
VK ERROR Validation 0:-1: [ UNASSIGNED-VkImageMemoryBarrier-image-00004 ] Object: 0x1d975d0 (Type = 6) | vkQueueSubmit(): in submitted command buffer VkImageMemoryBarrier aquiring ownership of VkImage (0x7fe1ac0054e0), from srcQueueFamilyIndex 4294967294 to dstQueueFamilyIndex 0 has no matching release barrier queued for execution.
```

I ended up debugging this in validation because I wanted to be sure we were doing the right thing.  Here is what I think is happening.  In this code here it is using the QFOTransferBarrierBase::base_hash_combiner() and operator== to compare the acquire/release barriers:

https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/layers/buffer_validation.cpp#L767

The problem is that these functions both include the srcQueueFamilyIndex and dstQueueFamilyIndex:
```
QFOTransferBarrierBase() = default;
    QFOTransferBarrierBase(const BarrierType &barrier, const HandleType &resource_handle)
        : handle(resource_handle),
          srcQueueFamilyIndex(barrier.srcQueueFamilyIndex),
          dstQueueFamilyIndex(barrier.dstQueueFamilyIndex) {}

    hash_util::HashCombiner base_hash_combiner() const {
        hash_util::HashCombiner hc;
        hc << srcQueueFamilyIndex << dstQueueFamilyIndex << handle;
        return hc;
    }
```
What happens is that the acquire barrier will have srcQueueFamilyIndex = EXTERNAL and the release barrier will have dstQueueFamilyIndex = EXTERNAL, causing them to mismatch during the set_for_handle.find().  I worked around it locally by changing the loop to the following:

```
for (const auto &acquire : cb_barriers.acquire) {
        const auto set_it = global_release_barriers.find(acquire.handle);
        bool matching_release_found = false;
        if (set_it != global_release_barriers.cend()) {
            const QFOTransferBarrierSet<Barrier> &set_for_handle = set_it->second;
            for (const auto &release : set_for_handle) {
                if (release.handle == acquire.handle) {
                    matching_release_found = true;
                    break;
                }
            }
```

I'm not sure if this fix is sufficient, it depends if it needs to be checking things like the subresourceRange and offset/size of the imagememory and buffer barriers or if that's checked elsewhere.  

This is possibly also related to #290.

**Comment by danginsburg** [comment] 2018-09-04 13:36
Another problem I'm seeing is the following: on the first time we do a vkQueueSubmit with an acquire/release barrier, the global_release_barriers is empty causing the same validation error above even with my fix.

It seems that the validation above happens in PreCallRecordQueueSubmit but the global_release_barriers does not get updated untip PostCallRecordQueueSubmit when it calls RecordQueuedQFOTransferBarriers.

Maybe the above check needs to also look in cb_barriers.release instead of only looking in global_release_barriers?

**Comment by jzulauf-lunarg** [comment] 2018-09-04 15:19
Looks like a duplicate of #290 . QFO transfers to and from external can't really be tracked and matched generally AFAICT -- for example when external is in a completely different API that isn't intercepted by the layers.

**Comment by jzulauf-lunarg** [comment] 2018-09-04 16:10
For external, yes.  The layers don't currently communicate across/among Vulkan instances**, and there's no way to match release and acquire operation across API's.

** If this is important to change, it's doable.

**Comment by danginsburg** [comment] 2018-09-04 16:43
> ** If this is important to change, it's doable.

No, I agree it should not report false errors.  However, I'm not convinced that just removing the external barrier checks fixes the issue.It would be helpful to me if you outlined what changes you think are necessary for validation.  

Reviewing the changes in the spec in v1.1.82 I don't think the check mentioned above is even correct at all.  It shouldn't be checking that there is a matching release operation after an acquire, but rather that there was a release before an acquire.

**Comment by jzulauf-lunarg** [comment] 2018-09-04 23:36
Simply neither recording nor validating QFO transfers involving external queues at barrier record time should silence the false positives.  At queue submit time the QFO transfer barrier information recorded for each command buffer is validated against the device-wide record of previous QFO transfer barriers.  If they aren't recorded, they won't be validated, and thus can't create false positives of the type you describe. 

Sharing external QFO transfer information between instances would allow eliminating false *negatives* for purely inter-Vulkan transfers -- but I'm not aware of any inter-instance shared data at this point.

Beyond the external issue,  the release-acquire logic is naive in a couple of ways, that seem to me to be corner cases. One example reflects that it is possible to change ownership without a release-acquire pair, as long as one does not care about preserving the content of a resource.  What isn't clear is what the semantics and validity of mixing the non-preserving ownership change with a preserving one.  Imagine that queue A in queue family x releases a resource R, then queue B in queue family y (with a proper semaphore) simply starts using R as a write target.  Thing that aren't clear are what is the image layout if the release operation specified a transition.  The spec is silent about when the transition is done.  Would it be necessary and/or sufficient for B to do an image layout transition from UNDEFINED? 
After B accesses R what happens if C to performs an acquire operation on R, this is probably invalid.  We don't track that, and if queue A were to do some non-preserving ownership acquisition, any subsequent release would look like a duplicate (to the current bookkeeping).

In the online threads discussing release-acquire the consensus reflects a view that they really need to be in matched pairs for any hope of reasonable behavior, semantics, or implementation -- so the examples above should likely (eventually) be within the scope of synchronization validation to detect the mixed mode resource ownership transfers, and report them.

**Comment by jzulauf-lunarg** [comment] 2018-12-21 20:52
@danginsburg -- you had some concerns about the correctness of the fix.  

1) Has the issues of the false positives been resolved to your satisfaction?
2) Should we open an issue to track external QFO transfers between instances/devices as an incomplete?

**Comment by danginsburg** [comment] 2018-12-21 21:31
> Has the issues of the false positives been resolved to your satisfaction?

I think so, but honestly I haven't looked in this in several months and am not in a position to retest at the moment.

> Should we open an issue to track external QFO transfers between instances/devices as an incomplete?

Well, it is indeed an issue so it seems reasonable to open one.  Whether you should prioritize addressing it is I guess another question.

**Closed** 2019-06-04 22:13 UTC
Labels: duplicate, question
