### ISSUE TITLE
Getting read after write hazard sync errors when framebuffer textures are stored in a bindless descriptor and accessed from a shader that within the same render pass

### ISSUE THREAD

**Issue by GasimGasimzada** [KhronosGroup/Vulkan-ValidationLayers#5198] opened 2023-01-31 21:04 UTC
**Environment**

 - OS: Windows 11
 - GPU: NVIDIA RTX 3070Ti
 - VulkanSDK: 1.3.224
 - Options enabled: Synchronization (via Vulkan Configurator)

**Describe the Issue**

I have a descriptor set that is created with `VK_DESCRIPTOR_BINDING_PARTIALLY_BOUND_BIT` and `VK_DESCRIPTOR_BINDING_UPDATE_AFTER_BIND_BIT_EXT`. In this descriptor, I am storing **every single texture** that I have in my application, including all the textures that are used as framebuffer attachments.  Let's call this "global textures descriptor".

Generally, most of my render passes have a pipeline where the shaders need to access the textures; so, the shaders access these textures from the global textures descriptor by accessing them via indices that are passed using push constants.

Because the framebuffer attachment texture of render pass is also in the global textures descriptor that the shader within the render pass accesses, I get lots of read after write hazards about the texture access **even though I am not accessing this particular texture** from the global textures descriptor. I get this error because the texture is in the global textures descriptor and I am accessing this descriptor set but not because I am accessing the particular texture.

**Expected behavior**

There should be no validation errors if I am not accessing a resource from a descriptor set with partially bound and update after bind flags.

**Additional context**

```
vkCmdDrawIndexed: Hazard READ_AFTER_WRITE for VkImageView 0xA[], in VkCommandBuffer 0xB[], and VkPipeline 0xC[], VkDescriptorSet 0xD[], type: VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, imageLayout: VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL, binding #0, index 5. Access info (usage: SYNC_FRAGMENT_SHADER_SHADER_STORAGE_READ, prior_usage: SYNC_COLOR_ATTACHMENT_OUTPUT_COLOR_ATTACHMENT_WRITE, write_barriers: 0, command: vkCmdDrawIndexed, seq_no: 3, reset_no: 3). (SYNC-HAZARD-READ_AFTER_WRITE; 0xE)
```

**Comment by spencer-lunarg** [comment] 2023-02-01 05:18
@GasimGasimzada it is hard to fix these Synchronization validations without a way to try and reproduce it (or start to examine it more)

if possible could you give something like an [api dump](https://vulkan.lunarg.com/doc/view/latest/windows/api_dump_layer.html) of the area this happens as it will allow us to look into this faster

**Comment by GasimGasimzada** [comment] 2023-02-01 11:21
Here is an [api_dump.log](https://github.com/KhronosGroup/Vulkan-ValidationLayers/files/10556378/api_dump.log) from a single frame where hazard still happens.

**Comment by jeremyg-lunarg** [comment] 2023-02-01 14:59
>  I get lots of read after write hazards about the texture access even though I am not accessing this particular texture from the global textures descriptor

This is a duplicate of https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/3450 . Determining which descriptor indices are actually used in a shader requires instrumenting the SPIR-V code to report which indices are used and then feeding that information back into sync validation (core validation too). I'm working on this, but it is a fairly long term project.

**Closed by jeremyg-lunarg** 2023-02-01 14:59 UTC
Labels: Synchronization, DescriptorIndexing
