### ISSUE TITLE
Extension Error when it run under preload vulkan fucntions

### ISSUE THREAD

**Issue by oninach** [KhronosGroup/Vulkan-ValidationLayers#879] opened 2019-04-23 18:51 UTC
when preload some wrapper function it returns :
```
Program received signal SIGSEGV, Segmentation fault.
terminator_GetPhysicalDeviceSurfaceSupportKHR (physicalDevice=0xb90500, queueFamilyIndex=0, surface=0x0, pSupported=0x7ffff7fc483c)
at /usr/src/debug/Vulkan-LoaderAndValidationLayers-sdk-1.1.73.0/loader/wsi.c:234
234 if (NULL != icd_surface->real_icd_surfaces && (VkSurfaceKHR)NULL != icd_surface->real_icd_surfaces[phys_dev_term->icd_index]) {
```
It seems that KHR extensions are not enabled !

**Comment by jzulauf-lunarg** [comment] 2019-04-24 14:31
@lenny-lunarg -- are you able to understand what the issue is describing?

@oninach -- does this occur in the latest SDK?

**Comment by oninach** [comment] 2019-04-25 09:32
@jzulauf-lunarg -- SDK version 1.1.101.0

**Comment by jzulauf-lunarg** [comment] 2019-04-25 13:28
@oninach  -- Brevity is good.  But the information is a bit terse, here and above.  

1) are you confirming that the same issue exists in 1.1.101? (The error message you originally posted is from SDK 1.1.73.0)

2) When you say "when preload some wrapper function" what are the specific steps you are taking to reproduce this error?

**Comment by oninach** [comment] 2019-04-28 16:59
Yes the version of Vulkan that I use is 1.1.101.
I created a "wrapper functions" and I use $ LD_PRELOAD in Linux.
I notice that this happen for KHR functions.
I hope that it's clear :)

**Comment by jzulauf-lunarg** [comment] 2019-04-29 13:28
@lenny-lunarg @MarkY-LunarG @jeremy-lunarg -- given that the loader is a *loader* -- can one validly use LD_PRELOAD,  Are then operations during .so loading that are required to make entrypoints valid?

1) if preload is valid so, on what entrypoints and 
2) is this something we should label in large friendly letters as being unsupported, list the limitations of the support?

**Comment by oninach** [comment] 2019-05-03 12:20
The sdk 1.1.73.0 refers to DebugInfo : Vulkan-LoaderAndValidationLayers-sdk-1.1.73.0 but I am using right now the last Version of Vulkan : 1.1.106.0

**Comment by lenny-lunarg** [comment] 2019-05-03 16:18
What's going on with your debug info? Are you using debug info from the 1.1.73 loader with the 1.1.101 loader? If so, that's not particularly useful. You really need the debug info and source code to match the loader you're running.

As far as what's going on, what are you doing with the Vulkan calls? The loader uses the gcc constructor attribute to initialize some data. It is conceivable that this isn't being run if you're trying to use the loader before you enter your `main()` function, but I really don't know from the info you provided.

So my questions are these: What Vulkan APIs are you calling and when are you calling them? Before `main()` or during it? And what Vulkan call is this crashing in? The debug info suggests it's in `vkGetPhysicalDeviceSurfaceSupportKHR()`, but I'm not confident that's correct. A stack trace would probably be a good idea. Are any Vulkan calls working or is the first call you make crashing? Did instance initialization work?

**Comment by oninach** [comment] 2019-05-04 10:07
Well, when I run my application under GDB, I get suggestion to install vulkan debuginfo `

> "Missing separate debuginfos, use: debuginfo-install vulkan-1.1.73.0-1.el7.x86_64"

`
However my Vulkan version is 1.1.106.0 .So I guess I have two chooses either to download the vulkan version 1.1.73 or to match the loader but I don't have any idea how to do that.

I try to record the vulkan calls so that I can replay them after.

I have created a shared object library that I pre-load when running the application ( I guess it's before main but I am not sure).
I noticed that Vulkan calls like VkCreateInstance, VkCreateSurface... work properly but when I call vulkan calls that are in the KHR extension It crashes in the first one 
(vkGetPhysicalDeviceSurfaceSupportKHR).And I get 

```
Program received signal SIGSEGV, Segmentation fault.
terminator_GetPhysicalDeviceSurfaceSupportKHR (physicalDevice=0xb90500, queueFamilyIndex=0, surface=0x0, pSupported=0x7ffff7fc483c)
at /usr/src/debug/Vulkan-LoaderAndValidationLayers-sdk-1.1.73.0/loader/wsi.c:234
234 if (NULL != icd_surface->real_icd_surfaces && (VkSurfaceKHR)NULL != icd_surface->real_icd_surfaces[phys_dev_term->icd_index]) {

```
I see in the **wsi.c** file at the part where it crashes that it verify if KHR extension are enabled or not.
The comment in the file _"   // First, check to ensure the appropriate extension was enabled: "_

I enabled the extension when I want to create the instance :

	```
reateInfo.enabledExtensionCount = glfwExtensionCount;
        createInfo.ppEnabledExtensionNames = glfwExtensions;

```
 So do I have to enable KHR extensions in the layer that I try to add ?

Note that when I run my application normally it works.But under pre-load function it crashes.

**Comment by lenny-lunarg** [comment] 2019-05-06 17:11
> So do I have to enable KHR extensions in the layer that I try to add ?

Yes, you definitely need to enable any extension that you use. This is true for all extensions, no matter if they're KHR or not. If you're using extensions in your layer that the application doesn't enable, then your layer will need to create a `VkInstanceCreateInfo` that includes those extensions before it calls down the call chain.

That is the obvious thing that needs to be fixed, but I have some general comments on a couple other points you raised:

> Note that when I run my application normally it works.But under pre-load function it crashes.

I can't explain why it works some of the time, but I would expect a crash if you're not enabling the extensions you use. Your crash seems to be happening when the loader tries to convert the application `VkSurfaceKHR` handle to a driver `VkSurfaceKHR` handle. This usually indicates that the handle you passed in invalid. But if your surface creation function is returning success, I don't know why that would happen.

> However my Vulkan version is 1.1.106.0.

I don't know what that means. There really isn't one overall version of Vulkan that's installed on your system. There's an instance version, which is really the loader version, but each GPU can report its own version. Those versions are determined by the driver. And if you're reporting the version number given at the top of the `vulkaninfo` output, only the major and minor versions are the loader versions. The patch number is really the `vulkaninfo` version. Running `vulkaninfo` on my Windows machine, for example, I see:

```
==========
VULKANINFO
==========

Vulkan Instance Version: 1.1.106
```
at the top, but when I look further down I see:
```
==================================
GPU0
VkPhysicalDeviceProperties:
===========================
        apiVersion     = 0x401054  (1.1.84)
        driverVersion  = 1746157568 (0x68144000)
        vendorID       = 0x10de
        deviceID       = 0x139b
        deviceType     = DISCRETE_GPU
        deviceName     = GeForce GTX 960M
```
and
```
==================================
GPU1
VkPhysicalDeviceProperties:
===========================
        apiVersion     = 0x400042  (1.0.66)
        driverVersion  = 65538 (0x10002)
        vendorID       = 0x8086
        deviceID       = 0x191b
        deviceType     = INTEGRATED_GPU
        deviceName     = Intel(R) HD Graphics 530
```

This reflects the fact that there's no single version that I'm running. What's really relevant here is the loader version that you're using. My guess is you're using a 1.1.73 loader, but the only way you're going to know for sure is to check wherever you got your loader (either an SDK or system packages).

**Comment by mark-lunarg** [comment] 2019-06-04 21:45
@oninach, is your issue now resolved?

**Comment by mark-lunarg** [comment] 2019-08-07 21:36
@oninach, we will close this issue for now.  If it turns out the problem persists for you, please reopen this issue or create a new one -- thanks.

**Closed by mark-lunarg** 2019-08-07 21:36 UTC
Labels: question
