### ISSUE TITLE
DebugUtils not working on Android w/ VK_LAYER_KHRONOS_validation

### ISSUE THREAD

**Issue by tobine** [KhronosGroup/Vulkan-ValidationLayers#1336] opened 2019-10-21 23:03 UTC
After a number of roadblocks we finally updated ANGLE to use the VK_LAYER_KHRONOS_validation unified layer. However, on Android I'm seeing a crash when attempting to use the layer along with the VK_EXT_debug_utils extension.

I've added a [workaround](https://cs.chromium.org/chromium/src/third_party/angle/src/libANGLE/renderer/vulkan/RendererVk.cpp?l=698) for Android on ANGLE where we fall-back to the older DebugReport extension.
Can someone at LunarG take a look at this to see why the validation layers aren't working on Android with DebugUtils extension?

Here's the high-level repro instructions, let me know if you need further info:
1. Build ANGLE for Android as described in the DevSetup doc [here](https://chromium.googlesource.com/angle/angle/+/master/doc/DevSetup.md#building-angle-for-android). Build the `angle_deqp_gles3_tests` target to run the test referenced below.
2. Run a test and verify that it passes. Here's a command line that should work from your chromium/src dir: `out/ANGLEDebug/bin/run_angle_deqp_gles3_tests --use-angle=vulkan --gtest_filter=dEQP.GLES3/functional_fbo_completeness_renderable_texture_stencil_depth_stencil_unsigned_int_24_8` (NOTE: If you see weird adb script errors, run `which adb` and add the additional command line option `--adb-path=<adb_path>` where <adb_path> was the output from `which` cmd)
3. When you pull the source, remove the [workaround](https://cs.chromium.org/chromium/src/third_party/angle/src/libANGLE/renderer/vulkan/RendererVk.cpp?l=698) referenced above by changing the line of code to read `bool enableDebugUtils = false;`
4. Re-run the test from line #2 above and verify that it now fails.

That's it
I've also attached the logcat output the includes the stacktrace for the crash.
[logcat_dbgutils_crash.txt](https://github.com/KhronosGroup/Vulkan-ValidationLayers/files/3753266/logcat_dbgutils_crash.txt)

**Comment by locke-lunarg** [comment] 2019-10-25 19:09
The program crashes in https://cs.chromium.org/chromium/src/third_party/angle/src/libANGLE/renderer/vulkan/RendererVk.cpp?l=788 -> https://cs.chromium.org/chromium/src/third_party/angle/src/libANGLE/renderer/vulkan/vk_utils.h?g=0&l=706.

It crashes when it runs `vkCreateDebugUtilsMessengerEXT`. I think the reason is the driver doesn't really support `VK_EXT_DEBUG_UTILS_EXTENSION_NAME`, although the extension exist in `VK_LAYER_KHRONOS_validation`.

The problem also happens in `VkLayerTest.DebugUtilsNameTest`. Most Android devices skip this test. In `VkLayerTest.DebugUtilsNameTest`, it only checks `VK_EXT_DEBUG_UTILS_EXTENSION_NAME` in default layer( pLayerName = NULL ), not `VK_LAYER_KHRONOS_validation`. But the extension really exists in `VK_LAYER_KHRONOS_validation`. If I add the extension and run `vkCreateDebugUtilsMessengerEXT`, it crashes in `layer_data->instance_dispatch_table.CreateDebugUtilsMessengerEXT` of `DispatchCreateDebugUtilsMessengerEXT`.

So, I think the problem is why `VK_LAYER_KHRONOS_validation` has those extensions that the driver doesn't support.

**Comment by mark-lunarg** [comment] 2019-10-25 19:23
@tobine, we think this is probably an issue with the Android loader.  The desktop loader needed special plumbing to handle extensions implemented by a layer but not by the display driver.

**Comment by tobine** [comment] 2019-11-01 16:00
I'll investigate this a bit more. Note that we were able to use DebugUtils extension without issue previously on Android. It was only when I switched from the individual layer stack to the unified layer that DebugUtils was causing crashes.

**Comment by mark-lunarg** [comment] 2019-11-01 18:40
@tobine, `EnumerateInstanceExtensionProperties `was modified to correctly report the `DebugUtils `extension in mid-April.  @locke-lunarg modifed the Khronos layer to NOT report this extension, and the test cases in question pass, outputting "Extension not supported: VK_EXT_debug_utils", and we verified that our Android device does not support this extension.  This points directly to an issue with the Android Loader.

**Comment by mark-lunarg** [comment] 2019-11-12 17:42
@tobine, I am closing this as we're pretty sure there's nothing actionable here -- if this turns out to be incorrect, please reopen the issue.  Thanks!

**Comment by critsec** [comment] 2019-12-19 18:28
(I'd reopen if I could.)

What I'm seeing right now is that `VK_EXT_debug_utils` is advertised by the `VK_LAYER_khronos_validation` layer. Can you point me to the change that disabled advertising it when lower layers don't? I haven't been able to find that.

I'm not sure I understand why the loader needs to change or why this can only work when the loader/drivers also support it. Layers are supposed to be able to support extensions that the underlying loader/layers don't in most cases, and I'm not sure why this one would be an extension. When adding an extension, it should just not call into the next layer if that layer doesn't support it. In this case, `VK_EXT_debug_utils` is an essential part of validation, and developers should be able to use it on devices that don't have the latest drivers or loader.

**Comment by mark-lunarg** [comment] 2019-12-19 18:44
@critsec,the change to disable advertising the extension was done solely for testing purposes.  I'll ask @lenny-lunarg to address the rest.

**Comment by lenny-lunarg** [comment] 2019-12-19 21:25
> I'm not sure I understand why the loader needs to change or why this can only work when the loader/drivers also support it.

The desktop loader needed special support for debug utils, but that support centered on getting loader messages reported through the extension. I don't think there should be anything preventing layers from implementing debug utils even without loader support, but I don't know if we've ever tested that use case. I do agree that a loader change shouldn't be required for a layer-only implementation.

As far as a lack of support from the Android loader is concerned, I really don't know how the Android loader gets extensions. Does it use `vkEnumerateInstanceExtensionProperties`? The desktop loader uses the json manifest file, but I believe those aren't used by Android. It may be that it not working on Android isn't about a lack of support for the extension, but is instead about checking for extensions in different ways.

**Comment by mark-lunarg** [comment] 2019-12-19 21:40
Seems like the Android Loader should be calling `Enumerate[Instance|Device]ExtensionProperties()` for each layer, and setting up their dispatch tables/terminators accordingly.  I *believe* we are correctly returning the following data for the Khronos validation layer:

```
static const VkExtensionProperties instance_extensions[] = {{VK_EXT_DEBUG_REPORT_EXTENSION_NAME, VK_EXT_DEBUG_REPORT_SPEC_VERSION},
                                                            {VK_EXT_DEBUG_UTILS_EXTENSION_NAME, VK_EXT_DEBUG_UTILS_SPEC_VERSION}};
static const VkExtensionProperties device_extensions[] = {
    {VK_EXT_VALIDATION_CACHE_EXTENSION_NAME, VK_EXT_VALIDATION_CACHE_SPEC_VERSION},
    {VK_EXT_DEBUG_MARKER_EXTENSION_NAME, VK_EXT_DEBUG_MARKER_SPEC_VERSION},
    {VK_EXT_TOOLING_INFO_EXTENSION_NAME, VK_EXT_TOOLING_INFO_SPEC_VERSION}
};
```

**Comment by mark-lunarg** [comment] 2019-12-19 21:46
@Tobine, can you confirm that the loader in question is calling these APIs with the new `VK_KHRONOS_validation` layer name?

**Comment by critsec** [comment] 2019-12-19 22:23
Yes, the Android loader calls `vkEnumerateInstanceExtensionProperties` for each layer. I don't think there's a problem there -- it's being reported to the app correctly when `pLayerName` is `VK_LAYER_khronos_validation`.

**Comment by mark-lunarg** [comment] 2019-12-19 22:36
OK, I'll try to do some further digging tomorrow.

**Comment by lenny-lunarg** [comment] 2019-12-20 21:40
So I talked to @mark-lunarg a little more today and I would like to correct what I said above. He was right that for desktop systems, loader support is required for the extension to work at all. The reason for this is that debug utils is an instance extension. While the loader can support unrecognized device extensions, the same is not true of instance extensions. This is because the loader has no idea how to handle this on multiple drivers which may or may not support the extension in question. If the loader recognizes the extension, then it can figure out what to do.

I'll also add that this is a particularly odd extension because it's an instance extension that also contains device functionality. The desktop loader wasn't originally designed to support extensions like that, so we had to make some changes for debug utils. It seems likely to me that the Android loader would be similar to the desktop loader in that it may need to know about instance extensions and it may not like mixing instance and device functionality in the same extension.

**Comment by mark-lunarg** [comment] 2019-12-20 22:30
@critsec, @tobine -- Did some android testing today and confirmed that the layers are receiving and properly responding to `vkEnumerateInstanceExtensionProperties`.  The KHRONOS layer returns two extensions, `DebugUtils `and `DebugReport`.  Following this up with a call to `EnumerateInstanceExtensionProperties `with pLayerName set to NULL returns a list of extensions that does **NOT** contain DebugUtils -- in the layer validation tests, we skip those tests on android.  

Interestingly, calling `GetInstanceProcAddress `on that function seems to return a non-null pointer, though the layers won't be happy as its extension is not enabled.  If the Android loader is doing anything special with DebugReport, it may need to do the same thing with DebugUtils

**Comment by critsec** [comment] 2019-12-21 00:05
I'm not aware of anything the Android loader would need to do to handle this. We only support one ICD, and having a 1:1 relationship between API instance and ICD instance simplifies things.

Mark, I'm confused about your last paragraph. On Android, enabling the layer and extension and calling `vkGetInstanceProcAddress` does return a non-NULL pointer, as it should because the extension is enabled from the app's point of view. Calling that function enters the layer code, but that ends up calling a NULL function pointer because the next layer down (the driver, in my case) *doesn't* support the extension and doesn't have it enabled.

In general, any layer whether device or instance, needs to either:

1. Not advertise an extension if it requires the layers beneath it to support the extension, but they don't, or

2. Gracefully handle the case where the layers below it don't support the extension, by stripping it out of the list of extensions to enable on the way down, and not querying or calling the extension's functions from that layer.

Right now, the layer's implementation of this extension is not doing either of those, so the extension looks like it is available to use, but crashes when it is used. That's going to be a real problem in the Android ecosystem as more developer materials recommend using this extension. Again, AFAIK the Android loader doesn't have to change to support this -- which is good because the loader is not updatable without a full-system OTA from the device OEM.

The difference with debug report is that the Android loader does implement it since in a few cases it reports its own messages -- so the extension is usable even without any validation layers. That makes the passthrough from the validation layer happen to work. But the validation layer ought to be able to expose the extension even if the loader doesn't also expose it.

**Comment by mark-lunarg** [comment] 2019-12-21 04:27
Yeah, I'll get back with Locke and we'll see if we can debug further using the original setup.  In the Android test harness we have, the DebugUtils extension is never available (EnumerateInstanceExtensionProperties does not return it) even if advertised by the layers, so there's no way to call it.

**Comment by mark-lunarg** [comment] 2019-12-31 22:03
@tobine, @critsec, pushed a branch (`markl-instancestubs`) that should terminate the GPA chain properly in the layers for instance extensions. I'm unable to reproduce the issue on the mobile devices I have, though they do not crash and appear to work normally (as they did before the change).  If you could share the results of that branch and its effect on this issue, that'd help a lot.

On another note, I am unable to get the android loader to return debug_utils as a supported extension on my Pixel 2XL -- though DebugReport shows up fine.  Using it without enabling it seems to work, however.

**Comment by tobine** [comment] 2020-01-03 23:18
@mark-lunarg running ANGLE [CI](https://chromium-review.googlesource.com/c/angle/angle/+/1985175) with your branch and enabling the DebugUtils extension on Android is passing where it was previously crashing.

**Closed** 2020-01-06 22:18 UTC
Labels: bug

**Comment by critsec** [comment] 2020-01-13 21:42
I verified my program can now use the debug utils messenger on Android with that change; I'm getting callbacks successfully when I deliberately violate valid usage. Thanks!

**Comment by TheMostDiligent** [comment] 2022-06-26 22:22
Sorry for replying to this old thread, but we are heaving exactly the same issue with debug utils on Android (#4242): the extension is not reported by `vkEnumerateInstanceExtensionProperties`, yet it can be successfully enabled and seems to work fine.
It looks like @critsec managed to get it working, but I can't understand what needs to be done - simply ignore the fact that it is not listed and use it regardless? What about devices that genuinely do not support it?
