### ISSUE TITLE
vkCreateShaderModule Invalid SPIR-V magic number when using Metal source or Metal bytecode in MoltenVK

### ISSUE THREAD

**Issue by BearishSun** [KhronosGroup/Vulkan-ValidationLayers#931] opened 2019-05-21 08:52 UTC
Hello.

When using MoltenVK, you can provide Metal shader source code or pre-compiled Metal byte code to `vkCreateShaderModule` by setting a magic number. Currently the validation layers report this as "SPIR-V module not valid: Invalid SPIR-V magic number.".

These are the magic numbers:
```
typedef enum {
    kMVKMagicNumberSPIRVCode        = 0x07230203,    /**< SPIR-V stream contains standard SPIR-V code. */
    kMVKMagicNumberMSLSourceCode    = 0x19960412,    /**< SPIR-V stream contains Metal Shading Language source code. */
    kMVKMagicNumberMSLCompiledCode  = 0x19981215,    /**< SPIR-V stream contains Metal Shading Language compiled binary code. */
} MVKMSLMagicNumber;
```

As defined in https://github.com/KhronosGroup/MoltenVK/blob/32e79892f582b0d8dfc876d32c4ccd3dba714622/MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h

I'm seeing this issue using the official  1.1.106 Vulkan SDK for mac OS.

**Comment by KarenGhavam-lunarG** [comment] 2019-05-21 19:14
@billhollings Could you provide your opinion on this. Is there a defect in the validation layers?

**Comment by billhollings** [comment] 2019-05-21 23:58
@KarenGhavam-lunarG 

Yes...MoltenVK supports the two additional magic numbers for direct MSL import. 

BTW...MoltenVK also supports the `VK_NV_glsl_shader` extension, allowing GLSL without a magic number...but that is advertised by MoltenVK in the standard extension lists like any other Vulkan implementation.

**Comment by jeremy-lunarg** [comment] 2019-05-22 18:15
> 
> Yes...MoltenVK supports the two additional magic numbers for direct MSL import.
> 

@billhollings 
It is possible to get those magic numbers upstream'ed into SPIR-V (via core or extension)? We can hack around this issue in validation layers by ignoring those magic numbers during shader validation, but it feels like a backwards way of implementing support for MSL.

**Comment by billhollings** [comment] 2019-05-22 19:06
I guess that could work. But I'm not aware of how to make that happen...and it would likely be a lower priority effort for me...and the SPIRV folks, I'm sure.

But what would we need to do to make that happen?

BTW...in implementing the `VK_NV_glsl_shader` extension...I was really disappointed to see that the Vulkan WG allowed that extension to skip using a magic number altogether...basically commandeering the entire code space that isn't SPIRV. Essentially...if it isn't SPIRV...it must be GLSL source text! 

Pretty short-sighted given the number of shaders that originate, say, in HLSL. They should have assigned a magic number for GLSL.

**Comment by jeremy-lunarg** [comment] 2019-05-22 20:28
> But what would we need to do to make that happen?

On second thought, it'd be strange to add magic numbers to SPIR-V that say "I'm not SPIR-V". I think it makes more sense for this to be implemented as a Vulkan extension rather than a SPIR-V extension. e.g. VK_MSL_shader defines two new symbols (your magic numbers).

> BTW...in implementing the VK_NV_glsl_shader extension...I was really disappointed to see that the Vulkan WG allowed that extension to skip using a magic number altogether...basically commandeering the entire code space that isn't SPIRV. Essentially...if it isn't SPIRV...it must be GLSL source text!

I'm not sure how that'd work; it's just source code. Regardless, I think it can still work with other shading languages. The interaction could be defined at the extension level.

It probably makes sense to bring this up with the working group. Perhaps you can ask via the Khronos Vulkan mailing list.

**Comment by billhollings** [comment] 2019-05-22 21:19
> I'm not sure how that'd work; it's just source code.

The MSL passed above is also source code...but it's prefixed with an `MVKMSLSPIRVHeader`:

    typedef uint32_t MVKMSLSPIRVHeader;

which just provides space for the magic number (in this case `kMVKMagicNumberMSLSourceCode`). For MSL code, it then just skips the header to point to the source code:

	size_t hdrSize = sizeof(MVKMSLSPIRVHeader);
	char* pMSLCode = (char*)(uintptr_t(pCreateInfo->pCode) + hdrSize);
	size_t mslCodeLen = codeSize - hdrSize;

It would have been nice and consistent if the GLSL extension had done something similar.

But as you say...it can be selected by enabling the correct extension at runtime.

**Comment by jeremy-lunarg** [comment] 2019-05-22 22:29
> But as you say...it can be selected by enabling the correct extension at runtime.

Looking at the spec for `VkShaderModuleCreateInfo`, I believe you could support MSL in a way that is similar to GLSL.

> pCode must point to either valid SPIR-V code, formatted and packed as described by the Khronos SPIR-V Specification or valid GLSL code which must be written to the GL_KHR_vulkan_glsl extension specification

> If pCode points to GLSL code, it must be valid GLSL code written to the GL_KHR_vulkan_glsl GLSL extension specification

Someone would need to champion that effort. From a validation layers standpoint, we're reluctant to hack around this since it would violate the spec.

**Comment by billhollings** [comment] 2019-05-23 18:03
> Looking at the spec for `VkShaderModuleCreateInfo`, I believe you could support MSL in a way that is similar to GLSL.
> 
> > pCode must point to either valid SPIR-V code, formatted and packed as described by the Khronos SPIR-V Specification or valid GLSL code which must be written to the GL_KHR_vulkan_glsl extension specification
> 
> > If pCode points to GLSL code, it must be valid GLSL code written to the GL_KHR_vulkan_glsl GLSL extension specification

I wouldn't want to handle MSL the way `VK_NV_glsl_shader` handles GLSL. The problem is that it would force the user to enable only one or the other extension (MSL vs GLSL). Enabling an MSL extension would force the disabling of GLSL, and vice-versa.  

From my perspective, the point of magic numbers is to identify the remaining content on each load. Using magic numbers would allow an app to submit SPIR-V, GLSL, MSL, HLSL,..., on a shader-by-shader basis, without having to choose one or the other for all shaders, by enabling one or other extension at the device level.

**Comment by KarenGhavam-lunarG** [comment] 2019-05-23 20:04
@billhollings Your concerns about the extension VK_NV_glsl_shader are valid and as you are trying to find a Vulkan compliant solution to the original issue, these should be brought to the WG for a solution. Do note that extension has been deprecated and it is GL_KHR_vulkan_glsl  that you should be reviewing as reference point. 

To modify the validation layers to accommodate the MSL shaders would be a violation of the current Vulkan spec and hence why we currently aren't planning to do that solution since we need to keep the validation layers compliant with the Vulkan specification. Fortunately the validation error is not fatal and the application can continue to execute.

**Comment by billhollings** [comment] 2019-05-24 13:51
@KarenGhavam-lunarG 

Thanks for the update.

Good point about the deprecation of `VK_NV_glsl_shader` in Vulkan 1.1. That makes it worse because with Vulkan 1.1 there is no way of turning off the interpretation of GLSL by disabling the extension to allow MSL to be interpreted!

`GL_KHR_vulkan_glsl` is the reference for style of GLSL that can be converted to Vulkan SPIR-V or input to the `VK_NV_glsl_shader` extension (or Vulkan 1.1). I don't think it has anything to say about the loading activities themselves.

**Comment by KarenGhavam-lunarG** [comment] 2019-05-24 15:46
@billhollings Since this issue isn't a defect for the validation layers, we are planning to close it. It probably would be a good idea for you to create a tracking issue in your MoltenVK project for resolving this issue. You can link to this issue for historical context/info.

**Closed** 2019-05-24 15:53 UTC
