### ISSUE TITLE
Failed to track layout transitions of images bound to peer memory in mGPU

### ISSUE THREAD

**Issue by janetliuAMD** [KhronosGroup/Vulkan-ValidationLayers#750] opened 2019-03-01 22:54 UTC
In mGPU environment, if I create a peer image (`peer_image`) that bound to the peer memory of a swapchain image (`swapchain_image`), then the validation layer won't recognize `peer_image`'s layout as transitioned as the result of transitioning `swapchain_image`'s layout, or vice versa.

Here's a simple example:

I have a device group consists of two GPUs (`GPU0` and `GPU1`), and I created `peer_image` with `VK_IMAGE_CREATE_ALIAS_BIT` and whose memory bound to `swapchain_image`'s peer memory through `vkBindImageMemory2KHR` using following settings:

- `VkBindImageMemorySwapchainInfoKHR`: set `imageIndex` as the index of `swapchain_image`.
- `VkBindImageMemoryDeviceGroupInfo`: set `pDeviceIndices = {0, 0}`.

Then on both GPUs ,`peer_image` is bound to the memory instance of `swapchain_image` on `GPU0`.

To transfer data from `GPU1` to `GPU0`'s `swapchain_image` instance, I do the following steps:

1. On `GPU0`, transition `swapchain_image`'s layout to `VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL`.
2. On `GPU1`, copy the data from data source to `peer_image`.

Then since `peer_image` was created with an initial layout of `VK_IMAGE_LAYOUT_UNDEFINED`, validation layer will not recognize its layout as transitioned and generate layout inconsistency error messages like:
> Validation Error was reported: Submitted command buffer expects image 0x44 (subresource: aspectMask 0x1 array layer 0, mip level 0) to be in layout VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL--instead, image 0x44's current layout is VK_IMAGE_LAYOUT_UNDEFINED.

despite that the layout of its underlying memory (memory instance of `swapchain_image` on `GPU0`) has already been transitioned.

I believe the image layout should be associated with its underlying memory, but it seems the validation layer currently only tracks image layout based on individual image objects, not on the underlying memory it binds to.

**Comment by locke-lunarg** [comment] 2019-06-27 15:51
@janetliuAMD Fixed in [PR #1014](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/1014)

**Comment by locke-lunarg** [comment] 2019-07-02 16:55
Sorry, the problem is not really fixed. I'm still working on it.

**Closed** 2019-09-09 22:25 UTC
Labels: bug
