### ISSUE TITLE
Feature to allow use of pre-release extensions

### ISSUE THREAD

**Issue by tobine** [KhronosGroup/Vulkan-ValidationLayers#1820] opened 2020-05-06 15:32 UTC
This is an issue to start a dialogue about potentially adding a more user-friendly way to support developers using validation layers with pre-release extensions.

Currently the unique handles layer will null out the pNext ptr for any extension struct that's not yet defined in the spec. As a workaround the unique handles layer can be disabled with "VK_VALIDATION_FEATURE_DISABLE_UNIQUE_HANDLES_EXT."

This issue is to explore if an alternate feature may be worthwhile that will allow unique handles to remain on, but also allow unknown structures down pNext chain. Perhaps some user-friendly way to notify the validation layers of experimental extensions that are being used so that they won't be null'd out of the pNext chain by unique handles.

Also, note that I have a report that the current behavior for unknown extensions is not consistent. I believe that it should warn for any unknown extension, but a user with two separate unreleased extensions reports:

> it warned correctly for vkCreateSampler for my extension, and nulled out the pointer; however, vkCreateDevice did NOT warn about the provoking vertex extension being unknown, but DID remove it from the pNext pointer.

For any extension not known by the validation I would expect a warning, but the user reports this didn't occur for the provoking vertex extension (which is not yet supported in GitHub layers that were being used.)

**Comment by jzulauf-lunarg** [comment] 2020-05-06 16:29
One thing to note as we approach this.  If we complete "dehandling", essentially store all handle references within the validation layer data by the shared_ptr (or weak_ptr) for the reference, most of the reason for unique handles goes away.  More details and trade-offs are needed to evaluate this approach.

**Comment by mark-lunarg** [comment] 2020-05-06 17:36
@tobine, I confirmed that we do output a _warning_ if an unrecognized extension is encountered at CreateInstance- or CreateDevice-time.  The ability to disable handle wrapping was added as a workaround for this situation, as you mentioned.  Does using validation with this off present any practical differences or issues?

**Comment by null77** [comment] 2020-05-06 18:15
We have run into "spurious" warnings with invalid values for pNext/sType because of unspecced extensions. Maybe we could add a layer extension to tell the layers about these expected new values? I'm not sure how complicated that extension would be.

**Comment by mark-lunarg** [comment] 2020-05-06 19:07
@null77, yes, the warning we output for unsupported extensions is `Instance[or Device] Extension %s is not supported by this layer.  Using this extension may adversely affect validation results and/or produce undefined behavior.` Most of these spurious warnings likely originate in source code auto-generated from the Vulkan Registry.  

You could filter out those expected errors in your callbacks, but the perhaps the most efficient way to work with new extensions is to add them directly to a custom version of vk.xml and regenerate the source code used by the layers.  This should address any implicit-validation problems in this issue, but may not cover you for interactions with other extensions or APIs.

**Comment by null77** [comment] 2020-05-06 21:12
Custom XML is a neat idea. We could potentially do something like that in the long-term. It would be a bit of investment to get it set up for ourselves. For now we can probably disable the unique objects.

**Comment by mark-lunarg** [comment] 2020-05-11 17:13
@tobine, save to close this for now?

**Comment by tobine** [comment] 2020-05-13 14:47
We're still having internal discussions on this that may make this thread relevant. Let me hold it open and I'll update or close when we've reached consensus internally.

**Comment by tobine** [comment] 2020-05-14 22:21
We disabled unique layers and it made it through a first level of testing but then hit errors in broader testing including an individual hitting an error in app testing.
So, we've re-enabled unique handles and need to push on this issue to close on a good solution to allow unknown extensions while unique handles is enabled.

For one of the extensions that we're interested in, the extension struct doesn't contain any Vulkan object handles. For this simplest case, would it be reasonable to have some kind of "allowable unknown struct" exception list? If a struct type is in that list it should be perfectly safe for unique handles to ignore it and let it go through.

You can see the example extension in this [CL](https://chromium-review.googlesource.com/c/angle/angle/+/2185822) in the src/libANGLE/renderer/vulkan/vk_google_filtering_precision.h file, on line 24:

`
static constexpr VkStructureType VK_STRUCTURE_TYPE_SAMPLER_FILTERING_PRECISION_GOOGLE =
    static_cast<VkStructureType>(1000264000);
`

That's just one idea for a simpler, short-term solution.

If an extension struct has VK objects in it, would inclusion of that struct in the vk.xml be sufficient to allow unique handles to support the struct? 
Is there any serious discussion/plans for a de-handling approach like @jzulauf-lunarg mentioned or was that just an off-the-cuff comment? That's heavy handed to achieve the goal of this issue, but would certainly solve the unsupported extension issue.

**Comment by mark-lunarg** [comment] 2020-05-14 23:10
@tobine, I think we'll need to modify the pNext field of these structures to keep them in the chain, right?  And then restore them after the down-chain call?

**Closed** 2020-06-22 18:13 UTC
