### ISSUE TITLE
Hitting SYNC-HAZARD-WRITE-AFTER-READ 

### ISSUE THREAD

**Issue by HuYuxin** [KhronosGroup/Vulkan-ValidationLayers#7436] opened 2024-02-02 22:53 UTC
**Environment:**
 - OS: Linux
 - GPU and driver version: GeForce_GTX_1660
 - SDK or header version if building from repo: a3d2a718882e8ca68db0c6722264b47cf54b03e0
 - Options enabled (synchronization, best practices, etc.):

**Describe the Issue**

After merging this change https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/a3d2a718882e8ca68db0c6722264b47cf54b03e0, some test cases in chromium dawn (Implements WebGPU over different native Graphics API) starts to hit below VVL error on vulkan backend:

```
Validation Error: [ SYNC-HAZARD-WRITE-AFTER-READ ] Object 0: handle = 0x19d8006d5310, name = DawnDbg=1;Dawn_Queue, type = VK_OBJECT_TYPE_QUEUE; | MessageID = 0x376bc9df | vkQueueSubmit():  Hazard WRITE_AFTER_READ for entry 0, VkCommandBuffer 0x19d800796000[], Submitted access info (submitted_usage: SYNC_IMAGE_LAYOUT_TRANSITION, command: vkCmdPipelineBarrier, seq_no: 1, VkImage 0x130000000013[DawnDbg=1;Dawn_InternalTexture], reset_no: 1). Access info (prior_usage: SYNC_PRESENT_ENGINE_SYNCVAL_PRESENT_ACQUIRE_READ_SYNCVAL, read_barriers: VK_PIPELINE_STAGE_2_TOP_OF_PIPE_BIT|VK_PIPELINE_STAGE_2_DRAW_INDIRECT_BIT|VK_PIPELINE_STAGE_2_VERTEX_SHADER_BIT|VK_PIPELINE_STAGE_2_TESSELLATION_CONTROL_SHADER_BIT|VK_PIPELINE_STAGE_2_TESSELLATION_EVALUATION_SHADER_BIT|VK_PIPELINE_STAGE_2_GEOMETRY_SHADER_BIT|VK_PIPELINE_STAGE_2_FRAGMENT_SHADER_BIT|VK_PIPELINE_STAGE_2_EARLY_FRAGMENT_TESTS_BIT|VK_PIPELINE_STAGE_2_LATE_FRAGMENT_TESTS_BIT|VK_PIPELINE_STAGE_2_COLOR_ATTACHMENT_OUTPUT_BIT|VK_PIPELINE_STAGE_2_COMPUTE_SHADER_BIT|VK_PIPELINE_STAGE_2_BOTTOM_OF_PIPE_BIT|VK_PIPELINE_STAGE_2_HOST_BIT|VK_PIPELINE_STAGE_2_COMMAND_PREPROCESS_BIT_NV|VK_PIPELINE_STAGE_2_CONDITIONAL_RENDERING_BIT_EXT|VK_PIPELINE_STAGE_2_TASK_SHADER_BIT_EXT|VK_PIPELINE_STAGE_2_MESH_SHADER_BIT_EXT|VK_PIPELINE_STAGE_2_RAY_TRACING_SHADER_BIT_KHR|VK_PIPELINE_STAGE_2_FRAGMENT_SHADING_RATE_ATTACHMENT_BIT_KHR|VK_PIPELINE_STAGE_2_FRAGMENT_DENSITY_PROCESS_BIT_EXT|VK_PIPELINE_STAGE_2_TRANSFORM_FEEDBACK_BIT_EXT|VK_PIPELINE_STAGE_2_ACCELERATION_STRUCTURE_BUILD_BIT_KHR|VK_PIPELINE_STAGE_2_VIDEO_DECODE_BIT_KHR|VK_PIPELINE_STAGE_2_VIDEO_ENCODE_BIT_KHR|VK_PIPELINE_STAGE_2_ACCELERATION_STRUCTURE_COPY_BIT_KHR|VK_PIPELINE_STAGE_2_OPTICAL_FLOW_BIT_NV|VK_PIPELINE_STAGE_2_MICROMAP_BUILD_BIT_EXT|VK_PIPELINE_STAGE_2_COPY_BIT|VK_PIPELINE_STAGE_2_RESOLVE_BIT|VK_PIPELINE_STAGE_2_BLIT_BIT|VK_PIPELINE_STAGE_2_CLEAR_BIT|VK_PIPELINE_STAGE_2_INDEX_INPUT_BIT|VK_PIPELINE_STAGE_2_VERTEX_ATTRIBUTE_INPUT_BIT|VK_PIPELINE_STAGE_2_SUBPASS_SHADER_BIT_HUAWEI|VK_PIPELINE_STAGE_2_INVOCATION_MASK_BIT_HUAWEI|VK_PIPELINE_STAGE_2_CLUSTER_CULLING_SHADER_BIT_HUAWEI, )

```

The only change https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/a3d2a718882e8ca68db0c6722264b47cf54b03e0 introduced is to enforce the rule that TOP_OF_PIPE is equaivalent to NONE in the first sync scope when source access is 0. We don't seem to use TOP_OF_PIPE in those test cases for the swapchain (e.g. https://github.com/faro-oss/Dawn/blob/main/src/dawn/tests/end2end/SwapChainTests.cpp#L91), technically they should not be affected. Would you please help us shed some lights on what might lead to the VVL error after the [change](https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/a3d2a718882e8ca68db0c6722264b47cf54b03e)?

Thank you.

**Comment by artem-lunarg** [comment] 2024-02-03 00:09
@HuYuxin Looking into the error message, I think it's an issue similar to the one that I have just closed: https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7348. Or one more ticket from this area that also explains the topic: https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7353#issuecomment-1915833903.

`vkAcquireNextImageKHR`, which is modeled as a READ operation, collides with swapchain image layout transition (WRITE operation).

The provided error message suggests ALL_COMMANDS  (or a similar meta stage) is used by the semaphore wait. The above links have more detailed explanations, but the short answer is that semaphores synchronize commands that run on stages. Pipeline barrier commands and layout transitions do not run on any specific stage, so they cannot be guarded by the semaphore's ALL_COMMANDS and must form execution dependency with the semaphore's wait stages.

https://github.com/faro-oss/Dawn/blob/main/src/dawn/tests/end2end/SwapChainTests.cpp#L91 test calls `ClearTexture` that records command buffer, which starts with `BeginRenderPass`. Because the error message mention layout transition, render pass defines this layout transition, and the explanation in the first link is applicable.

Layout transition barrier during `BeginRenderPass` does not chain with wait semaphore. External subpass dependency is needed.

It worked before because TOP_OF_PIPE is part of implementation when no stage is specified, as in the case of layout transition done by the render pass without external subpass dependency. In the implementation before the fix, TOP_OF_PIPE from the layout transition chained with TOP_OF_PIPE from semaphore's ALL_COMMANDS, mistakenly creating execution dependency. Now it's fixed (NONE is used, equivalent to TOP_OF_PIPE in src scope, but cannot mistakenly be chained with other scopes).

I'm going to close this issue, since it's similar to recent reports but feel free to re-open if I missed something specific to your setup.

**Closed by artem-lunarg** 2024-02-03 00:09 UTC
Labels: Synchronization

**Comment by Kangz** [comment] 2024-02-05 16:13
Thank you @HuYuxin for filing this issue and @artem-lunarg for the detailed explanation. The qualification of this part of the Vulkan spec as "cursed" is an understatement. I was able to reproduce with VVL+Swiftshader and have a fix [here](https://dawn-review.googlesource.com/c/dawn/+/173463) (though we want to rework texture barrier tracking more in the future).

**Comment by artem-lunarg** [comment] 2024-02-06 23:12
@HuYuxin @Kangz After internal discussion it looks like my explanation was incorrect. That's something I'm still clarifying but the experts say ALL_COMMANDS should be fine to synchronize submission. My apologies for the confusion and inconvenience.  https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/a3d2a718882e8ca68db0c6722264b47cf54b03e0 was reverted.
