### ISSUE TITLE
Crash in gpu_validation.cpp when using buffer reference as a return value in GLSL

### ISSUE THREAD

**Issue by GabeRundlett** [KhronosGroup/Vulkan-ValidationLayers#5981] opened 2023-06-11 15:04 UTC
**Environment:**
 - OS: **Windows**
 - GPU: **RTX 3070**
 - SDK or header version if building from repo: **(SDK version) 1.3.243.0**
 - Options enabled (synchronization, best practices, etc.): **Default + Shader based: GPU Assisted**

**Describe the Issue**

When using buffer references in GLSL, if you return a buffer reference from a function (even if it's not used) the validation layers will crash in `gpu_validation.cpp`. Here's the simplest shader I've repro'd it with: (fragment shader, but it happens in compute as well. I didn't try vertex shaders)
```glsl
layout(location = 0) out vec4 color;
layout(buffer_reference, scalar, buffer_reference_align = 4) buffer TestBufferRef {
    uint data;
};
layout(push_constant, scalar) uniform push {
    TestBufferRef test_buffer_ref;
};
TestBufferRef get_ref() {
    return test_buffer_ref;
}
void main() {
    TestBufferRef ref = get_ref();
    color = vec4(1, 0, 1, 1);
}
```

**Expected behavior**

I expected it to behave just as if the buffer ref was assigned as an out parameter, which works just fine -
```glsl
layout(location = 0) out vec4 color;
layout(buffer_reference, scalar, buffer_reference_align = 4) buffer TestBufferRef {
    uint data;
};
layout(push_constant, scalar) uniform push {
    TestBufferRef test_buffer_ref;
};
void get_ref(out TestBufferRef result) {
    result = test_buffer_ref;
}
void main() {
    TestBufferRef ref;
    get_ref(ref);
    color = vec4(1, 0, 1, 1);
}
```

It also works just fine if I disable the Shader based GPU assisted validation

**Valid Usage ID**
There are no validation messages, just an immediate crash within the validation layers.

**Additional context**
Here's the call stack as seen within VSCode, which is the extent of debugging I'm able to do at the moment.
![image](https://github.com/KhronosGroup/Vulkan-ValidationLayers/assets/28205981/d1543520-a5cd-42b5-a20d-ca98951d8cb6)

**Comment by spencer-lunarg** [comment] 2023-06-12 04:29
Agree this is a bug for GPU-AV, but at the same time, it seems it might be something for the SPIRV-Tools repo...

If I take the shader and go 

```
./spirv-opt --inst-buff-addr-check issue.spv
```

I see the same crash. This will need to be solved in that code base regardless

I know for non-related ShaderVal, I hit this same issue where things were not going down function call chains to find the  correct value

**Comment by jeremyg-lunarg** [comment] 2023-06-13 21:10
The crash is in the aggressive dce elimination pass. It is run as part of the GPU-AV instrumentation but the crash can be reproduced like this  as well:
```
spirv-opt   --eliminate-dead-code-aggressive ../bad.spv -o dce.spv
```

**Comment by jeremyg-lunarg** [comment] 2023-06-13 21:16
closing since this is a SPIRV-Tools problem unrelated to GPU-AV

**Closed by jeremyg-lunarg** 2023-06-13 21:16 UTC
Labels: ShaderVal, GPU-AV
