### ISSUE TITLE
failures on driver 517.68 NDA

### ISSUE THREAD

**Issue by lunarpapillo** [KhronosGroup/Vulkan-ValidationLayers#4910] opened 2022-12-03 00:18 UTC
These failures appeared after updating to the 517.68 NDA driver.
- `VkLayerTest.InvalidDescriptorSetLayoutBinding`
- `VkLayerTest.CopyMutableDescriptors`
- `VkLayerTest.ValidateUpdatingMutableDescriptors`
- `VkLayerTest.MutableDescriptorPoolsWithPartialOverlap`
- `VkLayerTest.InvalidWriteMutableDescriptorSet`
- `VkLayerTest.MutableDescriptors`
- `VkLayerTest.DescriptorUpdateTemplate`
- `VkLayerTest.MutableDescriptorSetLayout`
- `VkLayerTest.DescriptorBufferDescriptorGetInfo`
- `VkPositiveLayerTest.CopyMutableDescriptors`

**Comment by lunarpapillo** [comment] 2022-12-03 00:18
The full output of the blacklist exercise may provide information on why particular tests failed:

[blacklist3.txt](https://github.com/KhronosGroup/Vulkan-ValidationLayers/files/10145150/blacklist3.txt)

**Comment by ncesario-lunarg** [comment] 2022-12-06 20:01
I think this is effectively a duplicate of https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4920.

**Comment by spencer-lunarg** [comment] 2023-06-12 06:40
This issue got stale - many of these tests are renamed and/or been worked on

I am currently trying to reduce which tests are "still" failing, from there will make the proper issues to looking into why

**Closed by spencer-lunarg** 2023-06-12 06:40 UTC
Labels: CI/Tests
