### ISSUE TITLE
Crashes and multiple possibly wrong VUIDs show up after 2d289701063cb554bdb0b84f192931365a9f3da4

### ISSUE THREAD

**Issue by y-novikov** [KhronosGroup/Vulkan-ValidationLayers#3915] opened 2022-03-26 19:20 UTC
**Describe the Issue**
When we roll 2d289701063cb554bdb0b84f192931365a9f3da4 into ANGLE, we see crashes on Android in:
  RELADDR   FUNCTION                                                                          FILE:LINE
  0000000000b54b48  VkPresentIdKHR const* LvlFindInChain<VkPresentIdKHR>(void const*)                 ../../third_party/vulkan-deps/vulkan-validation-layers/src/layers/generated/vk_typemap_helper.h:5928:47
  0000000000c1da68  ValidationStateTracker::PostCallRecordQueuePresentKHR(VkQueue_T*, VkPresentInfoKHR const*, VkResult)::$_1::operator()() const  ../../third_party/vulkan-deps/vulkan-validation-layers/src/layers/state_tracker.cpp:3432:39

Also, these VUIDs are reported in multiple tests:
    "VUID-VkPresentInfoKHR-pImageIndices-01296",
    "UNASSIGNED-CoreValidation-DrawState-QueueForwardProgress",
    "VUID-vkAcquireNextImageKHR-swapchain-01802",
    "VUID-VkPresentInfoKHR-pImageIndices-01430",

This commit is supposed to have affected only "UNASSIGNED-CoreValidation-NonAcquiredSwapchainImageUsed", so affecting other VUIDs is likely a bug.

**Valid Usage ID**
See above

**Environment:**
 - OS: Android, Linux, Mac, Windows
 - GPU: NVIDIA, Intel, SwiftShader
 - SDK or header version if building from repo: headers 1.3.209
 - Options enabled (synchronization, best practices, etc.): not sure

**Additional context**
More details in http://crbug.com/1310536

@ziga-lunarg, PTAL

**Comment by ziga-lunarg** [comment] 2022-03-27 00:52
Thanks for reporting the issue @y-novikov 
The crash should be fixed in #3916.
As for the additional VUIDs you're getting, that PR fixed more than just `UNASSIGNED-CoreValidation-NonAcquiredSwapchainImageUsed`, some code was executed at submit time, when it should have been after semaphore/fence wait and the PR fixed that. 
In #3917 I wrote a test that correctly reports `VUID-vkAcquireNextImageKHR-swapchain-01802`, that would not have been found before. 
Can you verify if the additional VUIDs you're seeing are correct or incorrect? Or let me know how I can reproduce them myself.

**Comment by y-novikov** [comment] 2022-03-28 18:59
Thanks, I can confirm that #3916 fixed the crash.
Going to look more into the additional VUIDs.

**Comment by ShabbyX** [comment] 2022-03-29 02:06
I can't reliably reproduce all four VVL failures, but at least the following are VVL bugs:

`VUID-VkPresentInfoKHR-pImageIndices-01296`. We have clearly got image index 1 from ANI:

```
ANI -> 0
QP  <- 0
ANI -> 1
QP  <- 1
../../src/tests/test_utils/ANGLETest.cpp:64: Failure
RendererVk.cpp:772 (DebugUtilsMessenger): [ VUID-VkPresentInfoKHR-pImageIndices-01296 ] Validation Error: [ VUID-VkPresentInfoKHR-pImageIndices-01296 ] Object 0: handle = 0x80000000008, type = VK_OBJECT_TYPE_SWAPCHAIN_KHR; | MessageID = 0xc7aabc16 | vkQueuePresentKHR: pSwapchains[0] image at index 1 was not acquired from the swapchain. The Vulkan spec states: Each element of pImageIndices must be the index of a presentable image acquired from the swapchain specified by the corresponding element of the pSwapchains array, and the presented image subresource must be in the VK_IMAGE_LAYOUT_PRESENT_SRC_KHR layout at the time the operation is executed on a VkDevice (https://github.com/KhronosGroup/Vulkan-Docs/search?q=)VUID-VkPresentInfoKHR-pImageIndices-01296)
                            Object: 0x80000000008 (type = Swapchain(1000001000))
```

`VUID-vkAcquireNextImageKHR-swapchain-01802`. We always alternate between ANI and QP, but it looks like VVL is not counting the QPs correctly:

```
[ RUN      ] MultithreadingTest.MakeCurrentSingleContext/ES3_Vulkan
ANI
QP
ANI
QP
ANI
QP
ANI
../../src/tests/test_utils/ANGLETest.cpp:64: Failure
RendererVk.cpp:776 (DebugUtilsMessenger): [ VUID-vkAcquireNextImageKHR-swapchain-01802 ] Validation Error: [ VUID-vkAcquireNextImageKHR-swapchain-01802 ] Object 0: handle = 0x80000000008, type = VK_OBJECT_TYPE_SWAPCHAIN_KHR; | MessageID = 0x3e97a888 | vkAcquireNextImageKHR: Application has already previously acquired 2 images from swapchain. Only 2 are available to be acquired using a timeout of UINT64_MAX (given the swapchain has 3, and VkSurfaceCapabilitiesKHR::minImageCount is 2). The Vulkan spec states: If the number of currently acquired images is greater than the difference between the number of images in swapchain and the value of VkSurfaceCapabilitiesKHR::minImageCount as returned by a call to vkGetPhysicalDeviceSurfaceCapabilities2KHR with the surface used to create swapchain, timeout must not be UINT64_MAX (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkAcquireNextImageKHR-swapchain-01802)
                            Object: 0x80000000008 (type = Swapchain(1000001000))
```

`VUID-VkPresentInfoKHR-pImageIndices-01430` looks very much like `VUID-VkPresentInfoKHR-pImageIndices-01296`.

As for `UNASSIGNED-CoreValidation-DrawState-QueueForwardProgress`, I could reproduce it a few times, but never again. If I can ever reproduce it again, I'll try and see what's going on. I suspect this to be a VVL bug too, but you never know.

**Closed** 2022-03-29 14:57 UTC

**Comment by y-novikov** [comment] 2022-03-29 21:53
Thank you for the investigation, @ShabbyX, and for the revert, @ziga-lunarg
