### ISSUE TITLE
synchronization validation failure related to dynamic descriptor set

### ISSUE THREAD

**Issue by cclao** [KhronosGroup/Vulkan-ValidationLayers#3605] opened 2021-12-14 22:06 UTC
**Describe the Issue**
synchronization validation failure related to dynamic descriptor set

**Valid Usage ID**
This is found with ANGLE. ANGLE is OpenGLES implementation on top of vulkan. We recently implemented buffer sub-allocation from VkBuffer and run into syncval failure. The failure goes away if I disable the use of VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC. My guess is that when dynamic uniform buffer is used, the actual buffer range been used for uniform buffer maybe not been calculated properly, which result in false hazard detection.

**Environment:**
 - OS: 
 - GPU:
 - SDK or header version if building from repo:
 - Options enabled (synchronization, best practices, etc.):

**Additional context**

**Comment by spencer-lunarg** [comment] 2022-10-14 06:59
sorry for the late reply. @cclao is there any more information about this issue, an api dump or something to help reproduce?

**Comment by cclao** [comment] 2022-10-14 17:23
Hi Spencer, to reproduce, you need to build ANGLE. 
1) Remove these lines of code that skip the specific VVL error described here.
https://chromium.googlesource.com/angle/angle/+/refs/heads/main/src/libANGLE/renderer/vulkan/RendererVk.cpp#406
to line 424
2) Build and install ANGLE, and run all tests we have. Or the alternative way is try to run in ANGLE CI bots and some tests will fail and you can start from that. 
There are more information in this bug as well
https://bugs.chromium.org/p/angleproject/issues/detail?id=6725

**Comment by spencer-lunarg** [comment] 2022-10-18 14:11
@cclao I commented out the 4 errors from the file (under `http://anglebug.com/6725`) and built ANGLE (release, hope that wouldn't matter) and ran

`angle/out/Release/bin$ ./run_angle_deqp_gles31_tests --use-angle=swiftshader --gtest_filter=functional.draw_indirect.compute_interop.separate.* --verbose --local-output --verbose-logging
`

and it passed the tests, am I missing something obvious here?

**Comment by mark-lunarg** [comment] 2022-10-18 15:10
@spencer-lunarg, DM'd you some hints.

**Comment by artem-lunarg** [comment] 2024-10-09 20:47
@ShabbyX @cclao I did not try to repro this specific issue but it's most likely it's from category for false-positives for suballocated buffers used together with indirect action command and it should be fixed by https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8674. More precisely we disabled corresponding check since they are not reliable.

**Closed** 2024-10-09 20:52 UTC
Labels: Bug
