### ISSUE TITLE
vkCmdDispatchBase crash on Vulkan 1.0 with validation layers enabled

### ISSUE THREAD

**Issue by TonyBarbour** [KhronosGroup/Vulkan-ValidationLayers#3579] opened 2021-11-30 17:02 UTC
**Describe the Issue**
Although vkCmdDispatchBase is not supported with Vulkan 1.0, it should not crash, and does not crash without validation layers enabled.  The following test crashes as is, but removing "instance_layers_.push_back(kValidationLayerName);" from layer_validation_tests.cpp allows it to run to completion.  Instead of crashing, it would be better for the validation layers to alert that using vkCmdDispatchBase in Vulkan 1.0 is not allowed.
```
TEST_F(VkLayerTest, DispatchBaseVulkan1) {
    ASSERT_NO_FATAL_FAILURE(Init());
    auto c_queue = m_device->GetDefaultComputeQueue();
    char const *csSource = 
        "#version 450\n"
        "void main() {\n" 
        "}\n";
    CreateComputePipelineHelper pipe(*this);
    pipe.InitInfo();
    pipe.cs_.reset(new VkShaderObj(m_device, csSource, VK_SHADER_STAGE_COMPUTE_BIT, this));
    pipe.InitState();
    pipe.CreateComputePipeline();

    m_commandBuffer->begin();
    vk::CmdBindPipeline(m_commandBuffer->handle(), VK_PIPELINE_BIND_POINT_COMPUTE, pipe.pipeline_);
    vk::CmdDispatchBase(m_commandBuffer->handle(), 1, 1, 1, 0, 0, 0);
    m_commandBuffer->end();
}
```

**Environment:**
 - OS: Win 10 or 11 
 - GPU: Nvidia RTX 3060
 - SDK or header version if building from repo: d950cc7
 - Options enabled (synchronization, best practices, etc.):

First reported in #3504

**Comment by sfricke-samsung** [comment] 2021-12-01 04:43
So before calling `vkCmdDispatchBaseKHR` we have a check in the stateless validation

```
    if (!IsExtEnabled(device_extensions.vk_khr_device_group)) skip |= OutputExtensionError("vkCmdDispatchBaseKHR", VK_KHR_DEVICE_GROUP_EXTENSION_NAME);
```

but now I am surprised we don't see m to have something for `vkCmdDispatchBase` that would check the device version (for device functions) being used

but we do have a `StatelessValidation::CheckPromotedApiAgainstVulkanVersion` function already and it would just be a matter of adjusting the generation code to find all promoted functions such as `vkCmdDispatchBase`

**Comment by sfricke-samsung** [comment] 2021-12-02 21:18
So even when I remove `instance_layers_.push_back(kValidationLayerName);` I still have it crash because my `vk::CmdDispatchBase` or even if I do

```cpp
    auto vkCmdDispatchBase = (PFN_vkCmdDispatchBase)vk::GetDeviceProcAddr(device(), "vkCmdDispatchBase");
    vkCmdDispatchBase(m_commandBuffer->handle(), 1, 1, 1, 0, 0, 0);
```

the function pointer is always `null`

**Comment by Tony-LunarG** [comment] 2021-12-02 21:33
The vk:: pointers are filled by GetProcAddr from the loader, and should be getting a non-null pointer back.  Also, using vkGetInstanceProcAddr should also get a non-null pointer back.  GetDeviceProcAddr should return a null pointer if the api level is < 1.1

**Comment by spencer-lunarg** [comment] 2023-01-08 09:51
So getting back to this, I am still not convinced this is a Validation Layer issue

To get a non-null pointer the test (or any app) must call `vkGetInstanceProcAddr` with Vulkan 1.1+

I can't think how you could both get a valid non-null pointer from `vkGetInstanceProcAddr` AND still be running Vulkan 1.0 in order to have the Validation Layers even check it (aka, I can't write a test to reproduce this)

**Comment by pc-john** [comment] 2023-01-09 07:53
> I can't think how you could both get a valid non-null pointer from `vkGetInstanceProcAddr` AND still be running Vulkan 1.0 in order to have the Validation Layers even check it (aka, I can't write a test to reproduce this)

I hope I am not mistaken, but you can link your application with libvulkan.so and use the call to <code>vkCmdDispatchBase</code>. Running objdump reveals that <code>vkCmdDispatchBase</code> is among the symbols if recent enough libvulkan.so is installed:
<pre>
objdump -T /usr/lib/x86_64-linux-gnu/libvulkan.so.1.2.198 | grep -i dispatch
00000000000321d0 g    DF .text  0000000000000009  Base        vkCmdDispatchIndirect
0000000000032ba0 g    DF .text  0000000000000009  Base        vkCmdDispatchBase
00000000000321c0 g    DF .text  0000000000000009  Base        vkCmdDispatch
</pre>

So, calling <code>vkCmdDispatchBase</code> is possible, even with 1.0 Vulkan Instance. Without validation layers, it is even running ok on my computer. While with validation layers, I see the crash with old SDK ([example code](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/3504#issuecomment-968908612), just instance version needs to be changed to 1.0). Not tested the latest validation layers.

**Comment by spencer-lunarg** [comment] 2023-01-09 09:21
> can link your application with libvulkan.so

Ok, that is fair, I guess the issue is we aren't going to be able to write a test for it in the Validation Layer test suite, but I can reproduce it locally this way and make sure the `CheckPromotedApiAgainstVulkanVersion` is generated

**Comment by spencer-lunarg** [comment] 2024-04-08 05:30
@pc-john I ran your simple DispatchBase example and if I change the version to `VK_API_VERSION_1_0` it crashes at `vkCmdDispatchBase` **both** with and without the Validation Layers enabled

Doing a 2nd look at this, I am not sure what there is to do in the VVL because it never even makes it to the layer

**Comment by pc-john** [comment] 2024-04-08 10:43
Thanks for looking on the issue. I re-run the DispatchBase example and I confirm your findings. With the recent Vulkan Loader and VVL, it is exactly as you say. I suggest just to close the issue.

**Comment by spencer-lunarg** [comment] 2024-04-08 13:36
> I suggest just to close the issue.

Sounds good, sorry this took forever to get eyes on (Tony retired end of last year)

glad to see things are at least working now as expected

thanks again for the simple test, was very easy to test with!

**Closed by spencer-lunarg** 2024-04-08 13:36 UTC
Labels: Bug, CI/Tests
