### ISSUE TITLE
VkStructureType (VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_3_FEATURES) which was added in VK_API_VERSION_1_3 but the current effective API version is 1.3.0 (0x00403000)

### ISSUE THREAD

**Issue by davidc538** [KhronosGroup/Vulkan-ValidationLayers#8820] opened 2024-11-06 19:30 UTC
**Environment:**
 - OS: macOS 15.0.1
 - GPU and driver version: Intel Iris Plus 645
 - SDK or header version if building from repo: SDK 1.3.296
 - Options enabled (synchronization, best practices, etc.): synchronization2

**Describe the Issue**
```
VUID-VkDeviceCreateInfo-pNext-pNext(ERROR / SPEC): msgNum: -1876993556 - Validation Error: [ VUID-VkDeviceCreateInfo-pNext-pNext ] Object 0: handle = 0x7f9870814620,
type = VK_OBJECT_TYPE_INSTANCE; | MessageID = 0x901f59ec | vkCreateDevice(): pCreateInfo->pNext includes a pointer to a VkStructureType (VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_3_FEATURES)
which was added in VK_API_VERSION_1_3 but the current effective API version is 1.3.0 (0x00403000). The Vulkan spec states: Each pNext member of any structure (including this one)
in the pNext chain must be either NULL or a pointer to a valid struct for extending VkDeviceCreateInfo (https://vulkan.lunarg.com/doc/view/1.3.280.0/mac/1.3-extensions/vkspec.html#VUID-VkDeviceCreateInfo-pNext-pNext)
```

**Expected behavior**

I believe this error message is incorrect, as I think my device only supports Vulkan API version 0.1.2.280. If the effective API version really is 1.3.0 then I shouldn't be getting this message at all but shouldn't my effective API version be limited to 1.2.X?

**Valid Usage ID**
If applicable, please include the validation messages encountered leading up to the issue

**Additional context**

<details>
<summary>code or terminal output</summary>

```sh
# callstacks, crashes, etc.
# EX:
Validation Error: [ VUID-vkCmdDrawMultiEXT-colorAttachmentCount-06188 ] Object 0: handle = 0x3d47e60 ...
```

</details>

**Comment by spencer-lunarg** [comment] 2024-11-06 20:49
Yes, the version gets tricky because your "Instance" (Loader) is 1.3 (so it **could** use a 1.3 driver), but your "Device" (driverR) is 1.2

seems the issue is our error message is showing 

> the current effective API version is 1.3.0

because it looking at your "Instance" version, not your "device" version

... so yes, still invalid to use, just a confusing/bugged error message

**Comment by spencer-lunarg** [comment] 2024-11-07 18:06
@davidc538 I looked at the code and it seems correct, the issue seems you are **not** using the 1.3.296 SDK version of Validation Layers

In your error message you have

> https://vulkan.lunarg.com/doc/view/1.3.280.0/mac/1.3-extensions/vkspec.html

This `1.3.280` is compiled into the Validation Layers, so you have an old version, the new version has correct code for this

```c++
VkPhysicalDeviceProperties device_properties = {};
DispatchGetPhysicalDeviceProperties(physicalDevice, &device_properties);
if (device_properties.apiVersion < VK_API_VERSION_1_3) {
    APIVersion device_api_version(static_cast<uint32_t>(device_properties.apiVersion));
    skip |= LogError("current effective API version is %s.", StringAPIVersion(device_api_version).c_str());
}
```

**Comment by davidc538** [comment] 2024-11-07 19:17
It looks like my VULKAN_SDK environment variable needed to be updated, thanks!

**Comment by spencer-lunarg** [comment] 2024-11-07 19:40
Closing as this should be fixed in a newest SDK... if not ping me here, also thanks for raising these issues, hard for use to test every possible combination of versions of devices in the wild

**Closed** 2024-11-07 19:39 UTC
Labels: Bug
