### ISSUE TITLE
vk_enum_string_helper.h does not work in C

### ISSUE THREAD

**Issue by happysmash27** [KhronosGroup/Vulkan-ValidationLayers#3233] opened 2021-08-31 12:26 UTC
**Describe the Issue**
helper_file_generator.py generates a vk_enum_string_helper.h that requires C++, instead of a seperate vk_enum_string_helper.hpp file for C++ and vk_enum_string_helper.h file for C. 

**Environment:**
 - OS: Gentoo
 - GPU: RX 480
 - SDK or header version if building from repo: Discovered on 1.2.162, but the same dependency is present on the latest version on GitHub. 
 - Options enabled (synchronization, best practices, etc.): Irrelevant; this appears to be hard-coded. 

**Additional context**

I discovered this via a no such file or directory error: 

```
/usr/include/vulkan/vulkan/vk_enum_string_helper.h:38:10: fatal error: string: Dosiero aŭ dosierujo ne ekzistas
   38 | #include <string>
      |          ^~~~~~~~
```

When trying to use this file. 

When replacing this with <string.h>, I get hundreds of lines of errors relating to the use of std::string. 

Why is C++ code in a .h file? Shouldn't it be .hpp? 

I will probably start modifying helper_file_generator.py to generate 2 files instead of 1 after submitting this issue, and may want to create a pull request to merge this into mainline. Is this the right route to take?

**Comment by happysmash27** [comment] 2021-08-31 13:00
Trying to run `scripts/helper_file_generator.py` gives a missing module error: 

```
Traceback (most recent call last):
  File "~/Gits/Vulkan-ValidationLayers/scripts/helper_file_generator.py", line 26, in <module>
    from generator import *
ModuleNotFoundError: No module named 'generator'
```

Trying to run `scripts/generate_source.py` also gives a missing module error, being unable to find 'reg'. 

Which modules is it looking for? I see no clear list of python dependencies in this repository, other than distutils which I already have.

**Comment by sfricke-samsung** [comment] 2021-08-31 14:39
`generator` and `reg` are from the [Vulkan-Headers](https://github.com/KhronosGroup/Vulkan-Headers/tree/master/registry) which should be grabbed correctly for you with the `update_deps.py` script I think

**Comment by mark-lunarg** [comment] 2021-08-31 14:40
The .h vs .hpp issue is a duplicate of[ issue #1](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/1).  We have no current plans to rename header files in the repository.

**Comment by happysmash27** [comment] 2021-08-31 15:53
Would a pull request be accepted, though? I will do whatever it takes to be able to print the enum values in an elegant way, up to even modifying all the other header files to match if it is necessary.

**Comment by ncesario-lunarg** [comment] 2021-08-31 16:32
As of right now, the Vulkan-ValidationLayers (VVL) is not intended to be used as an "API." i.e., all of the VVL source is only intended to be used and maintained for use _within_ VVL. While I understand the problem here and sympathize with it, this would add an additional burden to maintain more python code; python code that would be generating headers that would never get tested through any of the VVL test suites.

If the desire is a C header with the same functionality as `vk_enum_string_helper.h`, I would propose creating a new repo that similarly pulls down the `Vulkan-Headers` and generates the desired utility headers in C (or whatever other languages are of interest). In general that sort of thing seems like it would be useful (maybe something like this already exists?).

Closing this for now as we currently cannot support the new code that it would introduce.

**Closed by ncesario-lunarg** 2021-08-31 16:32 UTC

**Comment by juan-lunarg** [comment] 2023-08-29 23:17
FWIW years later. vk_enum_string_helper.h is now C compatible and lives in the https://github.com/KhronosGroup/Vulkan-Utility-Libraries
