### ISSUE TITLE
Bug in validation of push constants

### ISSUE THREAD

**Issue by ShabbyX** [KhronosGroup/Vulkan-ValidationLayers#2689] opened 2021-04-07 02:30 UTC
ANGLE is starting to see this sort of validation error:

```
[ VUID-vkCmdDraw-None-02698 ] Validation Error: [ VUID-vkCmdDraw-None-02698 ] Object 0: handle = 0x213e5033760, type = VK_OBJECT_TYPE_COMMAND_BUFFER; Object 1: handle = 0x7440000000744, type = VK_OBJECT_TYPE_PIPELINE_LAYOUT; Object 2: handle = 0x4b300000004b3, type = VK_OBJECT_TYPE_PIPELINE_LAYOUT; Object 3: handle = 0xc9d0000000c9d, type = VK_OBJECT_TYPE_PIPELINE; | MessageID = 0x77ed4aac | vkCmdDraw(): The active push constants of VkPipelineLayout 0x7440000000744[] isn't compatible with VkPipelineLayout 0x4b300000004b3[] of active VkPipeline 0xc9d0000000c9d[]. The Vulkan spec states: For each push constant that is statically used by the VkPipeline bound to the pipeline bind point used by this command, a push constant value must have been set for the same pipeline bind point, with a VkPipelineLayout that is compatible for push constants, with the VkPipelineLayout used to create the current VkPipeline, as described in Pipeline Layout Compatibility (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-vkCmdDraw-None-02698)
```

This is generated on any test that makes ANGLE use its internal shaders. For example:

```
$ ./angle_end2end_tests --gtest_filter=VertexAttributeTest.UnsignedPacked1010102ExtensionNormalized/ES3_Vulkan
```

I don't believe there to be an issue with the way ANGLE uses push constants.

**Comment by ShabbyX** [comment] 2021-04-07 03:57
Note that [this change](https://chromium-review.googlesource.com/c/angle/angle/+/2808854) suppresses this warning which should be reverted to reproduce the errors.

**Comment by ncesario-lunarg** [comment] 2021-04-07 16:34
This is most likely due to #2683.

The following are comments from @Tony-LunarG after he found a lot (I think around 86,000) new push constant errors in CTS (the specific test he looked at was `dEQP-VK.memory.pipeline_barrier.host_write_uniform_texel_buffer.1024`):
```
vkCmdBindPipeline
vkCmdBindDescriptorSets
vkCmdPushConstants
vkCmdDraw
vkCmdBindPipeline - Assuming this pipeline is "incompatible" wrt push constants
vkCmdBindDescriptorSets
vkCmdDraw
VUID-vkCmdDraw-None-02698(ERROR / SPEC): msgNum: 2012039852 - Validation Error: [ VUID-vkCmdDraw-None-02698 ] Object 0: handle = 0x2053fcfc168, type = VK_OBJECT_TYPE_COMMAND_BUFFER; Object 1: handle = 0xcee22d000000000f, type = VK_OBJECT_TYPE_PIPELINE_LAYOUT; Object 2: handle = 0xac47990000000017, type = VK_OBJECT_TYPE_PIPELINE_LAYOUT; Object 3: handle = 0x913a870000000018, type = VK_OBJECT_TYPE_PIPELINE; | MessageID = 0x77ed4aac | vkCmdDraw(): The active push constants of VkPipelineLayout 0xcee22d000000000f[] isn't compatible with VkPipelineLayout 0xac47990000000017[] of active VkPipeline 0x913a870000000018[]. The Vulkan spec states: For each push constant that is statically used by the VkPipeline bound to the pipeline bind point used by this command, a push constant value must have been set for the same pipeline bind point, with a VkPipelineLayout that is compatible for push constants, with the VkPipelineLayout used to create the current VkPipeline, as described in Pipeline Layout Compatibility (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-vkCmdDraw-None-02698)
    Objects: 4
        [0] 0x2053fcfc168, type: 6, name: NULL
        [1] 0xcee22d000000000f, type: 17, name: NULL
        [2] 0xac47990000000017, type: 17, name: NULL
        [3] 0x913a870000000018, type: 19, name: NULL
```

@sfricke-samsung would you be able to investigate this?

**Comment by sfricke-samsung** [comment] 2021-04-07 17:00
Sure, I will take a look, the push constant ambiguity bubble I popped awhile ago seems to still be spilling out lol

but 

```
vkCmdBindPipeline - Assuming this pipeline is "incompatible" wrt push constants
vkCmdBindDescriptorSets
vkCmdDraw
```

This seems like the desired behavior to have the error, will look what those CTS tests are doing as well

**Comment by sfricke-samsung** [comment] 2021-04-07 17:00
Sure, I will take a look, the push constant ambiguity bubble I popped awhile ago seems to still be spilling out lol

but 

```
vkCmdBindPipeline - Assuming this pipeline is "incompatible" wrt push constants
vkCmdBindDescriptorSets
vkCmdDraw
```

This seems like the desired behavior to have the error, will look what those CTS tests are doing as well

**Comment by ncesario-lunarg** [comment] 2021-04-07 17:02
Thanks @sfricke-samsung! I'll assign this to you in the short term.

**Comment by sfricke-samsung** [comment] 2021-04-10 15:12
So wrote a simple test, and confirmed the issue, the big problem is that `CMD_BUFFER_STATE` has a single `PushConstantRangesId` mapping, but really needs one for each [bindpoint](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#pipeline-bindpoint-commands).

I know we spec'ed this out lately to make sure each bind point being push was independent of the other if there were 2 different layouts with 2 `VkPushConstantRange` with a compute and non-compute stage set.

(more of just noting for future readers now) If the range in the layout had `VK_SHADER_STAGE_COMPUTE_BIT | VK_SHADER_STAGE_VERTEX_BIT` then when you go `vkCmdPushConstants` the `VUID-vkCmdPushConstants-offset-01796` forces you to push to both bind points

**Comment by ncesario-lunarg** [comment] 2021-04-13 20:15
Thanks for the quick investigation @sfricke-samsung. It sounds like the change as it currently exists in the code is incorrect, is that right?

**Comment by sfricke-samsung** [comment] 2021-04-13 20:17
well that's a fun question as still trying to get a 100% understanding on what is valid vs invalid still https://gitlab.khronos.org/vulkan/vulkan/-/issues/2602

**Closed** 2021-04-15 18:49 UTC
