### ISSUE TITLE
vulkan.h is quite expensive on Windows

### ISSUE THREAD

**Issue by randomascii** [KhronosGroup/Vulkan-ValidationLayers#2896] opened 2021-06-18 03:09 UTC
**Describe the Issue**
I am working on the Chromium bug crbug.com/796644 to try to reduce how many of our translation units include Windows.h. This mostly involves avoiding including Windows.h from header files as much as possible because this can pass the considerable cost (and namespace pollution - #define GetMessage GetMessageW, and so much more) on to many translation units.

While working on this I noticed that vulkan.h includes Windows.h when compiled for Windows. I found that vulkan_core.h does not include Windows.h and in most cases this is sufficient.

I get the impression that many Vulkan users just include vulkan.h as the obvious-best-choice, not realizing the cost. It may be impractical to change vulkan.h at this point, but perhaps the samples and documentation could recommend vulkan_core.h instead of vulkan.h.

As a single concrete example I noticed that layer_validation_tests.h does a #include of vulkan.h, making it (and any translation units that use it) expensive to compile on Windows (and prone to lots of namespace pollution).

**Environment:**
 - OS: Windows
 - GPU: n/a
 - SDK or header version if building from repo: tip-of-tree (I think)
 - Options enabled (synchronization, best practices, etc.): n/a

**Additional context**

I don't think this is a blocking bug for me since I am just changing a few dozen #includes of vulkan.h to vulkan_core.h in Chromium, and that should help my cause. This bug is filed more as a food-for-thought issue.

**Comment by ncesario-lunarg** [comment] 2021-06-18 05:10
> I get the impression that many Vulkan users just include vulkan.h as the obvious-best-choice

I think this is "by design," but that is probably more of a Vulkan-Docs question.

>  It may be impractical to change vulkan.h at this point, but perhaps the samples and documentation could recommend vulkan_core.h instead of vulkan.h.

This again is probably a question for Vulkan-Docs (maybe Vulkan-Headers?).

> As a single concrete example I noticed that layer_validation_tests.h does a #include of vulkan.h, making it (and any translation units that use it) expensive to compile on Windows (and prone to lots of namespace pollution).

I _think_ (I very well could be wrong), that, as you alluded to, this is the common use case, and therefore should be tested. If my assumption is incorrect and/or the user recommendation changes in the future, then I don't see a problem with using vulkan_core.h instead vulkan.h. We haven't seen particularly bad compile times on Windows, but I agree the name pollution is always annoying with windows.h, so it would be nice to avoid it if it makes sense.

**Comment by sfricke-samsung** [comment] 2021-06-18 18:28
I don't work with Windows at all, but I remember seeing this a while ago, maybe its useful, otherwise ignore me 😅 
https://github.com/zeux/volk/blob/master/volk.h#L32-L34

**Comment by randomascii** [comment] 2021-06-18 18:57
Chromium uses a similar tactic to allow some includes of Windows.h to be removed. Our "light" version can be seen here:

https://source.chromium.org/chromium/chromium/src/+/main:base/win/windows_types.h;l=9?q=windows_types.h&sq=

Even with this header file being used in numerous places in Chromium a recent analysis of our Windows builds have showed that Windows.h counts for 40% of the total size (in bytes) of code processed by the compiler. That number measures the total size of all translation units after preprocessing, with Windows.h and its sub-files being included tens of thousands of times.

This Windows.h overhead is part of the reason that the total source size of Chromium on Windows is 2.8x larger than on Linux.

I am hopeful that reducing Chromium's usage of Windows.h will improve our build times. It's impossible to estimate how much it might help. Even if it doesn't make a significant improvement in build times it will at least reduce (or control) macro namespace pollution.

Anyway, I hope that this context is useful.

**Comment by ncesario-lunarg** [comment] 2021-06-22 16:12
Thanks for all the info @randomascii @sfricke-samsung. It's not clear to me whether or not the tests should change, but I will investigate doing something similar for the validation layer code.

**Comment by jeremyg-lunarg** [comment] 2022-10-14 18:07
See also https://github.com/KhronosGroup/Vulkan-Headers/issues/234

**Comment by juan-lunarg** [comment] 2023-01-12 17:48
This ended up getting discussed quite a bit :
https://github.com/KhronosGroup/Vulkan-Docs/issues/2025

Closing this issue since it's better discussed at Vulkan-Docs.

**Closed by juan-lunarg** 2023-01-12 17:48 UTC
Labels: Enhancement
