### ISSUE TITLE
Validation layer isn't aware the image layout changes by external vulkan instance.

### ISSUE THREAD

**Issue by phuang** [KhronosGroup/Vulkan-ValidationLayers#1438] opened 2019-12-16 20:40 UTC
We are using two vulkan instances and vkimages are shared between them. I found vulkan instance will not be aware the image layout changes by another instance. For example:

1 Vulkan Instance A changes image layout to layout A
2. Vulkan Instance B changes image layout from layout A to layout B.
validation layer reports image src layout is not Layout A.

Is there a way to notify the validation layer that the image layout has been changed by external vulkan instance?

**Comment by mark-lunarg** [comment] 2019-12-16 21:03
The sharing of validation state across instances is not currently implemented. Can you please share the specific mechanism being used to share VkImages across instances?

**Comment by phuang** [comment] 2019-12-16 21:37
The memory object is shared via VK_KHR_external_semaphore_fd and VK_KHR_external_memory_fd extensions. The detail code is:
The exportable shared image is created at [1] .
The exportable memory is created at [2] .
The fd is imported into gl which is implemented on vulkan (Vulkan + Angle) at [3].
[4][5] are for synchronizing between two instances with layout information.

[1] https://cs.chromium.org/chromium/src/gpu/command_buffer/service/external_vk_image_backing.cc?q=external_vk_&sq=package:chromium&g=0&l=97
[2] https://cs.chromium.org/chromium/src/gpu/command_buffer/service/external_vk_image_backing.cc?q=external_vk_&sq=package:chromium&g=0&l=222
[3] https://cs.chromium.org/chromium/src/gpu/command_buffer/service/external_vk_image_backing.cc?sq=package:chromium&g=0&l=686
[4] https://cs.chromium.org/chromium/src/gpu/command_buffer/service/external_vk_image_gl_representation.cc?sq=package:chromium&g=0&l=98
[5] https://cs.chromium.org/chromium/src/gpu/command_buffer/service/external_vk_image_gl_representation.cc?sq=package:chromium&g=0&l=166

**Comment by ShabbyX** [comment] 2019-12-17 15:33
I think the validation layers should simply not generate an error if the source queue family of the transition is EXTERNAL.

**Comment by mark-lunarg** [comment] 2020-01-08 21:47
@phuang, could you please include the invalid error messages generated due to this issue?  We will try to suppress the messages as @ShabbyX suggests.

**Comment by mspang** [comment] 2020-05-04 00:49
Example error:

DebugUtilsMessenger(321): [ UNASSIGNED-CoreValidation-DrawState-InvalidImageLayout ] Validation Error: [ UNASSIGNED-CoreValidation-DrawState-InvalidImageLayout ] Object 0: handle = 0x3e66f650fb50, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x4dae5635 | Submitted command buff
er expects VkImage 0x1a000000001a[] (subresource: aspectMask 0x1 array layer 0, mip level 0) to be in layout VK_IMAGE_LAYOUT_GENERAL--instead, current layout is VK_IMAGE_LAYOUT_PREINITIALIZED.                                                                                            
                            Object: 0x3e66f650fb50 (type = Command Buffer(6))

**Comment by mspang** [comment] 2020-05-04 00:56
Does this seem reasonable?
https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/1802

**Comment by mspang** [comment] 2020-05-04 22:43
Should be fixed now.

phuang, can you verify?

**Comment by mspang** [comment] 2020-05-04 22:55
phuang confirmed it went away, should be safe to close

**Closed** 2020-07-31 16:54 UTC
