### ISSUE TITLE
SYNC-HAZARD-WRITE-AFTER-READ error with swapchain acquisition and command buffer submission

### ISSUE THREAD

**Issue by rossant** [KhronosGroup/Vulkan-ValidationLayers#7348] opened 2024-01-23 16:42 UTC
Hi, I'm having a validation error with my C visualization library since I updated the Vulkan SDK to LunarG SDK version 1.3.275. I spent a while figuring out what's going on and I ended up writing a minimal reproducible example in C: https://gist.github.com/rossant/610961a9f9b7210cb208b616e69f4f37

This code should create a black window with GLFW and return immediately. However, it raises the SYNC-HAZARD-WRITE-AFTER-READ validation error below which seems to relate to [the code that handles the synchronization between swapchain acquisition and command buffer submission](https://gist.github.com/rossant/610961a9f9b7210cb208b616e69f4f37#file-vulkan_sync_warning-c-L536-L586):

```
    validation layer: Validation Error: [ SYNC-HAZARD-WRITE-AFTER-READ ] Object 0: handle =
    0x5599afbbf520, type = VK_OBJECT_TYPE_QUEUE; | MessageID = 0x376bc9df | vkQueueSubmit(): Hazard
    WRITE_AFTER_READ for entry 0, VkCommandBuffer 0x5599b202e960[], Submitted access info
    (submitted_usage: SYNC_IMAGE_LAYOUT_TRANSITION, command: vkCmdBeginRenderPass, seq_no: 1,
    renderpass: VkRenderPass 0xcad092000000000d[], reset_no: 1). Access info (prior_usage:
    SYNC_PRESENT_ENGINE_SYNCVAL_PRESENT_ACQUIRE_READ_SYNCVAL, read_barriers:
    VK_PIPELINE_STAGE_2_COLOR_ATTACHMENT_OUTPUT_BIT|VK_PIPELINE_STAGE_2_BOTTOM_OF_PIPE_BIT, ,
    batch_tag: 1, vkAcquireNextImageKHR aquire_tag:1: VkSwapchainKHR 0xf443490000000006[],
    image_index: 0image: VkImage 0xcb3ee80000000007[]).
```

It's likely that my code has a bug as I've always felt Vulkan synchronization difficult to understand. I did not get this error message with earlier versions of the SDK, but it might have been because these checks were not enabled by default.

I should add that the error disappears if I replace:

```c
VkPipelineStageFlags waitStages[] = {VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT};
```

with:

```c
VkPipelineStageFlags waitStages[] = {VK_PIPELINE_STAGE_ALL_COMMANDS_BIT};
```

which may not be a good practice though (I actually get a warning if I do this).

Anyone could help me understand where the error comes from, or whether it's a bug in the validation layers? Thank you in advance.

**Configuration**

```
LunarG SDK version 1.3.275
Ubuntu 22.04
Vulkan Instance Version: 1.3.275
NVIDIA GeForce RTX 2070 SUPER
NVIDIA-SMI 535.129.03             Driver Version: 535.129.03   CUDA Version: 12.2
```

**Comment by rossant** [comment] 2024-01-25 20:49
I think this is fixed after a suggestion on [StackOverflow](https://stackoverflow.com/a/77882528/1595060) which was to add an image barrier in the command buffer, right before the beginning of the renderpass. Feel free to close if you think this is a proper fix!

**Comment by rossant** [comment] 2024-01-25 22:50
I think this is partly fixed after a suggestion on [StackOverflow](https://stackoverflow.com/a/77882528/1595060) which was to add an image barrier in the command buffer, right before the beginning of the renderpass. However I'm not quite sure why this is required given that I'm using a renderpass and I'm NOT using dynamic rendering.

Also, I actually get another error message when using a depth buffer:

```
validation layer: Validation Error: [ SYNC-HAZARD-WRITE-AFTER-WRITE ] Object 0: handle = 0x5597ad224310, type = VK_OBJECT_TYPE_QUEUE; | MessageID = 0x5c0ec5d6 | vkQueueSubmit():  Hazard WRITE_AFTER_WRITE for entry 0, VkCommandBuffer 0x5597ada23b00[], Submitted access info (submitted_usage: SYNC_IMAGE_LAYOUT_TRANSITION, command: vkCmdPipelineBarrier, seq_no: 2, VkImage 0xd175b40000000013[], reset_no: 2). Access info (prior_usage: SYNC_LATE_FRAGMENT_TESTS_DEPTH_STENCIL_ATTACHMENT_WRITE, write_barriers: 0, queue: VkQueue 0x5597ad224310[], submit: 0, batch: 0, batch_tag: 4, command: vkCmdEndRenderPass, command_buffer: VkCommandBuffer 0x5597ada23b00[], seq_no: 4, renderpass: VkRenderPass 0xec4bec000000000b[], reset_no: 2).
```

**Comment by artem-lunarg** [comment] 2024-02-02 18:00
@rossant Thanks for the report, looking into it.

**Comment by rossant** [comment] 2024-02-02 21:20
Thanks for taking a look! I don't remember if I pushed a fix on the gist, sorry, but I'm pretty sure this [earlier version](https://gist.github.com/rossant/610961a9f9b7210cb208b616e69f4f37/fdd31e87f1d40f2f292e4a85792c2120d740b506) had the warnings. Also, the warnings only appear with the SDK 1.3.275, not 1.3.268.

**Comment by artem-lunarg** [comment] 2024-02-02 21:22
Yes in 1.3.275 we enable submit-time synchronization validation by default (previously it was in alpha stage).

**Comment by artem-lunarg** [comment] 2024-02-02 22:55
@rossant I checked the previous version and can reproduce the issue. I agree with @karl-lunarg who suggested on SO that it's similar to https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7193#issuecomment-1875960974 (appreciate his help).

Still I would recommend a bit different solution for two reasons. 

The first reason is that I'm not sure that the added `vkCmdPipelineBarrier` can actually chain (i.e., create execution dependency) with the layout transition performed by the render pass. It's a subtle topic, but render pass creates implicit `VK_SUBPASS_EXTERNAL` dependency, and it uses `VK_PIPELINE_STAGE_NONE` as the source stage, and it is not possible to create execution dependency with the NONE stage. I have a suspicion that the reason it works is due to the bug in our code (mainly note for myself: NONE is conveniently equal to zero, but our implementation could end up with TOP_OF_PIPE stage during computations which has value 1 and can result in non-zero values during binary AND operation, that allows it to chain and create execution dependency in the scenarios where NONE can't). I need to think more about this, and it could be I made a mistake in reasoning, but for this ticket it's not that important, because there is a better way to do this!

The second reason is that there is a feature designed specifically for this scenario. The problem with `vkCmdPipelineBarrier` (even if that approach is correct) is that you end up with two barriers - the pipeline command itself and the barrier as part of a render pass layout transition. Also, the provided sample does layout transition in `vkCmdPipelineBarrier`, so the image layout is unnecessarily transitioned two times, too (vkCmdPipelineBarrier can set oldLayout to be equal to newLayout to not transition). 

The proper way to fix this issue is to use subpass dependencies (`VkSubpassDependency`), specifically a subpass dependency between `VK_SUBPASS_EXTERNAL` (everything that happens before render pass) on one side and subpass 0 on the other. Then, you can specify `VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT` for that subpass dependency in order to chain with `vkQueueSubmit`'s wait semaphore.

I will close this ticket because, with my current understanding, it is not a synchronization issue. But if there is new evidence, feel free to re-open.

I'd recommend the Vulkan Discord channel as a place to discuss the tricky sides of Vulkan. It is an active community with a lot of people passionate about Vulkan. There is also a Synchronization chat there. Thanks for the hint about the potential issue in our code that allows the current example to pass validation. I need to create an internal ticket to investigate this, but the current recommendation is to try to use subpass dependency with `VK_SUBPASS_EXTERNAL` for `srcSubpass` and 0 for `dstSubpass`.

**Closed by artem-lunarg** 2024-02-02 22:55 UTC
Labels: Synchronization

**Comment by rossant** [comment] 2024-02-03 09:19
Thank you for the detailed report! I'm going to test your suggestion and will report back here.
