### ISSUE TITLE
spirv validation throws illegal error on task/mesh shader data

### ISSUE THREAD

**Issue by pixeljetstream** [KhronosGroup/Vulkan-ValidationLayers#2102] opened 2020-08-10 10:43 UTC
Validation layer complaints about location assignment missing, but location assignment is not required for "taskNV" qualified data shared between mesh/task shader.

see also https://github.com/KhronosGroup/SPIRV-Tools/issues/3673

```
ERROR: UNASSIGNED-CoreValidation-Shader-InconsistentSpirv
 --> Validation Error: [ UNASSIGNED-CoreValidation-Shader-InconsistentSpirv ] Object 0: handle = 0x2b93bb40468, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x6bbb14 | SPIR-V module not valid: Member index 0 is missing a location assignment
  0x0.07ff676e658f0p-1022sk = OpTypeStruct 821997464int v4uint _arr_uchar_uint_32
```

**Comment by ziga-lunarg** [comment] 2021-09-20 22:34
@pixeljetstream Can you provide the shaders you get this error with? I am unable to reproduce it.

**Comment by ziga-lunarg** [comment] 2022-01-30 13:03
I believe this issue was resolved in SPIRV-Tools, so I am closing this. If this is not true you can reopen @pixeljetstream

**Closed by ziga-lunarg** 2022-01-30 13:03 UTC
Labels: ShaderVal
