### ISSUE TITLE
Assertion failure when running VK-GL-CTS test

### ISSUE THREAD

**Issue by rg3igalia** [KhronosGroup/Vulkan-ValidationLayers#2500] opened 2021-01-26 11:43 UTC
**Describe the Issue**
When running the VK-GL-CTS test dEQP-VK.image.mismatched_formats.image_read.d16_unorm_with_r16, the layers (built from source in debug mode) crash with an assertion failure. As of the time I'm writing this, the test [contains a mistake ](https://github.com/KhronosGroup/VK-GL-CTS/blob/b29bf0434c16796dc48a17a52c7fe219d558af31/external/vulkancts/modules/vulkan/image/vktImageMismatchedFormatsTests.cpp#L394) that makes it try to create an image view with the color image aspect for a depth-only image. The layers crash with the following assertion failure:

```
Test case 'dEQP-VK.image.mismatched_formats.image_read.d16_unorm_with_r16'..
Validation Error: [ UNASSIGNED-CoreValidation-DrawState-InvalidImageAspect ] Object 0: handle = 0x80000000008, type = VK_OBJECT_TYPE_IMAGE; | MessageID = 0x90ef715d | vkCreateImageView(): Depth-only image formats must have the VK_IMAGE_ASPECT_DEPTH_BIT set.
deqp-vk: ../layers/subresource_adapter.h:131: uint32_t subresource_adapter::RangeEncoder::LowerBoundFromMask(VkImageAspectFlags) const: Assertion `mask & limits_.aspectMask' failed.
Aborted (core dumped)
```

**Valid Usage ID**
Prior to the crash, UNASSIGNED-CoreValidation-DrawState-InvalidImageAspect is correctly produced.

**Environment:**
 - OS: Linux
 - GPU: AMD Radeon RX 590 running RADV driver from Mesa master.
 - SDK or header version if building from repo: Building from the repo, commit 79b22370b0b0d6b9258dbb5e74bd671203763c02.
 - Options enabled (synchronization, best practices, etc.):

**Additional context**
Note: there is an in-flight CL to fix validation issues with these tests. When they are removed, the assertion failure will go away too.

**Comment by sfricke-samsung** [comment] 2021-01-30 06:59
So for context, I think the error message is missing the word "only"

```cpp
if ((aspect_mask & VK_IMAGE_ASPECT_DEPTH_BIT) != VK_IMAGE_ASPECT_DEPTH_BIT) {
            skip |= LogError(image, vuid, "%s: Depth-only image formats must have the VK_IMAGE_ASPECT_DEPTH_BIT set.", func_name);
```

Also these error messages in `ValidateImageAspectMask()` should 100% be printing out the format actually in the error (I am already in progress of a PR for that)

**Comment by sfricke-samsung** [comment] 2021-01-30 07:03
Making an action to add better error message to `ValidateImageAspectMask()` to print the format and aspect mask being used

**Comment by sfricke-samsung** [comment] 2021-02-01 18:38
@rg3igalia with the improved wording merged, curious if you grabbed ToT of validation layers and re-ran if you could give the new error as it will either quickly point out what is actually happening

**Comment by rg3igalia** [comment] 2021-02-02 08:39
I just did. Validation error (correct) and later crash:

```
Test case 'dEQP-VK.image.mismatched_formats.image_read.d16_unorm_with_r16'..
Validation Error: [ UNASSIGNED-CoreValidation-DrawState-InvalidImageAspect ] Object 0: handle = 0x80000000008, type = VK_OBJECT_TYPE_IMAGE; | MessageID = 0x90ef715d | vkCreateImageView(): Using format (VK_FORMAT_D
16_UNORM) with aspect flags (VK_IMAGE_ASPECT_COLOR_BIT) but depth-only image formats must have the VK_IMAGE_ASPECT_DEPTH_BIT set.
deqp-vk: ../layers/subresource_adapter.h:131: uint32_t subresource_adapter::RangeEncoder::LowerBoundFromMask(VkImageAspectFlags) const: Assertion `mask & limits_.aspectMask' failed.
Aborted (core dumped)
```

**Comment by ziga-lunarg** [comment] 2022-04-11 16:37
@rg3igalia It seems to me that the issue was resolved, can you test to confirm?

**Comment by rg3igalia** [comment] 2022-04-13 09:15
Not entirely sure if the crash is fixed. I've just updated the layers to master as of now (5501a60aa) and modified the CTS test so it contains the mistake again, by applying the following patch to the sources:

```
--- a/external/vulkancts/modules/vulkan/image/vktImageMismatchedFormatsTests.cpp
+++ b/external/vulkancts/modules/vulkan/image/vktImageMismatchedFormatsTests.cpp
@@ -417,7 +417,7 @@ tcu::TestStatus MismatchedFormatTestInstance::iterate (void)
 		VK_CHECK(vk.bindImageMemory(device, *storageImage, storageAllocation->getMemory(), storageAllocation->getOffset()));
 	}
 
-	const auto						subresourceRange	= makeImageSubresourceRange(getImageAspectFlags(tcuFormat), 0u, 1u, 0u, 1u);
+	const auto						subresourceRange	= makeImageSubresourceRange(VK_IMAGE_ASPECT_COLOR_BIT, 0u, 1u, 0u, 1u);
 	Move<VkImageView>				storageImageView	= makeImageView(vk, device, *storageImage, VK_IMAGE_VIEW_TYPE_2D, m_format, subresourceRange);
 	VkDescriptorImageInfo			storageImageInfo	= makeDescriptorImageInfo(DE_NULL, *storageImageView, VK_IMAGE_LAYOUT_GENERAL);
 
```

When running the test on RADV again, I get the same crash on the validation layers:

```
$ ./deqp-vk --deqp-validation=enable -n dEQP-VK.image.mismatched_formats.image_read.d16_unorm_with_r16
Writing test log into TestResults.qpa
dEQP Core git-455f114b931a4dcb35b7a2ac699a5445bbcdc7c9 (0x455f114b) starting..
  target implementation = 'Default'
UNASSIGNED-khronos-Validation-debug-build-warning-message(WARN / PERF): msgNum: 648835635 - Validation Performance Warning: [ UNASSIGNED-khronos-Validation-debug-build-warning-message ] Object 0: handle = 0x5188ab0, type = VK_OBJECT_TYPE_INSTANCE; | MessageID = 0x26ac7233 | VALIDATION LAYERS WARNING: Using debug builds of the validation layers *will* adversely affect performance.
    Objects: 1
        [0] 0x5188ab0, type: 1, name: NULL
VUID_Undefined(WARN / SPEC): msgNum: 2044605652 - Validation Warning: [ VUID_Undefined ] Object 0: handle = 0x5b14e80, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x79de34d4 | Device Extension VK_EXT_shader_module_identifier is not supported by this layer.  Using this extension may adversely affect validation results and/or produce undefined behavior.
    Objects: 1
        [0] 0x5b14e80, type: 3, name: NULL
VUID_Undefined(WARN / SPEC): msgNum: 2044605652 - Validation Warning: [ VUID_Undefined ] Object 0: handle = 0x5b14e80, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x79de34d4 | Device Extension VK_KHR_dynamic_rendering support is incomplete, incorrect results are possible.
    Objects: 1
        [0] 0x5b14e80, type: 3, name: NULL

Test case 'dEQP-VK.image.mismatched_formats.image_read.d16_unorm_with_r16'..
UNASSIGNED-CoreValidation-DrawState-InvalidImageAspect(ERROR / SPEC): msgNum: -1863356067 - Validation Error: [ UNASSIGNED-CoreValidation-DrawState-InvalidImageAspect ] Object 0: handle = 0xead9370000000008, type = VK_OBJECT_TYPE_IMAGE; | MessageID = 0x90ef715d | vkCreateImageView(): Using format (VK_FORMAT_D16_UNORM) with aspect flags (VK_IMAGE_ASPECT_COLOR_BIT) but depth-only image formats must have the VK_IMAGE_ASPECT_DEPTH_BIT set.
    Objects: 1
        [0] 0xead9370000000008, type: 10, name: NULL
deqp-vk: ../layers/subresource_adapter.h:137: uint32_t subresource_adapter::RangeEncoder::LowerBoundFromMask(VkImageAspectFlags) const: Assertion `mask & limits_.aspectMask' failed.
Aborted (core dumped)
```

Let me know if you need more info.

**Comment by ncesario-lunarg** [comment] 2022-04-13 17:18
@rg3igalia are you getting a crash without a debug build of VVL? I can't reproduce this with a release build of VVL; i.e., running in release, I see several error messages produced, and then the program exits successfully.

If we were hitting the assert and _no_ errors were getting logged, that would definitely sound like a bug in VVL, but that does not appear to be happening here. Are you blocked in some way by this particular assert?

In general, once we hit an error in VVL, a crash is entirely possible and "acceptable," but that doesn't seem to be happening here either.

Closing for now, but we can re-open if necessary.

**Closed by ncesario-lunarg** 2022-04-13 17:18 UTC

**Comment by rg3igalia** [comment] 2022-04-19 08:53
Hey @ncesario-lunarg, thanks for all that info! Answering your questions:

* No, I don't see the crash with, for example, a RelWithDebInfo build of the layers.
* I'm not blocked in any way by this particular assert, just reported the problem while fixing the CTS bug.

I wasn't aware once the layers hit a validation error, a crash was "acceptable". To give you more context, I normally build the layers myself when developing CTS tests because the OS packages are many times "outdated" for my needs, depending on the box and OS I need to run CTS on. Since the instructions in BUILD.md use a debug build, that's what I've been using. Performance of the layers is not an issue generally when running CTS, as most tests are small and run fast.

I see a small benefit to making the layers "resistant" to crashes when developing tests for new extensions which are not yet supported by the layers. Sometimes those new extensions introduce spurious validation errors due to the layers not understanding the extension yet, but other validation errors can signal problems in CTS code, so taking a look at all validation errors and having the layers not crash can be interesting for my use case. In any case, no big deal.

My assumption was that the assert was either checking something that didn't need to be checked for the layers to work correctly or that some checks should be skipped when the condition was not met but, after reading your comment, I don't see anything that needs to be fixed as such. Perhaps a possible improvement would be to use other build type in the build instructions?

**Comment by ncesario-lunarg** [comment] 2022-04-19 20:29
Thank you for the comments @rg3igalia!

> I wasn't aware once the layers hit a validation error, a crash was "acceptable"

_Not_ crashing is definitely preferred :)  In some cases, ensuring we do not crash becomes impractical due to the amount of redundant state checking that would be required. That said, if a crash can be easily avoided, we try to (or at least we should) avoid crashing. I don't think this is one of those cases, though, since we are not crashing, but rather hitting an assert, which is expected here.

> taking a look at all validation errors and having the layers not crash can be interesting for my use case

Once an error is logged, it is assumed that all of the state that has been tracked within the VL is invalid (i.e., the Vulkan spec has been violated), so theoretically, all subsequent errors logged are based on invalid data (though I know many of them _may_ be valid in practice).
