### ISSUE TITLE
Remove `PostCallRecordPipelineCreationsRT `

### ISSUE THREAD

**Issue by arno-lunarg** [KhronosGroup/Vulkan-ValidationLayers#8531] opened 2024-09-12 16:13 UTC
https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8499/files#r1757107411

**Comment by spencer-lunarg** [comment] 2024-09-12 16:16
duplicate of https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8530

**Closed by spencer-lunarg** 2024-09-12 16:16 UTC
Labels: RT
