### ISSUE TITLE
Final layout not ignored for renderpass attachments not referenced by any subpass

### ISSUE THREAD

**Issue by asuonpaa** [KhronosGroup/Vulkan-ValidationLayers#300] opened 2018-08-30 09:37 UTC
Vulkan spec section 7.1 states:

> If an attachment is not used by any subpass, then loadOp, storeOp, stencilStoreOp, and stencilLoadOp are ignored, and the attachment’s memory contents will not be modified by execution of a render pass instance.

Since memory contents should not be modified I would assume the final layout of an unreferenced attachment should be ignored too. However validation tracks the new layout even for these attachments.

**Comment by asuonpaa** [comment] 2018-08-30 09:38
I can try to come up with a pull request to address this issue.

**Comment by jzulauf-lunarg** [comment] 2018-10-08 22:01
@asuonpaa -- linking to open spec issue for resolution.

**Comment by jzulauf-lunarg** [comment] 2018-10-09 11:04
Given the response from the API working group (in 821 noted above), closing this as "works as intended"

**Closed by jzulauf-lunarg** 2018-10-09 11:04 UTC
