### ISSUE TITLE
VK_LAYER_LUNARG_core_validation invalid report of buffer binding to the VkMemoryDevice

### ISSUE THREAD

**Issue by danylorudenko** [KhronosGroup/Vulkan-ValidationLayers#257] opened 2018-07-31 04:44 UTC
`

    VkBuffer buffer = VK_NULL_HANDLE;

    VkBufferCreateInfo bufferInfo;
    bufferInfo.sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO;
    bufferInfo.pNext = nullptr;
    bufferInfo.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
    bufferInfo.queueFamilyIndexCount = 0;
    bufferInfo.pQueueFamilyIndices = nullptr;
    bufferInfo.size = 256;
    bufferInfo.usage = VK_BUFFER_USAGE_VERTEX_BUFFER_BIT | VK_BUFFER_USAGE_INDEX_BUFFER_BIT;
    bufferInfo.flags = VK_FLAGS_NONE;

    VK_ASSERT(table.vkCreateBuffer(device.Handle(), &bufferInfo, nullptr, &buffer));

    VkMemoryRequirements memRequirements;
    table.vkGetBufferMemoryRequirements(device.Handle(), buffer, &memRequirements);

    std::uint32_t memType = VK_MAX_MEMORY_TYPES;
    VkFlags requiredMemoryProperty = VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT;
    for (auto i = 0u; i < device.Properties().memoryProperties.memoryTypeCount; ++i) {
        auto memProps = device.Properties().memoryProperties.memoryTypes[i].propertyFlags;
        if (((memProps & requiredMemoryProperty) == requiredMemoryProperty) && 
            (((1 << i) & memRequirements.memoryTypeBits) != 0)) {
            memType = i;
            break;
        }
    }
    assert(memType != VK_MAX_MEMORY_TYPES);

    VkMemoryAllocateInfo allocInfo;
    allocInfo.sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;
    allocInfo.pNext = nullptr;
    allocInfo.allocationSize = 1024 * 1024;
    allocInfo.memoryTypeIndex = memType;

    VkDeviceMemory memory;
    VK_ASSERT(table.vkAllocateMemory(device.Handle(), &allocInfo, nullptr, &memory));

    VK_ASSERT(table.vkBindBufferMemory(device.Handle(), buffer, memory, 0));`

On the last line VK_LAYER_LUNARG_core_validation reports two following messages which basically duplicate each other and I don't know if this is intended behavior:

> DEBUG_LAYER
Message type: ERROR|
Layer prefix: Validation
Message:  [ VUID-vkBindBufferMemory-buffer-01029 ] Object: 0x2af5623db20 (Type = 8) | In vkBindBufferMemory(), attempting to bind memory (0x2af5623db20) to object (0x2af5631a7c0) which has already been bound to mem object 0x2af5623db20. The spec valid usage text states 'buffer must not already be backed by a memory object' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkBindBufferMemory-buffer-01029)
Object type: VK_DEBUG_REPORT_OBJECT_TYPE_DEVICE_MEMORY_EXT, id: (2952087722784)

> DEBUG_LAYER
Message type: ERROR|
Layer prefix: Validation
Message:  [ VUID-vkBindBufferMemory-buffer-01029 ]  [ VUID-vkBindBufferMemory-buffer-01029 ] Object: 0x2af5623db20 (Type = 8) | In vkBindBufferMemory(), attempting to bind memory (0x2af5623db20) to object (0x2af5631a7c0) which has already been bound to mem object 0x2af5623db20. The spec valid usage text states 'buffer must not already be backed by a memory object' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkBindBufferMemory-buffer-01029)
Object type: VK_DEBUG_REPORT_OBJECT_TYPE_DEVICE_MEMORY_EXT, id: (2952087722784)

The installed version of VulkanSDK is 1.1.77.0
VkInstance was created both with VK_LAYER_LUNARG_standard_validation and VK_LAYER_LUNARG_core_validation producing the same result.

So

1. Is duplicating reports in such manner is okay?
2. Is this even a valid error report based for the fiven application code?

**Comment by shannon-lunarg** [comment] 2018-09-13 23:07
Hello, @danylorudenko. I have been working on reproducing this issue but have so far been unsuccessful. The error being reported (concerning `VUID-vkBindBufferMemory-buffer-01029`) occurs when there is an attempt to bind memory to a `VkBuffer` object more than once. In the code snippet you provided, I cannot discern where a duplicate attempt to bind memory to the same buffer occurs--actually, if you are receiving the error twice there are three attempts to bind memory to the same buffer object. (To address one of your questions, yes, duplicate error reports are perfectly acceptable for duplicate errors.) A test in our testing framework exists for `VUID-vkBindBufferMemory-buffer-01029` and functions as intended. Is it possible your application performs this memory/buffer binding on the same object multiple times? Perhaps the `VkBuffer` object is not being destroyed before reusing the `VkBuffer` variable and binding the buffer memory again? If these are not possibilities can you provide me with sample code so I can explore this issue further?

**Comment by shannon-lunarg** [comment] 2018-09-21 21:04
I am going to go ahead and close this issue. If the problem persists, please reopen the issue and we can explore it further. Thanks!

**Closed by shannon-lunarg** 2018-09-21 21:04 UTC
Labels: bug

**Comment by danylorudenko** [comment] 2018-09-30 13:28
Hello, @shannon-lunarg 

Sorry for the late response.

Today I've installed the latest SDK (1.1.82.1), double-checked my code and Vulkan spec wheather it could be my fault that this error message occurs and still couldn't find any actions that spec prohibits to do. 

The issue has been reproduced by emplacing almost the same example at the start of the application right after logical device initialization. There are no binding or resource creation calls before the example part.

You can have a look at the example and build it from this branch [https://github.com/danylorudenko/vk-research/tree/buffer-binding-issue](here) 
VKW::Instance checks if needed layers are supported and initializes VkInstance and VKW::Device checks if required extensions are supported, chooses VkPhysicalDevice and initializes VkDevice.
Example reproducing the issue starts on src/application/vk-interface/Device.cpp, line 191, just after logical device is initialized and device function pointers were recieved.
 
As far as I remember I managed to reproduce the issue on corporate PC when I submittied issue here. I'll get to it on Monday and will try again.

Mabe it is something wrong just with my laptop configuration, or I'm being stupid.
Anyway I'll check the app on other PCs on Monday and report the results.

**Comment by karl-lunarg** [comment] 2018-10-03 18:56
@danylorudenko You might want to take a look at the implementation of your `VK_ASSERT` macro.  The `result` argument appears twice in the macro body, which would cause each statement wrapped by this macro to be executed twice.

**Comment by danylorudenko** [comment] 2018-10-14 16:45
@karl-lunarg Oh, those kinds of bugs make me feel very stupid..
Anyway, thank you and all team for taking your time to review the issue!
