### ISSUE TITLE
VUID-vkDestroySemaphore-semaphore-05149 reports semaphore in use with itself

### ISSUE THREAD

**Issue by HildarTheDorf** [KhronosGroup/Vulkan-ValidationLayers#8848] opened 2024-11-12 11:51 UTC
**Environment:**
 - OS: Ubuntu 24.10
 - GPU and driver version: AMD 
 - SDK or header version if building from repo: 1.3.296 (LunarG Ubuntu 24.04 packages)
 - Options enabled (synchronization, best practices, etc.): Validation -> Standard Preset

**Describe the Issue**

Semaphores in VkPresentInfoKHR::pWaitSemaphores are now being reported as 'in use' unless a vkQueueWaitIdle is emitted or VK_EXT_swapchain_maintenance1 fences are used (and waited on). However the message states that the semaphore is in use *by the semaphore itself* which is tautological and unhelpful.

**Expected behavior**

The error should be better worded, perhaps reporting it is in use by the VkQueue or VkSwapchainKHR.
Also unsure if this message should be emitted at all if VK_EXT_swapchain_maintenance1 isn't enabled, as the synchronization around vkQueuePresent is not well defined.

**Valid Usage ID**
VUID-vkDestroySemaphore-semaphore-05149

**Additional context**

VUID-vkDestroySemaphore-semaphore-05149(ERROR / SPEC): msgNum: -1813885519 - Validation Error: [ VUID-vkDestroySemaphore-semaphore-05149 ] | MessageID = 0x93e24db1 | vkDestroySemaphore(): semaphore can't be called on VkSemaphore 0xc4f3070000000021[] that is currently in use by VkSemaphore 0xc4f3070000000021[].
The Vulkan spec states: All submitted batches that refer to semaphore must have completed execution (https://vulkan.lunarg.com/doc/view/1.3.296.0/linux/1.3-extensions/vkspec.html#VUID-vkDestroySemaphore-semaphore-05149)

Note: I'm happy to fix this myself if the intended behavior is clarified by the maintainers.

**Comment by artem-lunarg** [comment] 2024-11-12 12:10
@HildarTheDorf thanks for the report. It’s a duplicate of https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8745

We will try to fix for the next SDK.

**Closed by artem-lunarg** 2024-11-12 12:10 UTC
