### ISSUE TITLE
Build failure: kInstVertOutVertexIndex

### ISSUE THREAD

**Issue by jengelh** [KhronosGroup/Vulkan-ValidationLayers#722] opened 2019-02-20 18:47 UTC
Strange that the CI build status (https://github.com/KhronosGroup/Vulkan-ValidationLayers ) says green for Linux when it's not:

```
commit fa7f02c4407709200e5c175098781720f8f549dc

[   10s] cd /home/abuild/rpmbuild/BUILD/Vulkan-ValidationLayers-1.1.100/build/layers && /usr/bin/cc -DAPI_NAME=\"Vulkan\" -DVK_USE_PLATFORM_WAYLAND_KHR -DVK_USE_PLATFORM_WAYLAND_KHX -DVK_USE_PLATFORM_XCB_KHR -DVK_USE_PLATFORM_XCB_KHX -DVK_USE_PLATFORM_XLIB_KHR -DVK_USE_PLATFORM_XLIB_KHX -DVK_USE_PLATFORM_XLIB_XRANDR_EXT -DVkLayer_core_validation_EXPORTS -I/usr/include/wayland -I/home/abuild/rpmbuild/BUILD/Vulkan-ValidationLayers-1.1.100/layers -I/usr/bin/include -I/home/abuild/rpmbuild/BUILD/Vulkan-ValidationLayers-1.1.100/build -I/home/abuild/rpmbuild/BUILD/Vulkan-ValidationLayers-1.1.100/build/layers  -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -DNDEBUG -Wpointer-arith -Wno-unused-function -Wno-sign-compare -O2 -g -DNDEBUG -fPIC   -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -fno-strict-aliasing -fno-builtin-memcmp -fvisibility=hidden -Wimplicit-fallthrough=0 -std=gnu99 -o CMakeFiles/VkLayer_core_validation.dir/xxhash.c.o   -c /home/abuild/rpmbuild/BUILD/Vulkan-ValidationLayers-1.1.100/layers/xxhash.c
[   12s] /home/abuild/rpmbuild/BUILD/Vulkan-ValidationLayers-1.1.100/layers/gpu_validation.cpp: In function 'void GenerateStageMessage(const uint32_t*, std::__cxx11::string&)':
[   12s] /home/abuild/rpmbuild/BUILD/Vulkan-ValidationLayers-1.1.100/layers/gpu_validation.cpp:620:71: error: 'kInstVertOutVertexIndex' was not declared in this scope
[   12s]              strm << "Stage = Vertex. Vertex Index = " << debug_record[kInstVertOutVertexIndex]
[   12s]                                                                        ^~~~~~~~~~~~~~~~~~~~~~~
[   12s] /home/abuild/rpmbuild/BUILD/Vulkan-ValidationLayers-1.1.100/layers/gpu_validation.cpp:621:58: error: 'kInstVertOutInstanceIndex' was not declared in this scope
[   12s]                   << " Instance Index = " << debug_record[kInstVertOutInstanceIndex] << ". ";
[   12s]                                                           ^~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by Tony-LunarG** [comment] 2019-02-20 18:54
I believe you need a newer glslang and corresponding spriv-tools build.  The current versions are listed in scripts/known_good.json, or running scripts/update_deps.py with desired parameters should fetch the right version of everything you need.

**Comment by jengelh** [comment] 2019-02-20 20:03
Yeah looks like I need spirv-tools 8d2d66f3. Though, spirv-tools is not listed in scripts/known_good.json (or update_deps.py).

**Comment by Tony-LunarG** [comment] 2019-02-20 20:51
Yes, validation layers count on glslang to build spirv-tools as a dependency external to glslang.

**Comment by tjaalton** [comment] 2019-03-08 09:16
please make sure to release all dependencies before cutting a new vulkan release, this is frustrating for distributors to publish new loader etc and then get stuck updating -validationlayers because it needs git versions of its dependencies

**Comment by mark-lunarg** [comment] 2019-03-08 16:16
@Tony-LunarG, does anything to be done for VVL?

**Comment by mark-lunarg** [comment] 2019-03-08 17:32
I talked to @karl-lunarg and he educated me on the underlying issues here.  @tjaalton, this particular instance can be attributed to a mistake which broke backwards-compatibility, and which we are attempting to avoid in the future.  However, we do feel that we can improve the coordination between the this project and the repository owners of glslang and spirv-tools -- perhaps using release tags for our dependencies instead of commit ids.  I'll leave this open until a comprehensive approach is agreed upon.

**Comment by jeremy-lunarg** [comment] 2019-03-11 21:29
@tjaalton Unfortunately, we have limited control over _github_ releases in some of the dependencies: spirv-header, spirv-tools, glslang, shaderc. However, we can provide releases for vulkan-loader, vulkan-validationlayers, vulkan-tools (khronos), vulkantools (lunarg), and vulkansamples.

@jengelh I'm going to close this issue because I believe @Tony-LunarG addressed it.

**Closed by jeremy-lunarg** 2019-03-11 21:29 UTC
Labels: Help Wanted

**Comment by akien-mga** [comment] 2019-03-27 14:21
I ran into the same issue trying to update the Vulkan SDK for the Mageia Linux distribution. I can only add my voice to @tjaalton to insist that known good versions should be tagged releases, not unreleased git commits.

**Comment by jengelh** [comment] 2019-03-27 15:01
>Yes, validation layers count on glslang to build spirv-tools as a dependency external to glslang.

I have a problem with this statement. spirv-tools is not a mandatory dependency to glslang. Just now I found that there is indeed a `-DENABLE_OPT=0` on the compiler command lines of glslang. cmake did that on its own and never aborted, so I suppose it is a supported configuration.

So then, the compiled glslang component does not depend on, nor pulls in, spirv-tools in my environment. This means that ValidationLayers ought to have an explicit dependency on spirv-tools. It should do that anyway, because implicit dependencies are kinda bad, especially when they evaluate to optional as they did.

**Comment by karl-lunarg** [comment] 2019-03-27 15:52
@akien-mga :  The issue of tagging glslang and spirv-tools should probably be taken up with the owners of those repos.  We currently "negotiate" with those owners to have them supply us with known-good commit ids that we then use for the SDKs.  These commit ids are clearly documented in the SDK release notes and in the repo via a "known-good" file.  While we'd prefer, as you do, that they tag them with "sdk" tags, that has not made a lot of sense to them in the past since vulkan and the vulkan SDK are not the only consumers of these two repos.  But perhaps they can be convinced.

@jengelh : That statement was intended to indicate that a specific glslang revision (commit) has a verified spirv-tools revision that is known to be compatible with that revision of glslang.  (The build process runs a script provided in the glslang repo that pulls in the required spriv-tools)  The validation layers in this repo link a library from spriv-tools.  But this repo also contains tests that use glslang components.  We feel that it is essential that the spriv-tools libs that are used to build glslang must be the same revision as the spirv-tools lib that is used for the validation layers.  While we *could* specify the git commit ids for glslang and spirv-tools independently (adding the explicit commit for spirv-tools that you are asking for), it seems safer to just specify the glslang revision and use the script in glslang to fetch the version of spirv-tools that it needs.  This completely removes any chance of getting two different spriv-tools in the build artifacts of this repo.

While we could entertain adding an explicit spirv-tools revision dependency, it seems redundant, since the required spirv-tools revision is communicated by glslang. 

This discussion has gotten off-topic from the original issue and this issue has been closed.  If you want to take up either of these topics again, I'd suggest opening new issues in the appropriate repos.
