### ISSUE TITLE
Unexpected VK_ERROR_VALIDATION from vkAcquireNextImageKHR

### ISSUE THREAD

**Issue by Destranix** [KhronosGroup/Vulkan-ValidationLayers#1363] opened 2019-11-07 06:20 UTC
See
https://github.com/KhronosGroup/Vulkan-Docs/issues/1040
for details.

Example:
Thread1:
```
private void drawFrame() {
		int[] imageIndex = new int[1];
		synchronized(waitAcquiredSwapChainImagesMonitorObject) {
			while(currentAcquiredSwapChainImagesCount > maxAcquiredSwapChainImagesCount) {
				try {
					waitAcquiredSwapChainImagesMonitorObject.wait();
				} catch (InterruptedException e) {
					e.printStackTrace();
					System.exit(-1);
				}
			}
		}

//...

		int err = VK_NOT_READY;
		synchronized(swapChain){
			while(err == VK_NOT_READY) {
				err = vkAcquireNextImageKHR(device, swapChain.get(0), 100L, nextSemaphore.longValue(), VK_NULL_HANDLE, imageIndex);
			}
		}
		if(err == VK_ERROR_OUT_OF_DATE_KHR) {
			recreateSwapChain();
			return;
		}else if(err != VK_SUCCESS && err != VK_SUBOPTIMAL_KHR) {
			throw new RuntimeException("Failed to acquire swap chain image: " + err);
		}

//...

//!!!!!	FIXME: With the synchronizeblock no error occures		
		//synchronized(waitAcquiredSwapChainImagesMonitorObject) {
			currentAcquiredSwapChainImagesCount++;
		//}
				
//!!!!!

//...

}
```
Thread2:
```
private void drawFrame() {

//...
		
		VkPresentInfoKHR presentInfo = VkPresentInfoKHR.calloc();
		presentInfo.sType(VK_STRUCTURE_TYPE_PRESENT_INFO_KHR);
		presentInfo.pWaitSemaphores(signalSemaphores);//wait with presentation till Image is rendered
		presentInfo.swapchainCount(1);
		presentInfo.pSwapchains(parentProcess.swapChain);
		IntBuffer imageIndexBuffer = (IntBuffer) memAllocInt(1).put(imageIndex).flip();
		presentInfo.pImageIndices(imageIndexBuffer);
		presentInfo.pResults(null);
		
		parentProcess.presentThread.registerNewJob(presentInfo, imageAvailableSemaphore, this);
		
//...

}
```
Thread3:
```
public class PresentThread extends Thread{
		
//...
		
	@Override
	public void run() {
		while(running) {

//...

			job = jobQueue.take();

//...

			synchronized(presentationQueue) {
				synchronized(swapChain) {
						err = vkQueuePresentKHR(presentationQueue, job.presentInfo);
				}
			}
			if(err == VK_ERROR_OUT_OF_DATE_KHR || err == VK_SUBOPTIMAL_KHR || framebufferResized) {
				framebufferResized = false;
				setSwapChainMustBeRecreated();
			}else if(err != VK_SUCCESS) {
				throw new RuntimeException("Failed to present swap chain image: " + err);
			}
			synchronized(job.owner) {
			job.owner.imagePresented = true;
			}
			synchronized(waitAcquiredSwapChainImagesMonitorObject){
				imageAvailableSemaphoresList.add(job.imageAvailableSemaphore);
				currentAcquiredSwapChainImagesCount--;
				waitAcquiredSwapChainImagesMonitorObject.notifyAll();
			}
			
//...

		}
	}
		
	public void registerNewJob(VkPresentInfoKHR presentInfo, Long imageAvailableSemaphore, SceneRendererPerFrameThreadObject owner) {
		PresentationJob job = new PresentationJob(presentInfo, imageAvailableSemaphore, owner);
		try {
			jobQueue.put(job);
		} catch (InterruptedException e) {
			e.printStackTrace();
			System.exit(-1);
		}		
	}
		
	private class PresentationJob{
		public final VkPresentInfoKHR presentInfo;
		public final Long imageAvailableSemaphore;
		public final SceneRendererPerFrameThreadObject owner;
	
		public PresentationJob(VkPresentInfoKHR presentInfo, Long imageAvailableSemaphore, SceneRendererPerFrameThreadObject owner) {
			this.presentInfo = presentInfo;
			this.imageAvailableSemaphore = imageAvailableSemaphore;
			this.owner = owner;
		}
	}
}
```

For detailed version see: https://github.com/Destranix/Vulkan_Swapchain_Issue

**Comment by mark-lunarg** [comment] 2019-11-11 18:05
@Destranix, we examined the layer source and the source for the sample program (thanks!) and this behavior is most unexpected -- that return code _should_ never occur unless you return 'true' from your debug messenger callback (which you do not).  As @krOoze suggested, the most helpful bit of information would be for you to get us an API dump of your test app running up to the point where the failure occurred -- would that be possible?  Thanks!

**Comment by krOoze** [comment] 2019-11-11 18:11
@mark-lunarg The `VK_ERROR_VALIDATION` is probably from the driver, which is allowed as part of undefined behavior (i.e. result of invalid usage). Why I suggested to migrate here is that by my understanding the invalid usage itself was not caught by layers.

**Comment by mark-lunarg** [comment] 2019-11-11 18:27
@krOoze, thanks! I thought that's what you'd meant, but went back to the spec and had ruled that out -- I'm surprised that a driver would return `VK_ERROR_VALIDATION_FAILED` as the spec says `The primary expected use of VK_ERROR_VALIDATION_FAILED_EXT is for validation layer testing. It is not expected that an application would see this error code during normal use of the validation layers.`, but now that you mention it it seems we might've seen this behavior before. Either way, the API dump will help a lot with figuring out what the driver's not happy with.

**Comment by krOoze** [comment] 2019-11-11 18:49
@mark-lunarg Well, problem with undefined behavior is that it is undefined. That means driver can do anything it wishes, including raiding your fridge and eating all your icecream. Returning a `VK_ERROR_VALIDATION_FAILED` is actually the most nice and obvious thing the driver could do.

**Comment by mark-lunarg** [comment] 2019-11-11 19:15
@krOoze, thanks again.  I guess that besides all of my ice cream, I've also lost my mind -- I think we have enough to go on after all.  Thanks for the clarification, guys.

**Comment by krOoze** [comment] 2019-11-11 19:21
I just tried `vk_validation_stats.py` and it says not implemented for `VUID-vkAcquireNextImageKHR-swapchain-01802`, so that checks out...

**Comment by krOoze** [comment] 2019-11-11 19:25
@mark-lunarg While I am here, you can asign me. Seems straightforward enough to implement...

**Comment by mark-lunarg** [comment] 2019-11-11 19:26
Love to!  You have my unending gratitude.

**Comment by Destranix** [comment] 2019-11-12 09:02
[api_dump.txt](https://github.com/KhronosGroup/Vulkan-ValidationLayers/files/3835199/api_dump.txt)

I had to force the crash manually by compleatly removing the increment of the counter. It seems like fileoperations when writing the api_dump prevent the race condition to occure.

**Comment by krOoze** [comment] 2019-11-12 13:23
In the log you have a validation error:

> vkAcquireNextImageKHR: Application has already acquired the maximum number of images (0x2)
> vkAcquireNextImageKHR: An attempt was made to acquire an image when the maximum number of images are already acquired.

Apparently I just need to clean it up and deduplicate it.

Or that error does not show in your original code?

**Comment by krOoze** [comment] 2019-11-12 13:27
PS: Yea the `api_dump` unfortunately serializes commands so it can show the returns from the commands as well...

On the other hand, there should be no difference, as `swapchain` parameter is marked externally synchronized for `vkAcquireNextImageKHR` and you should be making sure it does not run in parallel with something else.

**Comment by Destranix** [comment] 2019-11-12 17:19
> In the log you have a validation error:
> 
>     vkAcquireNextImageKHR: Application has already acquired the maximum number of images (0x2)
>     vkAcquireNextImageKHR: An attempt was made to acquire an image when the maximum number of images are already acquired.
> 

This also occured rarly in my orginal application.(Otherwise I would possibly noticed earlier, that I've made an synchronisation error. Also I thought, VK_ERROR_VALIDATION means, that something went wrong in the underlying API)

**Comment by krOoze** [comment] 2019-11-12 17:38
Well threaded bug is tricky to repro.

AIS, I think you either hit the image limit, or called two `vkAcquireNextImageKHR` in parallel which is not allowed. Though threading layer should complain too.

I am gonna clean the image limit error a bit and make a (single thread) unit test, but not sure what else to do here.

**Comment by Destranix** [comment] 2019-11-13 06:35
It's definitly the imagelimit due the issue is caused by the not synchronized counter for the currently used swapchain images.

Also I'm using vkAcquireNextImageKHR only in one thread.

I've just noticed, that I've called vkAcquireNextImageKHR using a timeout.
As far I understand the specification this should be allowed, as long the timeout is not UINT64_MAX.
But it's
`vkAcquireNextImageKHR(device, swapChain.get(0), 100L, nextSemaphore.longValue(), VK_NULL_HANDLE, imageIndex);`
100 != UINT65_MAX (this would be -1 in java, irc).

> If the number of currently acquired images is greater than this, vkAcquireNextImageKHR should not be called; if it is, timeout must not be UINT64_MAX.

Or is this still undefined? Does "should not" mean "in some cases the behaviour is not undefined, otherwise it is"?

**Comment by krOoze** [comment] 2019-11-13 14:33
@Destranix Oh, I see. I can reproduce that. Seems like a NV driver bug.

Meanwhile I fixed the validation check, which did not account for the timeout either: #1373

**Comment by mark-lunarg** [comment] 2019-11-20 17:37
@jeffbolznv, can you take a quick look at this analysis?

**Comment by pdaniell-nv** [comment] 2020-01-14 23:38
Yes, this does appear to be an NVIDIA driver bug. We're working on a fix. Thanks @krOoze for contributing a CTS test case.

**Comment by krOoze** [comment] 2020-04-14 22:04
The CTS was merged, and assumably the drivers pass now. Anything else to be done here?

**Comment by mark-lunarg** [comment] 2020-04-14 22:07
Thanks again @krOoze!

**Closed by mark-lunarg** 2020-04-14 22:07 UTC
Labels: Incomplete

**Comment by allanmac** [comment] 2020-04-21 18:24
Has this fix made its way into a driver?  If so, which version?

**Comment by krOoze** [comment] 2020-04-22 13:01
@allanmac My bad, test went into 1.2.2.0 CTS. NV still seems to be on 1.1.6.0. Testing rn on 445.87 still seems to fail. cc @pdaniell-nv

**Comment by pdaniell-nv** [comment] 2020-04-22 18:59
It should be fixed in our public beta drivers that can be found here: https://developer.nvidia.com/vulkan-driver
