### ISSUE TITLE
Invalid layer manifest file version warnings after upgrading to SDK 1.2.176

### ISSUE THREAD

**Issue by filnet** [KhronosGroup/Vulkan-ValidationLayers#2780] opened 2021-05-05 19:13 UTC
**Describe the Issue**

I am seeing the following warnings after upgrading to Vulkan SDK 1.2.176 (Windows):

```
[Warning][General]"loaderAddLayerProperties: C:\\VulkanSDK\\1.2.176.0\\Bin\\VkLayer_api_dump.json invalid layer manifest file version 1.2.0.  May cause errors."
[Warning][General]"loaderAddLayerProperties: C:\\VulkanSDK\\1.2.176.0\\Bin\\VkLayer_device_simulation.json invalid layer manifest file version 1.2.0.  May cause errors."
[Warning][General]"loaderAddLayerProperties: C:\\VulkanSDK\\1.2.176.0\\Bin\\VkLayer_gfxreconstruct.json invalid layer manifest file version 1.2.0.  May cause errors."
[Warning][General]"loaderAddLayerProperties: C:\\VulkanSDK\\1.2.176.0\\Bin\\VkLayer_khronos_synchronization2.json invalid layer manifest file version 1.2.0.  May cause errors."
[Warning][General]"loaderAddLayerProperties: C:\\VulkanSDK\\1.2.176.0\\Bin\\VkLayer_khronos_validation.json invalid layer manifest file version 1.2.0.  May cause errors."
[Warning][General]"loaderAddLayerProperties: C:\\VulkanSDK\\1.2.176.0\\Bin\\VkLayer_screenshot.json invalid layer manifest file version 1.2.0.  May cause errors."
```

**Environment:**
 - OS: Windows
 - GPU: RTX
 - SDK or header version if building from repo: 1.2.176
 - Options enabled : synchronization, best practices

**Additional context**

**Comment by ncesario-lunarg** [comment] 2021-05-05 21:02
Based on @charles-lunarg comments [here](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2705#pullrequestreview-636850981) and [here](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2705#issuecomment-820546077), it sounds like a loader update should make these go away.

**Comment by charles-lunarg** [comment] 2021-05-05 21:05
This is a harmless error, only caused by bumping the layer manifest version. Updating the loader to version 1.2.176 or newer will stop these warnings from being generated.
 
It was documented in the release notes. 
https://vulkan.lunarg.com/doc/sdk/1.2.176.0/windows/release_notes.html

**Comment by ncesario-lunarg** [comment] 2021-05-05 22:06
Going to close this as it sounds like this is expected. @filnet please re-open if you think there is something that needs to be changed on the validation layer side.

**Closed by ncesario-lunarg** 2021-05-05 22:06 UTC
