### ISSUE TITLE
How to load custom validation layers build

### ISSUE THREAD

**Issue by fctorial** [KhronosGroup/Vulkan-ValidationLayers#2916] opened 2021-06-26 21:28 UTC
**Describe the Issue**
I would like to know how to load a custom build of this repository on a linux system. I've compiled the 1.2.182 release successfully. I've tried loading it by adding the resulting `so` file to `LD_PRELOAD` but the program fails with this error message:

```
/nix/store/9ywr69qi622lrmx5nn88gk8jpmihy0dz-bash-4.4-p23/bin/bash: symbol lookup error: /home/fctorial/src/pgs/vkonscreen/my.tmp.dir/Vulkan-ValidationLayers/build/layers/libVkLayer_khronos_validation.so: undefined symbol: _ZN8spvtools25CreateInstDebugPrintfPassEjj
```

**Comment by ncesario-lunarg** [comment] 2021-06-28 15:14
Thanks for the issue @fctorial, unfortunately I haven't encountered that particular error, but if you're doing custom builds of this (VVL) repo, then usually setting the following environment variables is all that's necessary:
- `VK_LAYER_PATH` = the build output directory
- `VK_INSTANCE_LAYERS` = whatever layers you're interested
- If you have the SDK installed, make sure you `unset VULKAN_SDK`. I don't _think_ this has an effect at runtime, but if you're trying to use your own build of VVL alongside an installation of the SDK, having `VULKAN_SDK` defined can cause issues.

The vulkan loader is a complex beast from what little I understand of it, and  setting LD_PRELOAD _might_ be messing with something.

**Comment by fctorial** [comment] 2021-06-28 23:31
@ncesario-lunarg I tried this and this resulted in one error from the validation layer system followed by a segmentation fault:

```
$ VK_LAYER_PATH=/home/fctorial/src/pgs/vkonscreen/my.tmp.dir/Vulkan-ValidationLayers/build/layers cargo run --bin main
    Finished dev [optimized + debuginfo] target(s) in 0.02s
     Running `target/debug/main`
ERROR:GENERAL:"Loader Message"
/home/fctorial/src/pgs/vkonscreen/my.tmp.dir/Vulkan-ValidationLayers/build/layers/./libVkLayer_khronos_validation.so: undefined symbol: _ZN8spvtools25CreateInstDebugPrintfPassEjj
[1]    13951 segmentation fault (core dumped)  VK_LAYER_PATH= cargo run --bin main
```

The segmentation fault happens when I do an operation that would usually generate a validation message, like freeing a resource before the device.

**Comment by karl-lunarg** [comment] 2021-06-29 14:05
It may be productive to go after the cause of the undefined symbol.  The validation layer uses a SPIRV-Tools library which is built as one of the dependencies of the validation layer.  It is built as a static library and linked directly into the layer shared library (so file).

Your error message suggests that the validation layer is expecting to find a symbol in the SPIRV-Tools library that isn't there.  The most likely cause of this is a mismatch between the validation source version and the SPIRV-Tools library source version.  The coordination of these versions is handled in part by a file `scripts/known_good.json` and should be documented in `BUILD.md`.  In short, the `update_deps.py` script is supposed to gather and build the required dependencies for the validation layer.  It looks like this coordination didn't happen or something else went wrong with getting the correct version of SPIRV-Tools.

Note that the SPIRV-Tools dependency is transitive via the glslang dependency.  That is, we get a specific version of glslang which in turn gets its specific version of SPIRV-Tools.

If you built the dependencies by hand, then it is possible you didn't get the correct versions.

Also, note that in the `sdk-1.2.182` branch, the last commit there updated the `scripts/known_good.json` file in order to update SPIRV-Tools.  Is is possible that you don't have that commit?

**Comment by fctorial** [comment] 2021-06-29 19:01
I cloned the repository again, checked out latest 1.2.182, ran the four commands in build.md, but I'm still getting the same error message.

**Comment by ncesario-lunarg** [comment] 2021-06-29 20:41
@fctorial which VVL commit are you checking out? There is the `v1.2.182` _tag_, and the `sdk-1.2.182` _branch_. If your goal is to effectively "build the SDK VVL from source," then I believe the _branch_ `sdk-1.2.182` is what you want to be using. Though, I just tried building `v1.2.182` and that built and ran the tests fine for me as well.

A couple sanity checks that might be worth doing:
```bash
cd external/glslang && git rev-parse HEAD && cd -
```
The output of this command should match the `commit` entry for glslang in [known_good.json](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/scripts/known_good.json#L9).

```bash
rm build/layers/libVkLayer_khronos_validation.so 
ninja -C build --verbose # or VERBOSE=1 make for gmake (I think)

# Should see something like
/usr/bin/c++ -fPIC -Wpointer-arith -Wno-unused-function -Wno-sign-compare -g  -Wl,--version-script=/home/ncesario/lunarg/Vulkan-ValidationLayers/layers/libVkLayer_khronos_validation.map,-Bsymbolic,--exclude-libs,ALL -shared -Wl,-soname,libVkLayer_khronos_validation.so -o layers/libVkLayer_khronos_validation.so layers/CMakeFiles/VkLayer_khronos_validation.dir/generated/chassis.cpp.o layers/CMakeFiles/VkLayer_khronos_validation.dir/generated/layer_chassis_dispatch.cpp.o layers/CMakeFiles/VkLayer_khronos_validation.dir/generated/vk_safe_struct.cpp.o layers/CMakeFiles/VkLayer_khronos_validation.dir/layer_options.cpp.o layers/CMakeFiles/VkLayer_khronos_validation.dir/state_tracker.cpp.o layers/CMakeFiles/VkLayer_khronos_validation.dir/image_layout_map.cpp.o layers/CMakeFiles/VkLayer_khronos_validation.dir/subresource_adapter.cpp.o layers/CMakeFiles/VkLayer_khronos_validation.dir/sync_utils.cpp.o layers/CMakeFiles/VkLayer_khronos_validation.dir/core_validation.cpp.o layers/CMakeFiles/VkLayer_khronos_validation.dir/core_error_location.cpp.o layers/CMakeFiles/VkLayer_khronos_validation.dir/device_memory_state.cpp.o layers/CMakeFiles/VkLayer_khronos_validation.dir/cmd_buffer_state.cpp.o layers/CMakeFiles/VkLayer_khronos_validation.dir/image_state.cpp.o layers/CMakeFiles/VkLayer_khronos_validation.dir/pipeline_state.cpp.o layers/CMakeFiles/VkLayer_khronos_validation.dir/render_pass_state.cpp.o layers/CMakeFiles/VkLayer_khronos_validation.dir/drawdispatch.cpp.o layers/CMakeFiles/VkLayer_khronos_validation.dir/convert_to_renderpass2.cpp.o layers/CMakeFiles/VkLayer_khronos_validation.dir/descriptor_sets.cpp.o layers/CMakeFiles/VkLayer_khronos_validation.dir/buffer_validation.cpp.o layers/CMakeFiles/VkLayer_khronos_validation.dir/shader_module.cpp.o layers/CMakeFiles/VkLayer_khronos_validation.dir/shader_validation.cpp.o layers/CMakeFiles/VkLayer_khronos_validation.dir/sync_vuid_maps.cpp.o layers/CMakeFiles/VkLayer_khronos_validation.dir/generated/spirv_validation_helper.cpp.o layers/CMakeFiles/VkLayer_khronos_validation.dir/generated/command_validation.cpp.o layers/CMakeFiles/VkLayer_khronos_validation.dir/generated/synchronization_validation_types.cpp.o layers/CMakeFiles/VkLayer_khronos_validation.dir/gpu_validation.cpp.o layers/CMakeFiles/VkLayer_khronos_validation.dir/generated/corechecks_optick_instrumentation.cpp.o layers/CMakeFiles/VkLayer_khronos_validation.dir/xxhash.c.o layers/CMakeFiles/VkLayer_khronos_validation.dir/generated/object_tracker.cpp.o layers/CMakeFiles/VkLayer_khronos_validation.dir/object_tracker_utils.cpp.o layers/CMakeFiles/VkLayer_khronos_validation.dir/generated/thread_safety.cpp.o layers/CMakeFiles/VkLayer_khronos_validation.dir/generated/parameter_validation.cpp.o layers/CMakeFiles/VkLayer_khronos_validation.dir/parameter_validation_utils.cpp.o layers/CMakeFiles/VkLayer_khronos_validation.dir/best_practices_utils.cpp.o layers/CMakeFiles/VkLayer_khronos_validation.dir/generated/best_practices.cpp.o layers/CMakeFiles/VkLayer_khronos_validation.dir/gpu_utils.cpp.o layers/CMakeFiles/VkLayer_khronos_validation.dir/debug_printf.cpp.o layers/CMakeFiles/VkLayer_khronos_validation.dir/synchronization_validation.cpp.o  libVkLayer_utils.a  ../external/glslang/build/install/lib/libSPIRV-Tools-opt.a  ../external/glslang/build/install/lib/libSPIRV-Tools.a
```
Are the SPIRV binaries coming from `../external/glslang/build/install/lib/`?

**Comment by fctorial** [comment] 2021-06-29 21:38
No, they were coming from my global install of glslang:

```
/nix/store/ryy81g8zv6c8fh0j10m6fdynrgrn239k-gcc-wrapper-9.3.0/bin/g++ -fPIC  -Wpointer-arith -Wno-unused-function -Wno-sign-compare -g -Wl,--version-script=/home/fctorial/src/pgs/vkonscreen/my.tmp.dir/Vulkan-ValidationLayers/layers/libVkLayer_khronos_validation.map,-Bsymbolic,--exclude-libs,ALL -shared -Wl,-soname,libVkLayer_khronos_validation.so -o libVkLayer_khronos_validation.so CMakeFiles/VkLayer_khronos_validation.dir/generated/chassis.cpp.o CMakeFiles/VkLayer_khronos_validation.dir/generated/layer_chassis_dispatch.cpp.o CMakeFiles/VkLayer_khronos_validation.dir/generated/vk_safe_struct.cpp.o CMakeFiles/VkLayer_khronos_validation.dir/layer_options.cpp.o CMakeFiles/VkLayer_khronos_validation.dir/state_tracker.cpp.o CMakeFiles/VkLayer_khronos_validation.dir/image_layout_map.cpp.o CMakeFiles/VkLayer_khronos_validation.dir/subresource_adapter.cpp.o CMakeFiles/VkLayer_khronos_validation.dir/sync_utils.cpp.o CMakeFiles/VkLayer_khronos_validation.dir/core_validation.cpp.o CMakeFiles/VkLayer_khronos_validation.dir/core_error_location.cpp.o CMakeFiles/VkLayer_khronos_validation.dir/device_memory_state.cpp.o CMakeFiles/VkLayer_khronos_validation.dir/cmd_buffer_state.cpp.o CMakeFiles/VkLayer_khronos_validation.dir/image_state.cpp.o CMakeFiles/VkLayer_khronos_validation.dir/pipeline_state.cpp.o CMakeFiles/VkLayer_khronos_validation.dir/render_pass_state.cpp.o CMakeFiles/VkLayer_khronos_validation.dir/drawdispatch.cpp.o CMakeFiles/VkLayer_khronos_validation.dir/convert_to_renderpass2.cpp.o CMakeFiles/VkLayer_khronos_validation.dir/descriptor_sets.cpp.o CMakeFiles/VkLayer_khronos_validation.dir/buffer_validation.cpp.o CMakeFiles/VkLayer_khronos_validation.dir/shader_module.cpp.o CMakeFiles/VkLayer_khronos_validation.dir/shader_validation.cpp.o CMakeFiles/VkLayer_khronos_validation.dir/sync_vuid_maps.cpp.o CMakeFiles/VkLayer_khronos_validation.dir/generated/spirv_validation_helper.cpp.o CMakeFiles/VkLayer_khronos_validation.dir/generated/command_validation.cpp.o CMakeFiles/VkLayer_khronos_validation.dir/generated/synchronization_validation_types.cpp.o CMakeFiles/VkLayer_khronos_validation.dir/gpu_validation.cpp.o CMakeFiles/VkLayer_khronos_validation.dir/generated/corechecks_optick_instrumentation.cpp.o CMakeFiles/VkLayer_khronos_validation.dir/xxhash.c.o CMakeFiles/VkLayer_khronos_validation.dir/generated/object_tracker.cpp.o CMakeFiles/VkLayer_khronos_validation.dir/object_tracker_utils.cpp.o CMakeFiles/VkLayer_khronos_validation.dir/generated/thread_safety.cpp.o CMakeFiles/VkLayer_khronos_validation.dir/generated/parameter_validation.cpp.o CMakeFiles/VkLayer_khronos_validation.dir/parameter_validation_utils.cpp.o CMakeFiles/VkLayer_khronos_validation.dir/best_practices_utils.cpp.o CMakeFiles/VkLayer_khronos_validation.dir/generated/best_practices.cpp.o CMakeFiles/VkLayer_khronos_validation.dir/gpu_utils.cpp.o CMakeFiles/VkLayer_khronos_validation.dir/debug_printf.cpp.o CMakeFiles/VkLayer_khronos_validation.dir/synchronization_validation.cpp.o  ../libVkLayer_utils.a /nix/store/x22jgfj2nh4a3xdaqbnp8wznghsi2klw-glslang-8.13.3559/lib/libSPIRV-Tools-opt.a /nix/store/x22jgfj2nh4a3xdaqbnp8wznghsi2klw-glslang-8.13.3559/lib/libSPIRV-Tools.a 
```
 
The build generates working output if I uninstall the package.

**Comment by ncesario-lunarg** [comment] 2021-06-29 21:59
Closing as it looks like this is resolved. Please re-open if that is not the case.

**Closed by ncesario-lunarg** 2021-06-29 21:59 UTC
