### ISSUE TITLE
Synchronization validation flags official Vulkan example as incorrect

### ISSUE THREAD

**Issue by john01dav** [KhronosGroup/Vulkan-ValidationLayers#6995] opened 2023-11-19 23:30 UTC
**Environment:**
 - OS: Fedora Linux 38 Workstation Edition
 - GPU and driver version: Nvidia GTX 1070 535.129.03
 - SDK or header version if building from repo: got from Fedora package manager, so N/A
 - Options enabled (synchronization, best practices, etc.): all in MCVE (gpu assisted, gpu assisted reserve binding slot, best practices, debug printf, and synchronization). The same misbehaviour is observed with just synchronization enabled, however. 

**Describe the Issue**
[MCVE](https://github.com/KhronosGroup/Vulkan-Docs/files/13404906/mcve.zip)

I implemented the [Swapchain Image Acquire and Present Combined Graphics/Present Queue synchronization strategy](https://github.com/KhronosGroup/Vulkan-Docs/wiki/Synchronization-Examples#combined-graphicspresent-queue) from the VulkanDocs repo into [the hello triangle example from vulkan-tutorial.com](https://github.com/Overv/VulkanTutorial/blob/main/code/15_hello_triangle.cpp). After encountering this in a real program (that is based on this tutorial), I used this as a base for my MCVE and implemented the synchronization example's strategy into the tutorial code since the existing strategy there is very similar.

**Expected behavior**

I expect that the example code is correct, so either that should be fixed or the layer should be fixed as to not give a false error. 

**Validation Errors**
```
validation layer: Validation Error: [ SYNC-HAZARD-WRITE-AFTER-WRITE ] Object 0: handle = 0xd000000000d, type = VK_OBJECT_TYPE_RENDER_PASS; | MessageID = 0x5c0ec5d6 | vkCmdBeginRenderPass: Hazard WRITE_AFTER_WRITE vs. layout transition in subpass 0 for attachment 0 aspect color during load with loadOp VK_ATTACHMENT_LOAD_OP_CLEAR.
validation layer: Validation Error: [ SYNC-HAZARD-WRITE-AFTER-WRITE ] Object 0: handle = 0xd000000000d, type = VK_OBJECT_TYPE_RENDER_PASS; | MessageID = 0x5c0ec5d6 | vkCmdEndRenderPass: Hazard WRITE_AFTER_WRITE vs. store/resolve operations in subpass 0 for attachment 0 final image layout transition (old_layout: VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL, new_layout: VK_IMAGE_LAYOUT_PRESENT_SRC_KHR).
```

**Additional context**
I suspect that the problem is in the example code since [when implementing that strategy in a real program I get flickering on Nvidia + Wayland](https://github.com/Overv/VulkanTutorial/assets/3982497/768db702-56b3-4075-a764-4904f62fb773). In case that is not correct (and to get more eyes on the problem since this seems widespread¹), I am also creating an issue report here.

See the MCVE above to reproduce the issue.

Issue on Vulkan-Docs repo: https://github.com/KhronosGroup/Vulkan-Docs/issues/2274

1: Anecdotally, I have experienced similar flickering in other renderers as I go about my normal computer usage. For example, I remember some wgpu-rs programs experiencing similar problems. I also can't find any answer to how to deal with this online, but I can find a lot of sources giving similar or identical incorrect information as in the official example that I noticed.

**Comment by krOoze** [comment] 2023-11-20 13:31
I don't immediately see anything wrong with the wiki.

Example does not seem to align with the reported error. The `dstStage` does not make sense though without `VK_KHR_synchronization2`, and appropriate fine-grained signal semaphore.

> SDK or header version if building from repo: got from Fedora package manager, so N/A

Layer versions can be obtained programmatically via `vkEnumerateInstanceLayerProperties`. No point working with old versions. Uptodate versions are always available at https://vulkan.lunarg.com/sdk/home

**Comment by artem-lunarg** [comment] 2023-11-20 20:23
@john01dav I built your example locally on windows (thanks a lot for providing it) and it works without errors for the latest validation layer (both synchronization validation and core validation). I also tried some older releases and it works fine too. 

Checking the source code I can't see obvious issues, it matches the pseudocode from the Synchronization Examples. Checking the Synchronization Example snippet you used, I think it's correct. 

My best guess that the problem is what we had on the Arch Linux some time ago: https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5994
We made a fix here https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/6049. It could be you are using older VVL package which does not have a fix. The recommendation is to update the VVL package to the latest one, Fedora provides a VVL package that corresponds to the latest sdk 1.3.268 (https://koji.fedoraproject.org/koji/packageinfo?packageID=27187)

Some information about original problem. It was about `-flto` compiler/link option (we don't use that option for official sdk builds, afaik). That option exposed some bugs related to variable initialization in syncval module. According to Fedora's build logs https://kojipkgs.fedoraproject.org//packages/vulkan-validation-layers/1.3.268.0/1.fc40/data/logs/x86_64/build.log they also use `-flto` for VVL package, so there is a chance you have an older package that still has the issue exposed by `-flto` flag.

**Comment by artem-lunarg** [comment] 2023-11-20 20:38
According to https://packages.fedoraproject.org/pkgs/vulkan-validation-layers/vulkan-validation-layers/ Fedora 38 by uses VVL 1.3.243, which does not have a fix. I suggest either to update the package or to build VVL from the latest source code manually. Closing this ticket as not a VVL bug. If I missed something please feel free to re-open.

**Closed by artem-lunarg** 2023-11-20 20:38 UTC
Labels: Synchronization
