### ISSUE TITLE
Remove all mentions of 'global descriptor indices' from error messages

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-ValidationLayers#84] opened 2018-05-14 01:50 UTC
**Issue by [chrisforbes](https://github.com/chrisforbes) (MIGRATED)**
_Wednesday May 02, 2018 at 23:51 GMT_
_Originally opened as https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/2631_

----

A single global space is a LVL-created fiction. All our error messages should be in terms of Vulkan spec concepts -- in this case, the 3-level set/binding/arrayelement space.

**Comment by karl-lunarg** [comment] 2018-05-14 01:50
<a href="https://github.com/tobine"><img src="https://avatars0.githubusercontent.com/u/7526739?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [tobine](https://github.com/tobine) (MIGRATED)**
_Thursday May 03, 2018 at 13:57 GMT_

----

I believe all of the offending messages are in [ValidateDrawState](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/layers/descriptor_sets.cpp#L629) function. Agree that this should just reference the array offset into that descriptor, if any.

**Comment by tobine** [comment] 2019-03-29 12:35
Dupe of #812

**Closed by tobine** 2019-03-29 12:35 UTC
