### ISSUE TITLE
Validation layer should check that the order of the layouts in VkPipelineLayoutCreateInfo match the order specified in the shaders.

### ISSUE THREAD

**Issue by ZeGentzy** [KhronosGroup/Vulkan-ValidationLayers#176] opened 2018-06-06 22:40 UTC
Section 14.5.3 is the Vulkan spec states the following:

> A variable decorated with a DescriptorSet decoration of s and a Binding decoration of b indicates
that this variable is associated with the VkDescriptorSetLayoutBinding that has a binding equal to b
in pSetLayouts[s] that was specified in VkPipelineLayoutCreateInfo.

This isn't validated by the validation layers.

**Comment by tobine** [comment] 2018-06-18 17:16
@ZeGentzy thanks for filing the issue. The spec text that you quote isn't a validation requirement, it's simply stating how Vulkan is implemented. Your issue title saying "checks that the order" makes me think you're referring to a mismatch between the type of descriptor that's bound in a shader vs. the corresponding descriptor type from the DescriptorSet Layout.
Note that validation does report such type mis-matches already.
Based on this I'm not sure what the issue is so closing. If you have an example of a case that you believe should be flagged by validation but is not, then please re-open with example.

**Closed by tobine** 2018-06-18 17:16 UTC
Labels: incomplete
