### ISSUE TITLE
Question (need help, custom layer)

### ISSUE THREAD

**Issue by Bxaa** [KhronosGroup/Vulkan-ValidationLayers#2988] opened 2021-07-18 04:34 UTC
TEST.BAT:
set VK_LAYER_PATH=X:\TEST
set VK_INSTANCE_LAYERS=VK_LAYER_reshade;VK_LAYER_KHRONOS_validation
pushd "%~dp0"
start "TEST" /D "X:\TEST" "X:\TEST\TEST.EXE"

reshade32.json (X:\TEST\reshade32.json)
{
"file_format_version" : "1.0.0",
    "layer" : {
        "name": "VK_LAYER_reshade",
        "type": "GLOBAL",
        "library_path": ".\\rs.dll",
        "api_version": "1.2.131",
        "implementation_version": "1",
        "description": "W1_RS",
        "disable_environment": {
        "DISABLE_VK_LAYER_reshade_1": "1"
        }
    }
}

So...it perfect work while it TEST.BAT launch not from admin, BUT not work, if it launch from admin? 

Why?

**Comment by ncesario-lunarg** [comment] 2021-07-19 16:39
I'm sorry to say I have no experience with the reshade layer, but it looks like you may be running into the same problem described in https://github.com/KhronosGroup/Vulkan-Loader/issues/266?

**Comment by charles-lunarg** [comment] 2021-07-19 20:45
This is intended behavior, environment variables such as VK_LAYER_PATH can be set without admin privileges and if you then run an app in admin mode, it would use those environment variables. A bad actor could set VK_LAYER_PATH to include a layer with malicious code, then if the loader didn't ignore the environment variable, the bad actor now has admin access to the whole machine.

**Comment by ncesario-lunarg** [comment] 2021-07-19 22:10
Thanks @charles-lunarg, I'm going to close this you've noted it as "intended behavior." @Bxaa, if you feel there is still a change required to VVL, please re-open.

**Closed by ncesario-lunarg** 2021-07-19 22:10 UTC

**Comment by Bxaa** [comment] 2021-07-20 08:07
> then if the loader didn't ignore the environment variable, the bad actor now has admin access to the whole machine.

@charles-lunarg, Thx, is a way to bypass this safety? (disable ignoring  the environment variable by loader from admin)

**Comment by ncesario-lunarg** [comment] 2021-07-20 16:01
> Also, if user is administrator and login with integrated admin account - why this check? (All programs already working with max privileges after launch)

I'm not familiar enough with Windows permissions, but I don't _think_ you can differentiate between "logged in as admin running everything as admin" and "logged in normally, but running an app with admin privileges." If there is indeed a way to differentiate between these two cases at runtime, I could see disabling the check for the former case making sense, but I don't know if this is possible.

**Comment by Bxaa** [comment] 2021-07-21 08:30
_As i know:
System.Security.Principal class
You can check - if app launched with admin (but user not admin) 
Also you can check - is user use integrated administrator account (but not group administrators) 

I'll try to make example of this C++ implementation. If you need...

**Comment by charles-lunarg** [comment] 2021-07-21 14:26
One thing to note, these environment variables are for debugging purposes and not intended for release. So they aren't really intended to operate in all circumstances, especially those that would undermine security.

Can I ask what is trying to be accomplished with the above script? Knowing the intent would help me judge what the use case is. What I can see is a script that when run, enables reshade and validation. To always run a layer, the intended mechanism is with entries in `HKEY_CURRENT_USER/SOFTWARE/Khronos/Vulkan/ImplicitLayers` or  `HKEY_LOCAL_MACHINE/SOFTWARE/Khronos/Vulkan/ImplicitLayers` (which does work in admin mode!).

**Comment by KarenGhavam-lunarG** [comment] 2021-07-21 14:30
@charles-lunarg @ncesario-lunarg   Shouldn't this issue be in the Vulkan-Loader repository?

**Comment by ncesario-lunarg** [comment] 2021-07-21 15:53
If it is still an open issue (i.e., if there is something we need to change), then yes, I think this belongs in Vulkan-Loader. I've closed the issue here, but it's up to @charles-lunarg whether or not this belongs as an open issue in Vulkan-Loader.

**Comment by Bxaa** [comment] 2021-07-21 21:20
@charles-lunarg  for debug with fast changing injected dll (requre admin by some reasons)
Reshade  - just simple example

As far as I remember this also does not work
(HKEY_CURRENT_USER/SOFTWARE or HKEY_CURRENT_USER)/Khronos/Vulkan/ImplicitLayers...
I'll check it again.
Anyway thx

**Comment by charles-lunarg** [comment] 2021-07-21 21:26
@Bxaa Yes, HKEY_CURRENT_USER should _not_ work in admin mode because it is user settable.

Now that I see this is for debug purposes, it is a good time to move the issue over to the https://github.com/KhronosGroup/Vulkan-Loader repo. It would be very helpful if you could create the issue with what you use case is (debugging application with fast changing layer), explaining how admin mode is needed, and then we can discuss possible solutions there.
