### ISSUE TITLE
syncval: False SYNC-HAZARD-READ_AFTER_WRITE CopyBufferDest->VertexBufferRead for non-existent vkCmdCopyBuffer.

### ISSUE THREAD

**Issue by Jonathan-Weinstein** [KhronosGroup/Vulkan-ValidationLayers#3676] opened 2022-01-13 00:07 UTC
I'm testing an application using `VK_VALIDATION_FEATURE_ENABLE_SYNCHRONIZATION_VALIDATION_EXT` that (incorrectly, I believe) generates the following:
"
API High Miscellaneous 1287084845 Validation Error: [ SYNC-HAZARD-READ_AFTER_WRITE ] Object 0: handle = Surface Buffer (sid 204), name = Surface Buffer (sid 204), type = VK_OBJECT_TYPE_BUFFER; | MessageID = 0x4cb75b2d | vkCmdDraw: Hazard READ_AFTER_WRITE for vertex VkBuffer Surface Buffer (sid 204) in VkCommandBuffer Command Buffer 475. Access info (usage: SYNC_VERTEX_ATTRIBUTE_INPUT_VERTEX_ATTRIBUTE_READ, prior_usage: SYNC_COPY_TRANSFER_WRITE, write_barriers: SYNC_VERTEX_SHADER_UNIFORM_READ|SYNC_TESSELLATION_CONTROL_SHADER_UNIFORM_READ|SYNC_TESSELLATION_EVALUATION_SHADER_UNIFORM_READ|SYNC_GEOMETRY_SHADER_UNIFORM_READ|SYNC_EARLY_FRAGMENT_TESTS_DEPTH_STENCIL_ATTACHMENT_READ|SYNC_EARLY_FRAGMENT_TESTS_DEPTH_STENCIL_ATTACHMENT_WRITE|SYNC_FRAGMENT_SHADER_UNIFORM_READ|SYNC_LATE_FRAGMENT_TESTS_DEPTH_STENCIL_ATTACHMENT_READ|SYNC_LATE_FRAGMENT_TESTS_DEPTH_STENCIL_ATTACHMENT_WRITE|SYNC_COLOR_ATTACHMENT_OUTPUT_COLOR_ATTACHMENT_READ|SYNC_COLOR_ATTACHMENT_OUTPUT_COLOR_ATTACHMENT_WRITE|SYNC_COMPUTE_SHADER_UNIFORM_READ, command: vkCmdCopyBuffer, seq_no: 2, reset_no: 2511).
"

Note that the application I'm testing does not use `VkDeviceMemory` aliasing, descriptor indexing, or multiple `VkQueues`.

"sid 204" is a debug label for a `VkBuffer`. In the renderdoc Resource Inspector for the capture,
during EIDs 55708-55827 sid 204 is used as Vertex Buffer. After a while, it's used again as a Vertex Buffer with the first EID being 125264, where the validation message occurs here. However, there is no other use of sid 204 shown in the Resource Inspector between EID 55827 and 125264, nor does renderdoc show a `vkCmdCopyBuffer` anywhere in the capture using sid 204. Since no validation message was generated throughout sid 204's usage as a Vertex Buffer earlier during 55708-55827, it should still be valid to access as a Vertex Buffer at the later EID 125264 since nothing wrote to it in between, according to renderdoc.

This occurs in a debug build of the validation layer using the recent commit f684dcc99 on January 11th, but also happens in earlier builds.

**Environment:**
 - OS: Linux
 - GPU: NV Quadro P1000
 - Driver: 460.91.03

Does this seem interesting and would you like me to provide a renderdoc capture or gfxr file someplace?

Thanks.

**Comment by ncesario-lunarg** [comment] 2022-01-14 17:58
FYI @jeremyg-lunarg @jzulauf-lunarg.

**Comment by ziga-lunarg** [comment] 2022-03-08 00:10
@Jonathan-Weinstein gfxr file would be helpful

**Comment by Jonathan-Weinstein** [comment] 2022-03-09 01:00
Sorry I filed this originally and I hope I'm not using too much of your time. The bug doesn't bother me and rarely comes up. I made an issue on the chance this might be a symptom of a more significant issue. Here's a link to a 62 MB (I'm afraid it doesn't repro with `gfxrecon.py replay` unless a large enough frame range is captured) gfxr file: https://drive.google.com/file/d/11Lz5jkjk9En5-HARCLaLsmnP8jEOx8E4/view?usp=sharing

The false-positive validation errors should all be in the second to last or last frame of `issue3676_frames_85_through_133.gfxr`, which according to VK_LAYER_LUNARG_api_dump is 52.

First, I'm running with vkconfig active that forces `Synchronization` validation on and `Handle Wrapping` off so the debug message output handles match the api-dump handles. Then I replay the capture like this on Linux:
`VK_APIDUMP_LOG_FILENAME=`pwd`/apidump.txt VK_INSTANCE_LAYERS=VK_LAYER_LUNARG_api_dump gfxrecon.py replay --validate ./issue3676_frames_85_through_133.gfxr`
Which emit this to stdout, though the interesting handle value of `0x5630cadeb8e0` probably change from run to run:
```
VK_APIDUMP_LOG_FILENAME=`pwd`/apidump.txt VK_INSTANCE_LAYERS=VK_LAYER_LUNARG_api_dump gfxrecon.py replay --validate ./issue3676_frames_85_through_133.gfxr
[gfxrecon] INFO - Loading state for captured frame 85
[gfxrecon] INFO - Loading state for captured frame 85
[gfxrecon] INFO - Replay adjusted the vkGetPhysicalDeviceQueueFamilyProperties array count: capture count = 1, replay count = 3
[gfxrecon] INFO - Finished loading state for captured frame 85
[gfxrecon] INFO - Finished loading state for captured frame 85
SYNC-HAZARD-READ_AFTER_WRITE(ERROR / SPEC): msgNum: 1287084845 - Validation Error: [ SYNC-HAZARD-READ_AFTER_WRITE ] Object 0: handle = 0x5630cadeb8e0, type = VK_OBJECT_TYPE_BUFFER; | MessageID = 0x4cb75b2d | vkCmdDraw: Hazard READ_AFTER_WRITE for vertex VkBuffer 0x5630cadeb8e0[] in VkCommandBuffer 0x5630cb850d00[]. Access info (usage: SYNC_VERTEX_ATTRIBUTE_INPUT_VERTEX_ATTRIBUTE_READ, prior_usage: SYNC_COPY_TRANSFER_WRITE, write_barriers: SYNC_VERTEX_SHADER_UNIFORM_READ|SYNC_TESSELLATION_CONTROL_SHADER_UNIFORM_READ|SYNC_TESSELLATION_EVALUATION_SHADER_UNIFORM_READ|SYNC_GEOMETRY_SHADER_UNIFORM_READ|SYNC_EARLY_FRAGMENT_TESTS_DEPTH_STENCIL_ATTACHMENT_READ|SYNC_EARLY_FRAGMENT_TESTS_DEPTH_STENCIL_ATTACHMENT_WRITE|SYNC_FRAGMENT_SHADER_UNIFORM_READ|SYNC_LATE_FRAGMENT_TESTS_DEPTH_STENCIL_ATTACHMENT_READ|SYNC_LATE_FRAGMENT_TESTS_DEPTH_STENCIL_ATTACHMENT_WRITE|SYNC_COLOR_ATTACHMENT_OUTPUT_COLOR_ATTACHMENT_READ|SYNC_COLOR_ATTACHMENT_OUTPUT_COLOR_ATTACHMENT_WRITE|SYNC_COMPUTE_SHADER_UNIFORM_READ, command: vkCmdCopyBuffer, seq_no: 2, reset_no: 2769).
    Objects: 1
        [0] 0x5630cadeb8e0, type: 9, name: NULL
SYNC-HAZARD-READ_AFTER_WRITE(ERROR / SPEC): msgNum: 1287084845 - Validation Error: [ SYNC-HAZARD-READ_AFTER_WRITE ] Object 0: handle = 0x5630cadeb8e0, type = VK_OBJECT_TYPE_BUFFER; | MessageID = 0x4cb75b2d | vkCmdDraw: Hazard READ_AFTER_WRITE for vertex VkBuffer 0x5630cadeb8e0[] in VkCommandBuffer 0x5630cb850d00[]. Access info (usage: SYNC_VERTEX_ATTRIBUTE_INPUT_VERTEX_ATTRIBUTE_READ, prior_usage: SYNC_COPY_TRANSFER_WRITE, write_barriers: SYNC_VERTEX_SHADER_UNIFORM_READ|SYNC_TESSELLATION_CONTROL_SHADER_UNIFORM_READ|SYNC_TESSELLATION_EVALUATION_SHADER_UNIFORM_READ|SYNC_GEOMETRY_SHADER_UNIFORM_READ|SYNC_EARLY_FRAGMENT_TESTS_DEPTH_STENCIL_ATTACHMENT_READ|SYNC_EARLY_FRAGMENT_TESTS_DEPTH_STENCIL_ATTACHMENT_WRITE|SYNC_FRAGMENT_SHADER_UNIFORM_READ|SYNC_LATE_FRAGMENT_TESTS_DEPTH_STENCIL_ATTACHMENT_READ|SYNC_LATE_FRAGMENT_TESTS_DEPTH_STENCIL_ATTACHMENT_WRITE|SYNC_COLOR_ATTACHMENT_OUTPUT_COLOR_ATTACHMENT_READ|SYNC_COLOR_ATTACHMENT_OUTPUT_COLOR_ATTACHMENT_WRITE|SYNC_COMPUTE_SHADER_UNIFORM_READ, command: vkCmdCopyBuffer, seq_no: 2, reset_no: 2769).
    Objects: 1
        [0] 0x5630cadeb8e0, type: 9, name: NULL
SYNC-HAZARD-READ_AFTER_WRITE(ERROR / SPEC): msgNum: 1287084845 - Validation Error: [ SYNC-HAZARD-READ_AFTER_WRITE ] Object 0: handle = 0x5630cadeb8e0, type = VK_OBJECT_TYPE_BUFFER; | MessageID = 0x4cb75b2d | vkCmdDraw: Hazard READ_AFTER_WRITE for vertex VkBuffer 0x5630cadeb8e0[] in VkCommandBuffer 0x5630cb850d00[]. Access info (usage: SYNC_VERTEX_ATTRIBUTE_INPUT_VERTEX_ATTRIBUTE_READ, prior_usage: SYNC_COPY_TRANSFER_WRITE, write_barriers: SYNC_VERTEX_SHADER_UNIFORM_READ|SYNC_TESSELLATION_CONTROL_SHADER_UNIFORM_READ|SYNC_TESSELLATION_EVALUATION_SHADER_UNIFORM_READ|SYNC_GEOMETRY_SHADER_UNIFORM_READ|SYNC_EARLY_FRAGMENT_TESTS_DEPTH_STENCIL_ATTACHMENT_READ|SYNC_EARLY_FRAGMENT_TESTS_DEPTH_STENCIL_ATTACHMENT_WRITE|SYNC_FRAGMENT_SHADER_UNIFORM_READ|SYNC_LATE_FRAGMENT_TESTS_DEPTH_STENCIL_ATTACHMENT_READ|SYNC_LATE_FRAGMENT_TESTS_DEPTH_STENCIL_ATTACHMENT_WRITE|SYNC_COLOR_ATTACHMENT_OUTPUT_COLOR_ATTACHMENT_READ|SYNC_COLOR_ATTACHMENT_OUTPUT_COLOR_ATTACHMENT_WRITE|SYNC_COMPUTE_SHADER_UNIFORM_READ, command: vkCmdCopyBuffer, seq_no: 2, reset_no: 2769).
    Objects: 1
        [0] 0x5630cadeb8e0, type: 9, name: NULL
SYNC-HAZARD-READ_AFTER_WRITE(ERROR / SPEC): msgNum: 1287084845 - Validation Error: [ SYNC-HAZARD-READ_AFTER_WRITE ] Object 0: handle = 0x5630cadeb8e0, type = VK_OBJECT_TYPE_BUFFER; | MessageID = 0x4cb75b2d | vkCmdDraw: Hazard READ_AFTER_WRITE for vertex VkBuffer 0x5630cadeb8e0[] in VkCommandBuffer 0x5630cb850d00[]. Access info (usage: SYNC_VERTEX_ATTRIBUTE_INPUT_VERTEX_ATTRIBUTE_READ, prior_usage: SYNC_COPY_TRANSFER_WRITE, write_barriers: SYNC_VERTEX_SHADER_UNIFORM_READ|SYNC_TESSELLATION_CONTROL_SHADER_UNIFORM_READ|SYNC_TESSELLATION_EVALUATION_SHADER_UNIFORM_READ|SYNC_GEOMETRY_SHADER_UNIFORM_READ|SYNC_EARLY_FRAGMENT_TESTS_DEPTH_STENCIL_ATTACHMENT_READ|SYNC_EARLY_FRAGMENT_TESTS_DEPTH_STENCIL_ATTACHMENT_WRITE|SYNC_FRAGMENT_SHADER_UNIFORM_READ|SYNC_LATE_FRAGMENT_TESTS_DEPTH_STENCIL_ATTACHMENT_READ|SYNC_LATE_FRAGMENT_TESTS_DEPTH_STENCIL_ATTACHMENT_WRITE|SYNC_COLOR_ATTACHMENT_OUTPUT_COLOR_ATTACHMENT_READ|SYNC_COLOR_ATTACHMENT_OUTPUT_COLOR_ATTACHMENT_WRITE|SYNC_COMPUTE_SHADER_UNIFORM_READ, command: vkCmdCopyBuffer, seq_no: 2, reset_no: 2769).
    Objects: 1
        [0] 0x5630cadeb8e0, type: 9, name: NULL
Load time:  0.857908 seconds
Total time: 4.302849 seconds
Replay FPS: 14.223755 fps, 3.444941 seconds, 49 frames, framerange 85-133
```

Based on inspecting apidump.txt for all 46 occurrences of VkBuffer `0x5630cadeb8e0`, the above validation errors seem to be a false-positives. The buffer is made with                         `VkBufferCreateFlags = 0` and `VkBufferUsageFlags = 131 (VK_BUFFER_USAGE_TRANSFER_SRC_BIT | VK_BUFFER_USAGE_TRANSFER_DST_BIT | VK_BUFFER_USAGE_VERTEX_BUFFER_BIT)`, so it cant alias anything and can only be written to by transfer commands. The buffer handle is only destroyed at the very end of the capture. The last command to write to the buffer is a `vkCmdCopyBuffer` on frame 12, the one with
`srcOffset:                      VkDeviceSize = 13687104`

Immediately after that there is a `vkCmdPipelineBarrier` with a `VkBufferMemoryBarrier` containing that VkBuffer handle:
```
    srcStageMask:                   VkPipelineStageFlags = 4096 (VK_PIPELINE_STAGE_TRANSFER_BIT)
    dstStageMask:                   VkPipelineStageFlags = 4 (VK_PIPELINE_STAGE_VERTEX_INPUT_BIT)
    bufferMemoryBarrierCount:       uint32_t = 1
    pBufferMemoryBarriers:          const VkBufferMemoryBarrier* = 0x5630ca109410
        pBufferMemoryBarriers[0]:       const VkBufferMemoryBarrier = 0x5630ca109410:
            srcAccessMask:                  VkAccessFlags = 4096 (VK_ACCESS_TRANSFER_WRITE_BIT)
            dstAccessMask:                  VkAccessFlags = 4 (VK_ACCESS_VERTEX_ATTRIBUTE_READ_BIT)
            buffer:                         VkBuffer = 0x5630cadeb8e0
            offset:                         VkDeviceSize = 0
            size:                           VkDeviceSize = 18446744073709551615
```
After this point, the only other command involving this buffer is just `vkCmdBindVertexBuffers` of which there are calls in some of the middle frames, like 12, 15, 18, 24, 28, 32, 36. None of those cause a validation error, and I believe those are in front of draw calls that actually fetch from the buffer.

Based on the above, any later `vkCmdBindVertexBuffers` causing a validation error seems like a false-positive.

So I think I did stumble onto a legitimate issue, but its probably not very important
and need not be prioritized.

Thanks.

**Comment by ziga-lunarg** [comment] 2022-03-09 01:03
@Jonathan-Weinstein Thanks for the detailed report, I'll take a look

**Comment by BingoBongoVrn** [comment] 2022-06-22 10:26
Is this still an issue? Because right now I'm in the same situation. I have buffer that first is updated by transfer operation then it just used as vertex buffer through vkCmdBindVertexBuffers() command and never touched again by other commands. So in application it works fine until suddenly validation layer reports:

INFO, E:\fbr\trunk\source\fbr\vulkan\Instance.cpp: Vulkan: Validation Error: [ SYNC-HAZARD-READ_AFTER_WRITE ] Object 0: handle = 0xcf89ea00000003c6, type = VK_OBJECT_TYPE_BUFFER; | MessageID = 0x4cb75b2d | vkCmdDraw: Hazard READ_AFTER_WRITE for vertex VkBuffer 0xcf89ea00000003c6[] in VkCommandBuffer 0x214765f8370[]. Access info (usage: SYNC_VERTEX_ATTRIBUTE_INPUT_VERTEX_ATTRIBUTE_READ, prior_usage: SYNC_COPY_TRANSFER_WRITE, write_barriers: 0, command: vkCmdCopyBuffer, seq_no: 30, reset_no: 117).

I want to mention that in pipeline this buffer has input rate VK_VERTEX_INPUT_RATE_INSTANCE (not VK_VERTEX_INPUT_RATE_VERTEX).

**Comment by jzulauf-lunarg** [comment] 2022-06-27 15:42
@ncesario-lunarg @jeremy-lunarg -- I'm suspicious of the VK_WHOLE_SIZE handling in `MakeBufferMemoryBarriers` though it looks correct at first pass.  If the SyncOpBarriers is created with the wrong size, the Apply barriers range could write out of bounds in the "fake_base_address" space the resource usage records are in.

That's where I'd step through with the replay, in any case.

**Comment by Jonathan-Weinstein** [comment] 2022-06-27 18:05
I'm not sure how portable the original .gfxr capture is because it enables many unnecessary features/extensions. If I disable some of them and make a new capture on an RTX 3070, I am able to replay it (with -m remap) on an Intel Tigerlake. Let me know if a new capture could be helpful.

I don't think `VkBufferMemoryBarrier`s specifically are suspect. The messages still occur after I tried changing every `VkBufferMemoryBarrier` to a `VkMemoryBarrier` by dropping srcQueueFamilyIndex/dstQueueFamilyIndex (always VK_QUEUE_FAMILY_IGNORED) and the buffer/size/offset fields.

**Comment by jzulauf-lunarg** [comment] 2023-02-14 16:42
Cannot repro -- doesn't occur in gfxrecon-replay.  No sure if this reflects an earlier bug fix, or a replay incompatibility.

However, there are numerous (AFAICT) genuine CoreCheck and SyncVal issues.

```
SYNC-HAZARD-READ-AFTER-WRITE(ERROR / SPEC): msgNum: -455515022 - Validation Error: [ SYNC-HAZARD-READ-AFTER-WRITE ] Object 0: handle = 0x3a9c5c00000000c4, type = VK_OBJECT_TYPE_IMAGE; | MessageID = 0xe4d96472 | vkCmdBlitImage: Hazard READ_AFTER_WRITE for srcImage VkImage 0x3a9c5c00000000c4[], region 0. Access info (usage: SYNC_BLIT_TRANSFER_READ, prior_usage: SYNC_IMAGE_LAYOUT_TRANSITION, write_barriers: `SYNC_COPY_TRANSFER_WRITE|SYNC_RESOLVE_TRANSFER_WRITE|SYNC_BLIT_TRANSFER_WRITE|SYNC_CLEAR_TRANSFER_WRITE`, command: vkCmdPipelineBarrier, seq_no: 1, reset_no: 2).
```

I've confirmed in the debugger, reflects a missing `VK_ACCESS_TRANSFER_READ_BIT` in the preceding barrier command.

Also, given the numerous UNASSIGNED-CoreValidation-DrawState-InvalidImageLayout errors, I'd usually say the code wasn't ready for syncval testing yet.

Note that with the new queue submit time syncval support there are additional errors. 

Use: 

`VK_LAYER_ENABLES=VK_VALIDATION_FEATURE_ENABLE_SYNCHRONIZATION_VALIDATION_EXT;VALIDATION_CHECK_ENABLE_SYNCHRONIZATION_VALIDATION_QUEUE_SUBMIT`

to enable.

**Comment by jzulauf-lunarg** [comment] 2023-03-22 20:41
Cannot repro, no followup from issue author.  Closing

**Closed by jzulauf-lunarg** 2023-03-22 20:41 UTC
Labels: Synchronization
