### ISSUE TITLE
missing VkSparseImageMemoryBindInfo VUs

### ISSUE THREAD

**Issue by spencer-lunarg** [KhronosGroup/Vulkan-ValidationLayers#6758] opened 2023-10-19 09:36 UTC
- VUID-VkSparseImageMemoryBindInfo-subresource-01722
- VUID-VkSparseImageMemoryBindInfo-subresource-01723

these should be simple to add as it is just basic logic, similar to `VUID-VkSparseImageMemoryBindInfo-image-02901`

**Comment by arno-lunarg** [comment] 2023-10-20 06:12
Basically a duplicate of `VUID-VkSparseImageMemoryBind-subresource-01106`

**Comment by ziga-lunarg** [comment] 2024-12-20 22:27
These VUIDs are already in, @spencer-lunarg is there anything else to do here?

**Closed** 2024-12-21 00:24 UTC
Labels: Incomplete, SpecChange
