### ISSUE TITLE
possible bug with location/component validation

### ISSUE THREAD

**Issue by zmike** [KhronosGroup/Vulkan-ValidationLayers#5735] opened 2023-04-25 15:02 UTC
When running 'dEQP-GLES31.functional.separate_shader.random.69' on zink with lavapipe, I get:

```
UNASSIGNED-CoreValidation-Shader-MissingOutput(ERROR / SPEC): msgNum: 1086655814 - Validation Error: [ UNASSIGNED-CoreValidation-Shader-MissingOutput ] Object 0: handle = 0x603cd90000000044, type = VK_OBJECT_TYPE_SHADER_MODULE; Object 1: handle = 0x8cc1d80000000045, type = VK_OBJECT_TYPE_SHADER_MODULE; | MessageID = 0x40c50d46 | vkCreateGraphicsPipelines(): pCreateInfos[0] VK_SHADER_STAGE_FRAGMENT_BIT declared input at Location 0 Comonent 2 but it is not an Output declared in VK_SHADER_STAGE_VERTEX_BIT
```

The VS output type for location 0 is a vec2.

The FS input type for location 0 is mat3x2.

There doesn't appear to be any component 2 access in the fragment shader, so this seems invalid.

Shaders attached:

[vs2.txt](https://github.com/KhronosGroup/Vulkan-ValidationLayers/files/11323530/vs2.txt)
[fs2.txt](https://github.com/KhronosGroup/Vulkan-ValidationLayers/files/11323531/fs2.txt)

Repro with:

`ZINK_DEBUG=validation LIBGL_ALWAYS_SOFTWARE=1 MESA_LOADER_DRIVER_OVERRIDE=zink MESA_SHADER_CACHE_DISABLE=true ./glcts -n 'dEQP-GLES31.functional.separate_shader.random.69'`

**Comment by spencer-lunarg** [comment] 2023-04-26 05:56
> UNASSIGNED-CoreValidation-Shader-MissingOutput

This is `VUID-RuntimeSpirv-OpEntryPoint-08743` now

I am able to reproduce this

https://gitlab.khronos.org/vulkan/vulkan/-/issues/3445

So I raised this issue already recently when doing the shader refactor, still not clear how the Matrix consumes Locations/Components

For now, since there is clearly CTS on this, will remove this `3 x vec2` to `mat3x2` for getting triggered

**Comment by spencer-lunarg** [comment] 2023-08-31 00:45
@zmike we happy to close this as this seems to be sadly what the spec restricts for now

**Comment by zmike** [comment] 2023-08-31 00:49
Yeah let's do it

**Comment by spencer-lunarg** [comment] 2023-08-31 00:51
1 more done for what seems like the ever going battle of how 2 shaders can interface with each other

**Closed** 2023-08-31 00:50 UTC
Labels: ShaderVal, SpecChange

**Comment by zmike** [comment] 2023-08-31 00:56
The only way to win the battle is to not use shaders.
