### ISSUE TITLE
Can't run ToT tests on devsim (CI failing as well)

### ISSUE THREAD

**Issue by sfricke-samsung** [KhronosGroup/Vulkan-ValidationLayers#1713] opened 2020-04-11 20:08 UTC
Noticed when rebasing some PR that they are not failing CI. I tried pulling down ToT, grabbed 137 headers and clean build and what not and get

```
./tests/vk_layer_validation_tests --devsim
[==========] Running 656 tests from 4 test cases.
[----------] Global test environment set-up.
[----------] 499 tests from VkLayerTest
[ RUN      ] VkLayerTest.InstanceExtensionDependencies
[       OK ] VkLayerTest.InstanceExtensionDependencies (14 ms)
[ RUN      ] VkLayerTest.InstanceBadStype
[       OK ] VkLayerTest.InstanceBadStype (5 ms)
[ RUN      ] VkLayerTest.InstanceDuplicatePnextStype
[       OK ] VkLayerTest.InstanceDuplicatePnextStype (7 ms)
[ RUN      ] VkLayerTest.InstanceFlags
[       OK ] VkLayerTest.InstanceFlags (5 ms)
[ RUN      ] VkLayerTest.InstanceAppInfoBadStype
[       OK ] VkLayerTest.InstanceAppInfoBadStype (5 ms)
[ RUN      ] VkLayerTest.InstanceValidationFeaturesBadFlags
[       OK ] VkLayerTest.InstanceValidationFeaturesBadFlags (10 ms)
[ RUN      ] VkLayerTest.InstanceBadValidationFlags
[       OK ] VkLayerTest.InstanceBadValidationFlags (9 ms)
[ RUN      ] VkLayerTest.DestroyInstanceAllocationCallbacksCompatibility
[       OK ] VkLayerTest.DestroyInstanceAllocationCallbacksCompatibility (6 ms)
[ RUN      ] VkLayerTest.DestroyInstanceHandleLeak
[       OK ] VkLayerTest.DestroyInstanceHandleLeak (7 ms)
[ RUN      ] VkLayerTest.PSOPolygonModeInvalid
Segmentation fault (core dumped)
```

Found `b41b9d0c3689232da2ff9ca63d59ad3da0569446` is last commit that works

Seems [Remove MockICD workarounds in instanceless](https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/8f07f8b0cf2847f06c5a91ae9b6d564b943cc5f5)

Didn't fully grasp why we removed 

> // WORKAROUND: Subsequent tests crash when this is not called. MockICD or Loader bug

in the commit. Can't figure out what/where the fix is for this workaround instead. (or is there a new minimum version of the loader/MockICD needed now?)

cc @krOoze

**Comment by krOoze** [comment] 2020-04-11 21:13
Yea, head of mockicd (Vulkan-Tools) is needed.

**Comment by sfricke-samsung** [comment] 2020-04-11 21:38
Ok, let me grab a ToT loader/mockICD and try again!

Maybe it would be good to have a version of Vulkan-Tools and Vulkan-Loader in the known-good.json file and have a `update_testing_dep.py` script or something so that both someone writing a test and the CI are on the same, reproducible, page

**Comment by sfricke-samsung** [comment] 2020-04-11 21:45
Updating just the loader to ToT gets me

```
...
[ RUN      ] VkLayerTest.DestroyInstanceHandleLeak
[       OK ] VkLayerTest.DestroyInstanceHandleLeak (7 ms)
[ RUN      ] VkLayerTest.PSOPolygonModeInvalid
malloc(): smallbin double linked list corrupted
Aborted (core dumped)
```

so seems the loader version is not the issue

**Comment by krOoze** [comment] 2020-04-11 21:58
I believe it was removed from known-good. CI just pulls the master head now.

Loader should not matter for now. The things that fixed this for me are at Vulkan-Tools. Nevertheless the workarounds are back because of other things; just pull the head of layers.

**Comment by sfricke-samsung** [comment] 2020-04-11 22:42
With ToT Vulkan-Tools get further

```
[       OK ] VkLayerTest.CreatePipelineLayoutExcessPerStageDescriptors (11 ms)
[ RUN      ] VkLayerTest.CreatePipelineLayoutExcessDescriptorsOverall
vk_layer_validation_tests: /home/sfricke/github/VulkanTools/layersvt/device_simulation.cpp:481: static (anonymous namespace)::PhysicalDeviceData &(anonymous namespace)::PhysicalDeviceData::Create(VkPhysicalDevice, VkInstance): Assertion `!Find(pd)' failed.
Aborted (core dumped)
```

----

>  CI just pulls the master head now

Ok thats fair, just annoying having to update loader, vulkan-tools, and vulkantools in order to test layers

**Comment by krOoze** [comment] 2020-04-12 05:25
The mock always returns the same physical device, which would make the assertion fail. We perhaps might want to make mock little bit stateful to avood these classes of errors.

Also makes me think there is something wrong with debug callback skip.  The instance tests should never reach icd or devsim. Do you have the devsim layer ordered after validation layer?

**Comment by sfricke-samsung** [comment] 2020-04-13 16:06
> Do you have the devsim layer ordered after validation layer

I don't set the devsim layer in my env as the `--devsim` explicitly adds it for you after

**Comment by mark-lunarg** [comment] 2020-04-13 17:39
@sfricke-samsung, I just pulled and rebuilt TOT VulkanTools, TOT Vulkan-Tools, and Vulkan-ValidationLayers, and they seem to run, at least with the mobile_chip profile, and we got a clean run through CI on Saturday.  I apologize for the build failures. we had a large basket of stuff go into master, I didn't manage to sort out all the interactions in time to keep the repo clean throughout.  

BTW, as @krOoze mentioned, we did pull these repos from VVL known-good for a few reasons -- the big one is that there were circular dependencies between those two repos and VVL, which helped to make header updates a nightmare.  Since these two repos are only used by VVL for Travis CI, we concluded that the penalty was worth the pain, especially since it's limited to people running the LVTs AND using the mock ICD (which is pretty small).  Sorry for the extra inconvenience!

BTW, I still need to root-cause why removing those workarounds busted the test framework.

**Comment by mark-lunarg** [comment] 2020-04-13 17:39
I'm going to close this for now, but if you are still running into trouble, add another comment to this issue.  I'll reopen it and get right on the problem.

**Comment by krOoze** [comment] 2020-04-13 18:10
@mark-lunarg I am trying now as well (w\o workarounds), and I seem to be able to reproduce:

> [ RUN      ] VkLayerTest.[random]
Assertion failed: !Find(pd), file C:\Dev\_GitHub\VulkanTools\layersvt\device_simulation.cpp, line 481
d:\agent\_work\8\s\src\vctools\crt\github\stl\src\mutex.cpp(64): mutex destroyed while busy

**Comment by krOoze** [comment] 2020-04-13 18:29
@mark-lunarg Yea, it seems all the headaches were\are caused by layers at `vkCreateInstance` are lacking the callback skip code.  Though can't hurt to fix the devsim directly too, whatever problem this discovered...

**Comment by mark-lunarg** [comment] 2020-04-13 18:30
@krOoze, can you help me reproduce? I'm guessing you pulled and rebuilt VT and V-T, what's your OS and which devsim profile?

**Comment by sfricke-samsung** [comment] 2020-04-13 18:30
So my CI for some of my PR are also showing errors that look the same
https://travis-ci.org/github/KhronosGroup/Vulkan-ValidationLayers/jobs/673870676

**Comment by krOoze** [comment] 2020-04-13 18:34
@mark-lunarg V-VL head + drop workaround, V-T head, VT head.
In command arguments for tests add `--devsim`, then in env I have this:

> VK_LAYER_PATH=$(SolutionDir)\layers\$(Configuration);C:\Dev\_GitHub\VulkanTools\build\layersvt\Debug
VK_ICD_FILENAMES=C:\Dev\_GitHub\Vulkan-Tools\build\icd\Debug\VkICD_mock_icd.json
VK_DEVSIM_FILENAME=C:\Dev\_GitHub\Vulkan-ValidationLayers\tests\device_profiles\adreno_540.json

**Comment by mark-lunarg** [comment] 2020-04-13 18:37
Ah!  Ok, w/o workarounds, I missed that.  I thought I'd borked Master again.  Anyhow, I'll leave this open for the time-being.

**Comment by krOoze** [comment] 2020-04-13 18:58
@mark-lunarg Not for long. #1717 should fix this. There's some aspect to this in devsim that does not work correctly (or in a simplified way), but that should not matter for now if the skip works.

**Comment by sfricke-samsung** [comment] 2020-04-16 01:59
pulling ToT and running it things seem to be back to normal. Not sure what changed, but thanks again to @krOoze for helping triage this. I am happy to keep this open until 1717 merges, otherwise my issue of being able to run devsim seems to be gone now!

**Comment by krOoze** [comment] 2020-04-16 02:29
@sfricke-samsung AIS the workarounds were reinstated. After #1717, they can be reremoved, hopefully without breaking your stuff again. Also I made some tweaks to mock and devsim that should avoid it; tests should now each have its own physical device states so corruption should not happen.

**Closed** 2020-04-16 16:13 UTC
