### ISSUE TITLE
Potential bug with barrier hazard detection

### ISSUE THREAD

**Issue by ShabbyX** [KhronosGroup/Vulkan-ValidationLayers#2093] opened 2020-08-05 21:41 UTC
We recently enabled hazard detection and see a handful of hazards in ANGLE. I dived in one of them, which you can reproduce by:

1. Setup ANGLE (angleproject.org, but I know some at LunarG at least are already familiar with ANGLE)
2. Take the following change (if not already landed): https://chromium-review.googlesource.com/c/angle/angle/+/2297884
3. Build ANGLE
4. Run for example:

       ./angle_deqp_gles3_tests --use-angle=vulkan --deqp-case=dEQP-GLES3.functional.samplers.multi_tex_3d.diff_min_lod`

5. Observe validation errors regarding WRITE_AFTER_READ hazards. The exact message I'm investigating is:

       vkCmdPipelineBarrier: Hazard WRITE_AFTER_READ for image barrier 0 VkImage 0x6b000000006b[]. Access info (usage: SYNC_IMAGE_LAYOUT_TRANSITION, prior_usage: SYNC_TRANSFER_TRANSFER_READ, read_barriers: Unhandled VkPipelineStageFlagBits, command: vkCmdCopyImageToBuffer, seq_no: 14, reset_no: 1)

I have yet to fully investigate, but I see signs that perhaps there's a bug in VVL's hazard detection. The change that introduced these hazards is a19c71d0f (@locke-lunarg).

In `ResourceAccessState::DetectBarrierHazard`, I see a hazard detected because of:

```
if ((src_exec_scope & (read_access.stage | read_access.barriers)) == 0)
```

Here are some relevant values:

```
(gdb) p/x read_access
$62 = (const ResourceAccessState::ReadState &) @0x5555586c07d0: {
  stage = 0x1000,
  access = 0x10000000000,
  barriers = 0x0,
  tag = {
    index = 0x10000000e,
    command = 0x1d,
    static kMaxIndex = 0xffffffffffffffff
  }
}
(gdb) p src_exec_scope
$63 = 1
(gdb) p last_read_count
$66 = 1
```

The barrier that caused this is derived from this.

```
$65 = {
  srcStageMask = 0x1,
  dstStageMask = 0x1000,
  imageMemoryBarrier = {
    sType = 0x2d,
    pNext = 0x0,
    srcAccessMask = 0x0,
    dstAccessMask = 0x1000,
    oldLayout = 0x0,
    newLayout = 0x7,
    srcQueueFamilyIndex = 0x0,
    dstQueueFamilyIndex = 0x0,
    image = 0x6b000000006b,
    subresourceRange = {
      aspectMask = 0x1,
      baseMipLevel = 0x0,
      levelCount = 0x6,
      baseArrayLayer = 0x0,
      layerCount = 0x1
    }
  }
```

Note that `oldLayout` is UNDEFINED. In ANGLE, once we transition an image out of UNDEFINED, we never use that layout as `oldLayout` anymore. We also always transition the whole image (for now!). So the above tells me that this is the first time this image is being transitioned (i.e. used). However, the code in `ResourceAccessState::DetectBarrierHazard` suggests that there was a previous read from this image which I believe is impossible.

Also `ResourceAccessState::ReadState::access` says `0x10000000000` which doesn't make sense? Anyway, the `read_access` variable says that the previous read was from the TRANSFER stage, which again contradicts the fact that ANGLE is using UNDEFINED as the old layout (or that it uses TOP_OF_PIPE, or that `srcAccessMask` is 0. They all agree on the fact that the image was previously unused).

(final minor note: notice `read_barriers: Unhandled VkPipelineStageFlagBits` in the error message)

**Comment by jzulauf-lunarg** [comment] 2020-08-14 16:44
@ShabbyX  -- In the usage tag command and index indicate that sync val thinks that the 15th command  in the command buffer did a  vkCmdCopyImageToBuffer (seq_no: 14, reset_no: 1) read from that image is that possibly an ANGLE bug?  If you can backtrack to verify that the listed operation did not occur when SyncVal says it did, that would be appreciated.

The mapping from image subresource to the idealized address space we do our tracking in could be wrong, and thus tagging the wrong memory, and if the call is really not being made, then we'd need to chase that down.

**Comment by ShabbyX** [comment] 2020-08-24 16:21
@jzulauf-lunarg Running again today, the sync error has changed:

```
DebugUtilsMessenger(337): [ SYNC-HAZARD-WRITE_AFTER_READ ] Validation Error: [ SYNC-HAZARD-WRITE_AFTER_READ ] Object 0: handle = 0x370000000037, type = VK_OBJECT_TYPE_IMAGE; | MessageID = 0x4b3455b4 | vkCmdPipelineBarrier: Hazard WRITE_AFTER_READ for image barrier 0 VkImage 0x370000000037[]. Access info (usage: SYNC_IMAGE_LAYOUT_TRANSITION, prior_usage: SYNC_TRANSFER_TRANSFER_READ, read_barriers: VK_PIPELINE_STAGE_TRANSFER_BIT|VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT, command: vkCmdBlitImage, seq_no: 9, reset_no: 1)
```

Looking at renderdoc, I can see that the pipeline barrier causing this is issuing an UNDEFINED->TRANSFER_DST layout transition. There are the following commands before it:

- Barrier: 3D Color Attachment 148: UNDEFINED->TRANSFER_DST
- vkCmdCopyBufferToImage: Buffer 146 to 3D Color Attachment 148
- A series of blits between levels of 3D Color Attachment 148 with appropriate barriers (generating mipmap)
- (VVL Error) Barrier: 3D Color Attachment 155: UNDEFINED->TRANSFER_DST
- (goes on to do mip generation for this other image)

According to renderdoc, the barrier that's transitioning the layout of 3D Color Attachment 155 is the very first use of this image. I think it's a VVL bug to think there's a hazard here, as this image was not previously used at all.

**Comment by jzulauf-lunarg** [comment] 2020-08-28 23:35
@ShabbyX  -- Thanks for the follow up.  It's our bug... PR tomorrow.

**Comment by ShabbyX** [comment] 2020-09-03 14:51
@jzulauf-lunarg Looks like there is still a bug here, but with 2D array textures: https://ci.chromium.org/p/chromium/builders/try/linux_angle_deqp_rel_ng/16629

**Comment by jzulauf-lunarg** [comment] 2020-09-03 17:12
@ShabbyX  Reopening -- Having difficulty navigating the issue to what the command line would be to repro.

**Comment by ShabbyX** [comment] 2020-09-03 17:29
@jzulauf-lunarg Are you able to clone ANGLE standalone (as in, not inside Chromium) and build it?

**Comment by ShabbyX** [comment] 2020-09-03 17:32
Tried one of the failures on the bot I linked to a few comments back, and I can reproduce with this (for example):

```
$ ./angle_deqp_gles31_tests --use-angle=vulkan --deqp-case=dEQP-GLES31.functional.image_load_store.2d_array.load_store.rgba8
```

Again, note that you need to cherry-pick this change which enables syncval: https://chromium-review.googlesource.com/c/angle/angle/+/2297884

**Comment by jzulauf-lunarg** [comment] 2020-09-04 03:55
@ShabbyX -- cannot reproduce with my fix integrated.  Is it platform specific? Verified in debug that sync validation was running.  No hazards.

**Comment by jzulauf-lunarg** [comment] 2020-09-08 21:13
@shabbyx `dEQP-GLES31.functional.image_load_store.2d_array.load_store.rgba8` is platform specific and was able to reproduce on my Linux NV host.

However it appears to be an an angle or test bug.  The test is writing a resource and then reading it, but the only barrier between the write and the read is an execution barrier.  `ImageLoadAndStoreCase::iterate` writes to texture1 with Compute and then reads it with `readTextureAndVerify`. However, the memory buffer generated down the read chain only sends a `pMemoryBarrier` with 0 access masks. Thus, there is no protection for the read from the write, and we get a READ_AFTER_WRITE error. 

`readFloatOrNormTextureWithLookupsAndVerify` calls 
`glLog.glMemoryBarrier(GL_TEXTURE_FETCH_BARRIER_BIT);` but `ContextVk::memoryBarrierImpl` only sets the `*AccessMask` for `GL_SHADER_IMAGE_ACCESS_BARRIER_BIT | GL_SHADER_STORAGE_BARRIER_BIT`.  Not sure if the *test* should be more aggressive in calling `glMemoryBarrier` or if the issue is lower down.

**Comment by ShabbyX** [comment] 2020-09-10 20:27
Thanks for the analysis. Since the previous fix was for 3D textures, I wrongly assumed there was a similar issue with 2D textures. Sorry about that.

I'll have to look into it. If `readTextureAndVerify` is using a draw call to read the texture, then it's odd as the compute write and texture read necessarily require ANGLE to issue an image layout transition (hence a memory barrier). If that's missing, it means that ANGLE is not transitioning the image to READ_ONLY but is keeping it in GENERAL (but then it should have still issued a WaW (knowing that ANGLE assumes GENERAL=Write) barrier).

If on the other hand the texture is bound to a framebuffer and read back (through glReadPixels), then the GL barrier should have had `GL_FRAMEBUFFER_BARRIER_BIT`.

Anyway, if [this](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2158) is purely disabling the check for the sake of disabling it, maybe hold off until I investigate it more. If it's a test bug, I could fix that instead.

**Comment by jzulauf-lunarg** [comment] 2020-09-11 19:00
@ShabbyX  Okay.  Reclosing. The PR above is merged, so the master branch has everything I've fixed.  Got a couple of pending issues.

**Closed by jzulauf-lunarg** 2020-09-11 19:00 UTC
Labels: Synchronization, bug

**Comment by ShabbyX** [comment] 2020-09-12 02:33
@jzulauf-lunarg Turned out that was indeed an ANGLE bug (a regression I had introduced myself...). So, thanks for catching that!
