### ISSUE TITLE
syncval WRITE-AFTER-READ error with DEPTH_STENCIL_READ_ONLY attachment

### ISSUE THREAD

**Issue by ShabbyX** [KhronosGroup/Vulkan-ValidationLayers#2349] opened 2020-11-25 18:16 UTC
Take the following situation:

- Transition D/S image to DEPTH_STENCIL_READ_ONLY
- Start RP with storeOp=DONT_CARE (or STORE, doesn't matter as long as it's not NONE_QCOM)
- Draw with depth write disabled, and the D/S image simultaneously bound as a texture (and sampled from)
- End RP

syncval warns that storeOp is a WRITE operation that is done after the draw call READ from the image. However, there's no way to add any synchronization for this.

[Here](https://drive.google.com/file/d/1EwByeYQHXcWe4snSHU6__Dx-B_tNR05v/view?usp=sharing)'s a renderdoc trace showing this issue. It can be reproduced by applying the following changes to ANGLE; [Change1](https://chromium-review.googlesource.com/c/angle/angle/+/2551394) [Change2](https://chromium-review.googlesource.com/c/angle/angle/+/2297884), and running

    $ ./angle_end2end_tests --gtest_filter=FramebufferTest_ES3.ReadOnlyDepthFeedbackLoopSupported/ES3_Vulkan

**Comment by jzulauf-lunarg** [comment] 2021-05-03 15:24
@ShabbyX -- even though the storeOp is specified as DONT_CARE, the spec defines this as a write operation -- meaning that implementations may choose to write.  From section 8.1

https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkAttachmentStoreOp.html

• VK_ATTACHMENT_STORE_OP_STORE specifies the contents generated during the render pass and
within the render area are written to memory. For attachments with a depth/stencil format, this
uses the access type VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT. For attachments with a
color format, this uses the access type VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT.


I'm not confident however, that the write disable logic in syncval is correct...  so if you have a test case for that...

**Comment by ShabbyX** [comment] 2021-05-03 19:25
@jzulauf-lunarg I have linked to a renderdoc capture in the OP, is that not usable? The description of the bug nevertheless has the necessary information required to write a test.

I realize that storeOp=DONT_CARE is a write operation as far as the spec is concerned. The issue is that using a read-only depth/stencil attachment without storeOp=NONE_QCOM will always result in a syncval warning with no mechanism in Vulkan to add any synchronization to satisfy it.

**Comment by jzulauf-lunarg** [comment] 2021-05-03 23:02
Ah, I thought the hazard was following the store.  The rasterization ordering rules are *supposed* to handle this case (which the sync val is modelling), so there shouldn't be an error in the usual case.  I'll run your repro cases to try an understand if/what I'm missing here. If there needs to be a barrier, a self-dependency would be the way to handle it, but let's make sure it's not my issue.

**Comment by ShabbyX** [comment] 2021-05-04 16:38
To confirm, the hazard is on render pass end! I'd also like to point out that this issue is 6 months old, so it might be already fixed. Unfortunately the ANGLE changes that brought this up weren't merged and I haven't looked into resolving the merge conflicts to see if the issue is still reproducible. Regardless, a unit test in VVL is useful.

**Comment by jzulauf-lunarg** [comment] 2021-05-05 22:49
@shabbyX -- I'm not sure that the validation isn't correct.  

> The store operation for each sample in an attachment happens-after any recorded command which
accesses the sample in the last subpass where the attachment is used. Store operations for attachments with a depth/stencil format execute in the VK_PIPELINE_STAGE_LATE_FRAGMENT_TESTS_BIT pipeline stage. Store operations for attachments with a color format execute in the VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT pipeline stage.

The texture read happens in VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT.  A self dependency would certainly give you the ability to store without hazard.  There doesn't seem to be anything in the spec to state that a read-only resource is exempt from store operations.  Also, the rasterization order rule are currently stage specific, which I think matches the specification.

I'm going to pose a question re: the spec on this question.

**Comment by jzulauf-lunarg** [comment] 2021-05-10 20:14
@ShabbyX  -- can you verify the prior access information for the WAR error, that it's a FRAGMENT_SHADER read?  (or just paste the error string)

**Comment by jzulauf-lunarg** [comment] 2021-05-12 16:26
@hapakj  -- the subpass dependency alone won't solve this.  The subpass dependency defines what vkCmdPipelineBarrier are legal within the subpass.  After the last access in the last subpass referencing the attachment, you'll need a vkCmdPipelineBarrier (with either a VkMemoryBarrier or VkImageMemoryBarrier) before the vkCmdNextSubpass or vkCmdEndRenderPass that ends that subpass.

**Comment by ShabbyX** [comment] 2021-05-12 20:51
@jzulauf-lunarg Actually I don't believe we are restricted to fragment shader reads. I'm afraid the work I did that got me up to this message never got merged, and I don't intend to go through the merge conflicts. So, no, let's assume it's a vertex shader that's doing the sampling.

In that case, we can't use `VK_DEPENDENCY_BY_REGION_BIT` which effectively means pipeline barriers will result in an implicit render pass break on tilers which is costly. The STORE_OP_NONE_QCOM store op resolves this (which is being promoted to KHR), and it's probably best to just pursue that.

> I'm going to pose a question re: the spec on this question.

Please do let me know what internal issue number that is.

**Comment by jzulauf-lunarg** [comment] 2021-05-12 22:14
@ShabbyX  -- the issue is on gitlab... @Tobski and @jeffbolznv tagged.

Please add an issue to add support for VK_ATTACHMENT_STORE_OP_NONE_QCOM.  Currently Synchronization Validation has very little extension support, the issue will help prioritize it, especially if you note that it's going to be promoted to KHR.

**Comment by jzulauf-lunarg** [comment] 2021-05-12 22:17
@ShabbyX  -- as for which shader stage could trigger the WAR... any read access by any non-framebuffer-local stage would be reported as WAR without the required barrier.  Any access by a framebuffer-local stage is guaranteed (if I'm reading the spec correctly) to be safe w.r.t. storeOp's.

**Comment by Kangz** [comment] 2021-12-02 07:55
We are hitting the same issue in Dawn when implementing read-only depth stencil attachments in https://dawn-review.googlesource.com/c/dawn/+/70280 Since we can't rely on the presence of `STORE_OP_NONE`, the only thing we can do is ignore this syncval error.

However it doesn't seem that there is a WAR if you use `STORE_OP_STORE` because the values written to memory will be exactly the one already present, and you can later make these writes visible to operation with a DEPTH_STENCIL_WRITE pipeline barrier.

(and FYI @kvark for wgpu that will certainly hit the same issue)

**Comment by Tobski** [comment] 2021-12-02 09:11
@Kangz If DONT_CARE or STORE are used as store ops instead of NONE, it should just mean you need a barrier (or external subpass dependency) between the render pass and any further accesses for that attachment. That barrier has to sync the store op with the future accesses to prevent a RAW/WAW hazard. If sync_val is throwing a warning despite that extra barrier then there's still a problem here.

**Comment by Kangz** [comment] 2021-12-02 09:51
Yep we'll do that correctly (I think) by adding the `DEPTH_WRITE` access to be tracked for further barriers. But here the VVL complains about the write done by `STORE_OP_STORE` while the attachment is in `IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY`.

> [ SYNC-HAZARD-WRITE_AFTER_READ ] Object 0: handle = 0x1150000000115, type = VK_OBJECT_TYPE_RENDER_PASS; | MessageID = 0x4b3455b4 | vkCmdEndRenderPass: Hazard WRITE_AFTER_READ in subpass 0 for attachment 1 depth aspect during store with storeOp VK_ATTACHMENT_STORE_OP_STORE. Access info (usage: SYNC_LATE_FRAGMENT_TESTS_DEPTH_STENCIL_ATTACHMENT_WRITE, prior_usage: SYNC_FRAGMENT_SHADER_SHADER_STORAGE_READ, read_barriers: VK_PIPELINE_STAGE_2_NONE_KHR, command: vkCmdDraw, seq_no: 6, reset_no: 1)

**Comment by kvark** [comment] 2021-12-02 15:41
Looks like the issue needs to be re-opened if this fires up. We haven't done much running with the sync validation yet, but I imagine we'll see the same thing.

**Comment by jeremyg-lunarg** [comment] 2021-12-02 17:54
@jzulauf-lunarg  can you take another look at this one?

**Comment by jzulauf-lunarg** [comment] 2023-02-08 22:21
@kvark -- looking at this, it appears that you are using the same image as an attachment and as a storage image (VK_ACCESS_2_SHADER_STORAGE_READ_BIT).  Since the storage read is not framebuffer-local (though the stage is), it won't be implicitly ordered with the storeOp.  As self dependency here won't (can't) help is it is required to be framebuffer-local since both of the stages are framebuffer-space stages..

Effectively you're attempting to do a  framebuffer-global operation (the storage image read) and a  framebuffer-local operation (the store op) in the same subpass.  Except with storeOp NONE to eliminate the latter, there is not valid way to do this.

Think of it this way, a non-NONE storeOp operates on a  framebuffer-region basis.  For a trivial region (one with few or no shaded fragments), the storeOp could begin long before a region with many shaded fragments could complete.  For attachments this would be fine, because only fragments of a given region would be modified.  For a image load operation on a storage image (or texture) pixels (or texels) from *any* region can be read from any *other* region.  This means any image loads from the "many shaded fragments" region could be accessing (and racing) the pixels being stored.

To do this safely, you either need to use a NONE storeOp, *or* a dummy subpass with a framebuffer-global subpass dependency that *only* does the store operation.

**Comment by Kangz** [comment] 2023-02-09 11:40
I feel that some context has been lost: the attachment is in the `IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY` usage and the subpass has `loadOp: LOAD` and `storeOp: STORE`: this means that the value written to the framebuffer by the store op is the same value as the one that was loaded at the start of the render pass. There is technically a data race for the reason you stated of tiles being completed out of order, but the write operations of the race are noops. So the behavior should be well defined.

Dawn will eventually use `STORE_OP_NONE` in this case when available (because it is the correct solution) but in the meantime we suppress the VVL error  mentioned above because we are very confident this should be allowed.

**Comment by Tobski** [comment] 2023-02-09 12:30
@Kangz That exact situation is why we added STORE_OP_NONE - because STORE_OP_STORE is a real write on some hardware which can cause a genuine data race, even if the value is the same - the value being the same doesn't stop it potentially causing issues. Switching to STORE_OP_NONE will fix this.

**Comment by Kangz** [comment] 2023-02-09 15:59
Understood, I was hoping that wouldn't be the case but it makes sense that
framebuffer compression could technically cause the data race to be an
actual issue. However we don't really have a choice on Vulkan versions that
don't have STORE_OP_NONE so we'll keep suppressing and cross fingers until
we find it fails, and implement the correct logic when possible. Feel free
to close this as won't fix.

**Comment by jzulauf-lunarg** [comment] 2023-02-09 17:12
@Kangz -- the issue isn't the type of attachment use, but from the error message, the image underlying the attachment is being used as a storage image at the same time*.  The means you have simultaneous framebuffer-region and global access the same memory.  That's intrinsically racy. 

(*now if it isn't, then the bug is that we're incorrectly tagging the usage)

**Comment by Kangz** [comment] 2023-02-10 13:39
The failure we have now is just with `SYNC_FRAGMENT_SHADER_SHADER_SAMPLED_READ` because WebGPU doesn't have storage depth textures yet, but we are indeed using the attachment as a sampled texture at the same time. (without STORE_OP_NONE when that's not available).

**Comment by ShabbyX** [comment] 2023-02-10 14:10
> However we don't really have a choice on Vulkan versions that
don't have STORE_OP_NONE so we'll keep suppressing and cross fingers until
we find it fails, and implement the correct logic when possible.

If you're looking for data points, this is what ANGLE does as well (of course the suppression is conditional to lack of STORE_OP_NONE). So far, it hasn't caused any issues.

**Comment by jzulauf-lunarg** [comment] 2023-02-10 18:31
Work-as-designed.  Per Tobias, there are platforms on which this actually isn't safe.

**Closed** 2023-02-10 18:31 UTC
Labels: Bug, Synchronization
