### ISSUE TITLE
I am on parse results

### ISSUE THREAD

**Issue by Azaretdodo** [KhronosGroup/Vulkan-ValidationLayers#1822] opened 2020-05-07 10:49 UTC
Hello,

I am on parse result :

![Python Parse Result Vulkan-ValidationLayers Scripts](https://user-images.githubusercontent.com/30596513/81286208-f92da600-9060-11ea-921e-b37602a0d01b.jpg)

I am in adding python interpreter in all yours Vulkan forker,

I Don't add to VUlkan-Docs the python interpreter,

Because I am in python asked by your installing,

Regards.

Azaretdodo.

**Comment by mark-lunarg** [comment] 2020-05-07 14:14
@Azaretdodo, is there a problem with the parse_test_results script?

**Comment by Azaretdodo** [comment] 2020-05-07 14:27
this is my fedora problem the administrator console command line close by itself
________________________________
De : Dorian ROSSE <dorianbrice@hotmail.fr>
Envoyé : jeudi 7 mai 2020 16:27
À : KhronosGroup/Vulkan-ValidationLayers <Vulkan-ValidationLayers@noreply.github.com>; KhronosGroup/Vulkan-ValidationLayers <reply@reply.github.com>
Cc : Mention <mention@noreply.github.com>
Objet : RE: [KhronosGroup/Vulkan-ValidationLayers] I am on parse results (#1822)

I have no happen error but the window were closed by ItSelf leaving the python run...
________________________________
De : Mark Lobodzinski <notifications@github.com>
Envoyé : jeudi 7 mai 2020 16:14
À : KhronosGroup/Vulkan-ValidationLayers <Vulkan-ValidationLayers@noreply.github.com>
Cc : Azaretdodo <dorianbrice@hotmail.fr>; Mention <mention@noreply.github.com>
Objet : Re: [KhronosGroup/Vulkan-ValidationLayers] I am on parse results (#1822)


@Azaretdodo<https://github.com/Azaretdodo>, is there a problem with the parse_test_results script?

**Comment by Azaretdodo** [comment] 2020-05-07 14:29
if you want I launch the script by the hand method !

the monitor and the keyboard !

Thank you in advance to ask this mode if you need,

Regards.


Azaretdodo.
________________________________
De : Dorian ROSSE <dorianbrice@hotmail.fr>
Envoyé : jeudi 7 mai 2020 16:27
À : KhronosGroup/Vulkan-ValidationLayers <Vulkan-ValidationLayers@noreply.github.com>; KhronosGroup/Vulkan-ValidationLayers <reply@reply.github.com>
Cc : Mention <mention@noreply.github.com>
Objet : RE: [KhronosGroup/Vulkan-ValidationLayers] I am on parse results (#1822)

this is my fedora problem the administrator console command line close by itself
________________________________
De : Dorian ROSSE <dorianbrice@hotmail.fr>
Envoyé : jeudi 7 mai 2020 16:27
À : KhronosGroup/Vulkan-ValidationLayers <Vulkan-ValidationLayers@noreply.github.com>; KhronosGroup/Vulkan-ValidationLayers <reply@reply.github.com>
Cc : Mention <mention@noreply.github.com>
Objet : RE: [KhronosGroup/Vulkan-ValidationLayers] I am on parse results (#1822)

I have no happen error but the window were closed by ItSelf leaving the python run...
________________________________
De : Mark Lobodzinski <notifications@github.com>
Envoyé : jeudi 7 mai 2020 16:14
À : KhronosGroup/Vulkan-ValidationLayers <Vulkan-ValidationLayers@noreply.github.com>
Cc : Azaretdodo <dorianbrice@hotmail.fr>; Mention <mention@noreply.github.com>
Objet : Re: [KhronosGroup/Vulkan-ValidationLayers] I am on parse results (#1822)


@Azaretdodo<https://github.com/Azaretdodo>, is there a problem with the parse_test_results script?

**Comment by mark-lunarg** [comment] 2020-05-07 14:32
Do any of the other scripts do the same thing?  Also, this is a specialized script used for running the test scripts in a continuous integration farm -- are you doing something similar?

**Comment by Azaretdodo** [comment] 2020-05-07 14:40
I have launch all scripts in layer folder, test folder and scripts folder, this is the only scripts who hasn't finish,

somescripts failed with dependencies asked that by 'mkdir' or 'touch',

On your build folder I have success to add python for the build settings,

Now I am on Wayland error,

I have add Wayland but It can't build fully because expat keep missing,

I Don't know why because I have download expat from this link :

http://prdownloads.sourceforge.net/expat/expat-1.95.7.tar.gz

expat keep missing !

I send and e-mail to wayland for know the repairing,

Regards.


Azaretdodo.
________________________________
De : Mark Lobodzinski <notifications@github.com>
Envoyé : jeudi 7 mai 2020 16:32
À : KhronosGroup/Vulkan-ValidationLayers <Vulkan-ValidationLayers@noreply.github.com>
Cc : Azaretdodo <dorianbrice@hotmail.fr>; Mention <mention@noreply.github.com>
Objet : Re: [KhronosGroup/Vulkan-ValidationLayers] I am on parse results (#1822)


Do any of the other scripts do the same thing? Also, this is a specialized script used for running the test scripts in a continuous integration farm -- are you doing something similar?

**Comment by Azaretdodo** [comment] 2020-05-07 14:41
somescripts who ask file or folder keep in error status !
________________________________
De : Dorian ROSSE <dorianbrice@hotmail.fr>
Envoyé : jeudi 7 mai 2020 16:40
À : KhronosGroup/Vulkan-ValidationLayers <Vulkan-ValidationLayers@noreply.github.com>; KhronosGroup/Vulkan-ValidationLayers <reply@reply.github.com>
Cc : Mention <mention@noreply.github.com>
Objet : RE: [KhronosGroup/Vulkan-ValidationLayers] I am on parse results (#1822)

I have launch all scripts in layer folder, test folder and scripts folder, this is the only scripts who hasn't finish,

somescripts failed with dependencies asked that by 'mkdir' or 'touch',

On your build folder I have success to add python for the build settings,

Now I am on Wayland error,

I have add Wayland but It can't build fully because expat keep missing,

I Don't know why because I have download expat from this link :

http://prdownloads.sourceforge.net/expat/expat-1.95.7.tar.gz

expat keep missing !

I send and e-mail to wayland for know the repairing,

Regards.


Azaretdodo.
________________________________
De : Mark Lobodzinski <notifications@github.com>
Envoyé : jeudi 7 mai 2020 16:32
À : KhronosGroup/Vulkan-ValidationLayers <Vulkan-ValidationLayers@noreply.github.com>
Cc : Azaretdodo <dorianbrice@hotmail.fr>; Mention <mention@noreply.github.com>
Objet : Re: [KhronosGroup/Vulkan-ValidationLayers] I am on parse results (#1822)


Do any of the other scripts do the same thing? Also, this is a specialized script used for running the test scripts in a continuous integration farm -- are you doing something similar?

**Comment by Azaretdodo** [comment] 2020-05-07 14:43
I Don't know why I can't send an e-mail to wayland
________________________________
De : Mark Lobodzinski <notifications@github.com>
Envoyé : jeudi 7 mai 2020 16:32
À : KhronosGroup/Vulkan-ValidationLayers <Vulkan-ValidationLayers@noreply.github.com>
Cc : Azaretdodo <dorianbrice@hotmail.fr>; Mention <mention@noreply.github.com>
Objet : Re: [KhronosGroup/Vulkan-ValidationLayers] I am on parse results (#1822)


Do any of the other scripts do the same thing? Also, this is a specialized script used for running the test scripts in a continuous integration farm -- are you doing something similar?

**Comment by mark-lunarg** [comment] 2020-05-07 14:49
Running the parse_test_results script is not intended or recommended for end-users.  If you look at the instructions included in the script, you can see the requirements for running it properly.  Just running `python parse_test_results.py` is incorrect, and will cause the behavior you describe.

**Comment by mark-lunarg** [comment] 2020-05-07 15:56
@Azaretdodo, closing this issue for now.  If you find that the script does not operate as intended, reply here and I will reopen the issue.  Thanks!

**Closed by mark-lunarg** 2020-05-07 15:56 UTC
