### ISSUE TITLE
[Synchronization] Bindless textures support ?

### ISSUE THREAD

**Issue by Vincent-P** [KhronosGroup/Vulkan-ValidationLayers#2943] opened 2021-07-06 17:37 UTC
**Describe the Issue**
Hello,
It isn't clear to me if bindless is supported or not.
I am using one big descriptor array for COMBINED_IMAGE_SAMPLER descriptors, and I access them with non-uniform index.
Right now I have only one shader drawing imgui onto the swapchain. Because all of the images are bound in the bindless set, I am getting a READ_AFTER_WRITE hazard on the swapchain even though the shader isn't sampling this particular descriptor.

The other weird thing is that there is only a handful of these errors (4 on the 1st swapchain image and 6 on the second one exactly) at startup. If it truly was a hazard on each draw I'd expect to have errors at each frame.

**Valid Usage ID**
```
Validation Error: [ SYNC-HAZARD-READ_AFTER_WRITE ] Object 0: handle = 0x18b565279d0, name = Swapchain #0 full view, type = VK_OBJECT_TYPE_IMAGE_VIEW; | MessageID = 0x4cb75b2d | vkCmdDrawIndexed: Hazard READ_AFTER_WRITE for VkImageView 0x18b565279d0[Swapchain #0 full view], in VkCommandBuffer 0x18b56eb3c30[], and VkPipeline 0x18b56e99860[imgui], VkDescriptorSet 0x18b56bcd1c0[bindless sampled images], type: VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, imageLayout: VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL, binding #0, index 2. Access info (usage: SYNC_FRAGMENT_SHADER_SHADER_STORAGE_READ, prior_usage: SYNC_COLOR_ATTACHMENT_OUTPUT_COLOR_ATTACHMENT_WRITE, write_barriers: 0, command: vkCmdBeginRenderPass, seq_no: 7, reset_no: 1).
Objects:
         [0] Swapchain #0 full view
```

**Environment:**
 - OS:  Windows 10 Pro 19043
 - GPU: RX 5700XT, 21.5.1 driver
 - SDK or header version if building from repo: Vulkan SDK 1.2.176.0
 - Options enabled (synchronization, best practices, etc.): Synchronization preset from Vulkan Configurator (Thread Safety + Synchronization)

**Comment by ncesario-lunarg** [comment] 2021-07-06 18:46
Thank you for the issue @Vincent-P, by "bindless textures," are you referring to a particular extension (e.g., `VK_EXT_descriptor_indexing`?)?

Would you be able to provide some sample code to reproduce the issue?

FYI @jeremyg-lunarg.

**Comment by Vincent-P** [comment] 2021-07-06 18:53
Yes I am indeed referring to this extension.
I am creating the set with the following flags: `VK_DESCRIPTOR_BINDING_PARTIALLY_BOUND_BIT | VK_DESCRIPTOR_BINDING_UPDATE_AFTER_BIND_BIT | VK_DESCRIPTOR_BINDING_UPDATE_UNUSED_WHILE_PENDING_BIT`.

My actual code is quite complex but I can try to reproduce this error on a simpler example.

**Comment by ncesario-lunarg** [comment] 2021-07-06 19:13
:+1: if it's difficult to "isolate" the code causing the error, would you be able to submit an API trace/replay file?

**Comment by Vincent-P** [comment] 2021-07-06 19:34
Im not sure what kind of file you are expecting, I guess a gfxreconstruct file is ok?
[gfxrecon_capture_trim_trigger_20210706T213038.zip](https://github.com/KhronosGroup/Vulkan-ValidationLayers/files/6772393/gfxrecon_capture_trim_trigger_20210706T213038.zip)

**Comment by jeremyg-lunarg** [comment] 2021-07-06 19:39
gfxreconstruct is great.  The small number of errors you get could be the result of hitting the duplicate message limit, which defaults to 10. I'll give your capture file a try and see if I can figure out what is happening.

**Comment by Vincent-P** [comment] 2021-07-07 16:48
I am able to reproduce the error on a simpler code: https://github.com/Vincent-P/vulkan-sample.
I am creating a descriptor set with the flags mentioned above, containing images from the swapchain and one I created myself.
In the fragment shader I am sampling one image in the descriptor set with a constant index. (3 points to the image I created, there is a yellow background as a result)

I get this error 10 times:
```
Validation Error: [ SYNC-HAZARD-READ_AFTER_WRITE ] Object 0: handle = 0x1a984cf8f60, type = VK_OBJECT_TYPE_IMAGE_VIEW; | MessageID = 0x4cb75b2d | vkCmdDraw: Hazard READ_AFTER_WRITE for VkImageView 0x1a984cf8f60[], in VkCommandBuffer 0x1a9855be160[], and VkPipeline 0x1a985610050[], VkDescriptorSet 0x1a985585340[], type: VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, imageLayout: VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL, binding #0, index 1. Access info (usage: SYNC_FRAGMENT_SHADER_SHADER_STORAGE_READ, prior_usage: SYNC_COLOR_ATTACHMENT_OUTPUT_COLOR_ATTACHMENT_WRITE, write_barriers: 0, command: vkCmdBeginRenderPass, seq_no: 1, reset_no: 1).
```

**Comment by jeremyg-lunarg** [comment] 2021-07-07 19:02
Thanks for the shorter code! I was having to do some hardware swapping to get the trace to run but I can run the shorter program and reproduce the same errors you're getting. Hopefully I'll have  more info for you soon.

**Comment by jeremyg-lunarg** [comment] 2021-07-08 15:20
You are indeed hitting a limitation of how the validation layer handles bindless descriptor sets.  Currently the code is only able to tell  if the entire descriptor set is used, not if individual descriptors are. In the example shader:
```
layout(set = 0, binding = 0) uniform sampler2D global_textures[];
  
layout(location = 0) in vec2 i_uv;
layout(location = 0) out vec4 o_color;
void main()
{
    o_color = vec4(texture(global_textures[3], i_uv).rgb, 1.0);
}
```
Since the array index is a constant we should in theory be able to find that is the only access into the set by more thoroughly parsing the SPIRV.  But more complex cases where the index is computed from other inputs could require even more complexity.   Solving even the simple constant index cases is a large amount of work, so I'm not sure when we'll be able to make progress on removing this type of false positive.

**Comment by ncesario-lunarg** [comment] 2021-07-08 15:49
This seems somewhat related to #1998 (which I'm sporadically working on) as far as shader/SPIRV validation goes. I'll try to keep this in mind when going through the shader runtime validation so we can hopefully handle this case better.

**Comment by Tony-LunarG** [comment] 2021-07-08 16:01
This almost calls for GPU Assisted Synchronization Validation, since that's how we handle those cases in VUID validation.

**Comment by artem-lunarg** [comment] 2023-10-17 09:37
> It isn't clear to me if bindless is supported or not.

No, it's not supported now in syncval.

Closing this as a duplicate. Where are discussing this issue here: https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/3450

Current proposal is to disable syncval validation of dynamic descriptor indexing in order not to get false-positives. The suggested PR is here https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/6605 and it should help with error messages described above.

Longer term solution is to communicate with GPU-AV subsystem to get runtime information.

**Closed by artem-lunarg** 2023-10-17 09:37 UTC
Labels: Synchronization, DescriptorIndexing
