### ISSUE TITLE
Renderdoc capture crashes app

### ISSUE THREAD

**Issue by salamanderrake** [KhronosGroup/Vulkan-ValidationLayers#547] opened 2018-12-26 19:16 UTC
When trying to capture a frame in Renderdoc the application receives the signal SIGSEGV, Segmentation fault. 

Distro: OpenSUSE Tumbleweed
* Linux linux-zo95 4.19.11-1-default #1 SMP PREEMPT Thu Dec 20 09:45:14 UTC 2018 (096f733) x86_64 x86_64 x86_64 GNU/Linux

Clang: 7.0
Vulkan Validation Layers: [here](https://gist.github.com/salamanderrake/fc5b5e2b02c4cb4709794703975b5b0e)
RenderDoc: 1.2

Applications [backtrace](https://gist.github.com/salamanderrake/9e463c8e4bc91f1b08952db6f5a8e494)
RenderDoc diagnostic [log](https://gist.github.com/salamanderrake/0cb344d41e97f4fbdcd2d75021fc9f2b)
Vulkan Info [output](https://gist.github.com/salamanderrake/e5eccd8599774009e35d7118ec8375f1)

Enabled Validation Layer:
* VK_LAYER_LUNARG_standard_validation

**Comment by karl-lunarg** [comment] 2018-12-26 20:14
The fault occurs only when using RenderDoc.
No other validation messages are seen.
Repro app: https://github.com/Overv/VulkanTutorial/blob/master/code/29_multisampling.cpp

**Comment by jzulauf-lunarg** [comment] 2019-01-09 23:38
Am not able to reproduce during a capture, however *loading* a capture of 29_multisampling crashes due to an uninitialized descriptor error (which renderdoc would usually show upon completion of the load).

Is your crash on *capture* or well you attempt to *load capture* ?

**Comment by jzulauf-lunarg** [comment] 2019-01-10 00:01
Given the fix at PR 515. Closing.

**Closed by jzulauf-lunarg** 2019-01-10 00:01 UTC
Labels: bug

**Comment by jzulauf-lunarg** [comment] 2019-01-11 17:43
@salamanderrake also fixed in RenderDoc -- https://github.com/baldurk/renderdoc/issues/1230
