### ISSUE TITLE
Layers report layout violations when relaxed block layout extension is enabled

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-ValidationLayers#275] opened 2018-08-08 17:02 UTC
Originally reported in [LunarXchange](https://vulkan.lunarg.com/issue/view/5b6ac13666315148d1e44936).

SPIRV-Tools `spirv-val` was recently updated to check for conforming uniform block layouts.  The `--relax-block-layout` option can be used to quiet the error messages from intentionally non-conforming blocks.  Good so far.

But the validation layers still report a non-conforming layout even when the `VK_KHR_relaxed_block_layout` extension is active.  I'm not completely certain but it seems that the shader validation steps in the validation layers should also ignore these errors when the extension is enabled.  This could be done by somehow setting the equivalent of `--relax-block-layout` in the library interface to `spirv-val`, if possible,  or some other approach.  I took a quick look and didn't see any special steps taken if the extension is enabled.

Here's the sample shader with the non-conforming layout and notes from the reporter:

```
// This file is cutdown.vert
//
// The following happens with Vulkan SDK 1.1.82.0, but not with Vulkan SDK 1.1.77.0
//
// Run the following:
// glslangValidator -V cutdown.vert
// spirv-val vert.spv
//
// Results in:
// error: line 28: Structure id 8 decorated as Block must follow standard uniform buffer layout rules: member 2 at offset 28 // overlaps previous member ending at offset 31
//   OpFunctionEnd
//
// When running the application (using the non-cutdown shader code) with Vulkan validation
// layers enabled, it also results in errors such as:
//
// ERRR: @[Validation]:  [ UNASSIGNED-CoreValidation-Shader-InconsistentSpirv ] Object: VK_NULL_HANDLE (Type = 0) | SPIR-V module not valid: Structure id 212 decorated as Block must follow standard uniform buffer layout rules: member 2 at offset 28 overlaps previous member ending at offset 31
//   OpFunctionEnd

#version 450 core

layout(set = 0, binding = 1, std140) uniform uniforms {
    float a;
    vec3 b;
    float c;
};

void main() {
}
```

**Comment by chrisforbes** [comment] 2018-08-08 19:37
@karl-lunarg looks like we just need to plumb through the extension state to spirv-tools. @dneto has just done similar work in VulkanCTS.

**Comment by karl-lunarg** [comment] 2018-08-08 21:29
@chrisforbes  Ah, I see that spirv-tools has:
```c
// Records whether or not the validator should relax the rules on block layout.
//
// When relaxed, it will skip checking standard uniform/storage buffer layout.
SPIRV_TOOLS_EXPORT void spvValidatorOptionsSetRelaxBlockLayout(
    spv_validator_options options, bool val);
```
That makes that part pretty easy.

And the extension state is already available in `PreCallValidateCreateShaderModule`, so that looks easy too.  

I see that `VK_KHR_relaxed_block_layout` is promoted into core for 1.1, so it is already on for 1.1.

Since I've come this far, I might as well code this up.

**Comment by chrisforbes** [comment] 2018-08-08 22:38
:+1:

**Comment by karl-lunarg** [comment] 2018-08-09 20:24
Problem was in SPIRV-Tools, and was fixed there.

**Comment by dneto0** [comment] 2018-08-10 14:02
Sorry for the motion in this space.   

I messed up the interpretation of spvValidatorOptionsSetRelaxBlockLayout.  Originally it meant "turn off layout checks", as intended by @antiagainst.   But due the name being so close, I misinterpreted it as "uses VK_KHR_relax_block_layout" and assumed that the validator was taking a shortcut by not checking *any* layout rules at all.  But @antiagainst really did mean it as "skip all checks". 

We've now landed at this:

(See https://github.com/KhronosGroup/SPIRV-Tools/blob/master/include/spirv-tools/libspirv.h#L476 )

```
// Records whether or not the validator should relax the rules on block layout.
//
// When relaxed, it will enable VK_KHR_relaxed_block_layout when validating
// standard uniform/storage block layout.
SPIRV_TOOLS_EXPORT void spvValidatorOptionsSetRelaxBlockLayout(
    spv_validator_options options, bool val);

// Records whether or not the validator should skip validating standard
// uniform/storage block layout.
SPIRV_TOOLS_EXPORT void spvValidatorOptionsSetSkipBlockLayout(
    spv_validator_options options, bool val);
```

**Comment by antiagainst** [comment] 2018-08-21 11:40
Yep, I think having an option to turn layout check off for DX layout would be quite helpful.

**Closed** 2018-08-22 18:07 UTC
