### ISSUE TITLE
Core_validation mishandles attachments that are not touched by any subpass

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-ValidationLayers#17] opened 2018-05-14 01:37 UTC
**Issue by [chrisforbes](https://github.com/chrisforbes) (MIGRATED)**
_Tuesday Feb 28, 2017 at 04:44 GMT_
_Originally opened as https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/1510_

----

Spec says load and store ops are ignored in this case, and the memory contents of the attachment are unmodified. However, we still currently validate everything, and drive the attachment to its finalLayout.

**Comment by jzulauf-lunarg** [comment] 2018-12-13 23:39
This is a duplicate of #300.  After clarification with the WG closed as "works as designed".  See [Clarification on layout transitions for unused attachments](https://github.com/KhronosGroup/Vulkan-Docs/issues/821)

**Closed** 2018-12-13 23:40 UTC
Labels: duplicate
