### ISSUE TITLE
VkImageCopy potentially invalid error

### ISSUE THREAD

**Issue by manas-kulkarni** [KhronosGroup/Vulkan-ValidationLayers#6637] opened 2023-10-06 06:46 UTC
**Environment:**
 - OS: Android
 - GPU and driver version: Adreno 740 512.676.0
 - SDK or header version if building from repo: Latest validation layer release
 - Options enabled (synchronization, best practices, etc.):

**Describe the Issue**

Validation error complains when copying first mip between two 16x8 ASTC_8x8 images
Two code paths copying mip 1
- Always align VkImageCopy::extent to the block extent (8)
  - Validation complains that extent (8) exceeds subresource width (4)
  - ```[VUID-vkCmdCopyImage-srcImage-01728] : Validation Error: [ VUID-vkCmdCopyImage-srcImage-01728 ] Object 0: handle = 0xc0caf50000010b8a, name = name, type = VK_OBJECT_TYPE_IMAGE; | MessageID = 0x6b654496 | vkCmdCopyImage: pRegion[0] extent width (4) must be a multiple of the blocked texture block width (8), or when added to srcOffset.x (0) must equal the image subresource width (8). The Vulkan spec states: If srcImage is a blocked image, then for each element of pRegions, extent.width must be a multiple of the compressed texel block width or (extent.width + srcOffset.x) must equal the width of the specified srcSubresource of srcImage (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkCmdCopyImage-srcImage-01728) (1801798806)```
- Dont align VkImageCopy:;extent to the block extent (8)
  - Validation complains that extent (8) is not a multiple of block width (8)
  - ```[VUID-vkCmdCopyImage-dstOffset-00150] offset [0] + extent height [8] exceeds subResource height[4]```

**Expected behavior**
One of the two paths should be valid otherwise we have an error for all cases

**Comment by ziga-lunarg** [comment] 2023-10-06 10:02
I believe that the validation layer code handles the VUIDs correctly and that this is a problem with the spec, more specifically the VUIDs 00150 and 00151, which make some copies with compressed formats impossible. 

Same issue has been reported multiple times already: #3497, #1946 and #1908

**Comment by manas-kulkarni** [comment] 2023-10-06 12:18
Spec says
```For each element of pRegions, if the sum of srcOffset.x and extent.width does not equal the width of the subresource specified by srcSubresource, extent.width must be a multiple of the [texel block extent width](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdCopyImage.html#formats-compatibility-classes) of the [VkFormat](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkFormat.html) of srcImage```

So for this case, we have ```extent.width (4) + srcOffset.x (0) = width of the subresource (4)```. But validation still throws error that it is not a multiple of the texel block extent width.

**Comment by ziga-lunarg** [comment] 2023-10-06 18:38
To clarify, you have an image with format `VK_FORMAT_ASTC_8x8_UNORM_BLOCK` and it's size is 16x8? What are the parameters of `VkImageCopy`?

In your first message extent width was `4` and image subresource width was `8` so the error message seemed correct.

**Comment by ziga-lunarg** [comment] 2023-10-27 17:30
Closing this as a duplicate of the over issues mentioned above, if you believe there is another bug and can provide more information please reopen.

**Closed by ziga-lunarg** 2023-10-27 17:30 UTC
Labels: Bug
