### ISSUE TITLE
Contention on validation_object_mutex causes poor performance in some applications.

### ISSUE THREAD

**Issue by mattruschnv** [KhronosGroup/Vulkan-ValidationLayers#846] opened 2019-04-05 22:11 UTC
Sample profile of lock taking nearly 70% of CPU cycles:
| - ValidationObject::write_lock	67510 (67.49%)	29 (0.03%)	VkLayer_khronos_validation.dll
| - vulkan_layer_chassis::CmdBindDescriptorSets	21776 (21.77%)	62 (0.06%)	VkLayer_khronos_validation.dll
| - vulkan_layer_chassis::AllocateDescriptorSets	19806 (19.80%)	45 (0.04%)	VkLayer_khronos_validation.dll
| - vulkan_layer_chassis::UpdateDescriptorSets	19526 (19.52%)	68 (0.07%)	VkLayer_khronos_validation.dll
| - vulkan_layer_chassis::CmdDrawIndexed	12432 (12.43%)	40 (0.04%)	VkLayer_khronos_validation.dll
| - CoreChecks::UpdateStateCmdDrawType	3196 (3.19%)	4 (0.00%)	VkLayer_khronos_validation.dll
| - CoreChecks::UpdateDrawState	3143 (3.14%)	37 (0.04%)	VkLayer_khronos_validation.dll
| - vulkan_layer_chassis::CmdBindPipeline	2989 (2.99%)	12 (0.01%)	VkLayer_khronos_validation.dll
| - cvdescriptorset::DescriptorSet::UpdateDrawState	2968 (2.97%)	75 (0.07%)	VkLayer_khronos_validation.dll
| - vulkan_layer_chassis::ResetDescriptorPool	2938 (2.94%)	2 (0.00%)	VkLayer_khronos_validation.dll
| - operator new	2737 (2.74%)	41 (0.04%)	VkLayer_khronos_validation.dll

**Comment by jzulauf-lunarg** [comment] 2019-04-08 20:39
@mattruschnv -- this is consistent with other findings.  I've seen ~50% on Dota time demo.  This is due to the fact that for thread safe access to the validation metadata, each layer is effectively serialized during it's execution.

Which application/content was this profiled on?

**Comment by mattruschnv** [comment] 2019-04-08 21:45
A special build of Strange Brigade, right at the start of gameplay.

**Comment by mattruschnv** [comment] 2019-04-08 23:48
I'm seeing 50% on a different, unreleased title. Running in the main menu with VL disabled is 190 FPS, with VL enabled is ~1 FPS. The validation layer performance is preventing it from being usable with this application.

**Comment by mattruschnv** [comment] 2019-04-08 23:49
Function Name	Total CPU [unit, %]	Self CPU [unit, %]	Module
| - ValidationObject::write_lock	34319 (48.19%)	3 (0.00%)	VkLayer_khronos_validation.dll
| - vulkan_layer_chassis::CmdDrawIndexed	19065 (26.77%)	5 (0.01%)	VkLayer_khronos_validation.dll
| - vulkan_layer_chassis::QueueSubmit	11620 (16.32%)	0 (0.00%)	VkLayer_khronos_validation.dll
| - CoreChecks::ValidateCmdDrawType	11270 (15.83%)	0 (0.00%)	VkLayer_khronos_validation.dll
| - CoreChecks::ValidateCmdBufDrawState	11266 (15.82%)	8 (0.01%)	VkLayer_khronos_validation.dll
| - CoreChecks::PreCallValidateCmdDrawIndexed	11231 (15.77%)	0 (0.00%)	VkLayer_khronos_validation.dll
| - cvdescriptorset::DescriptorSet::ValidateDrawState	11205 (15.73%)	563 (0.79%)	VkLayer_khronos_validation.dll
| - CoreChecks::PostCallRecordQueueSubmit	10545 (14.81%)	0 (0.00%)	VkLayer_khronos_validation.dll
| - CoreChecks::UpdateCmdBufImageLayouts	10494 (14.74%)	107 (0.15%)	VkLayer_khronos_validation.dll
| - CoreChecks::SetGlobalLayout	10163 (14.27%)	10095 (14.18%)	VkLayer_khronos_validation.dll
| - CoreChecks::VerifyImageLayout	9460 (13.28%)	481 (0.68%)	VkLayer_khronos_validation.dll
| - CoreChecks::FindCmdBufLayout	9097 (12.77%)	2224 (3.12%)	VkLayer_khronos_validation.dll

**Comment by jzulauf-lunarg** [comment] 2019-04-08 23:52
@mattruschnv -- other profiling details could be of help.  Effectively, every cycle you pull out of a heavyweight subtree of a `*CallValidation*` or `*CallRecord*` path reduces wait time as a secondary benefit. Also, are you pulling from tip?  There was a recent (on one specific app) 6% perf gain recently committed.

**Comment by jzulauf-lunarg** [comment] 2019-04-08 23:54
CoreChecks::SetGlobalLayout -- is the parallel to the path I just optimized...

**Comment by mattruschnv** [comment] 2019-04-08 23:55
I'm probably a week out of date. What other profiling details would you like? I was able to get 5% locally by rearranging some structures to have better alignment / reduce padding.

**Comment by jzulauf-lunarg** [comment] 2019-04-08 23:58
@mattruschnv -- my request for details lost a race condition against your details :) 

https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/806 -- is the perf change.  Two parts, 1) faster command buffer scope image layout tracking, 2) Lazier updates of the object cross-referencing.

**Comment by mark-lunarg** [comment] 2019-04-09 15:59
@mattruschnv, just getting to this task as part of the layer consolidation.  For sure, we want to make sure that glomming all the layers together is no worse for performance than back when they were all separate layers.  Hopefully I can use DOTA2, but would the standard version of Strange Brigade work for us or is there something about your build that wouldn't allow us to duplicate your results?

**Comment by mattruschnv** [comment] 2019-04-09 18:06
The standard version of Strange Brigade should work fine for performance testing. I'll try to find a released application that exhibits the 190 FPS -> 1 FPS slowdown.

**Comment by mark-lunarg** [comment] 2019-04-09 18:11
Yeah, I'm super-curious about that one!

**Comment by mattruschnv** [comment] 2019-04-09 23:18
The optimization to SetGlobalLayout took the worst case from 1 FPS to 6-7 FPS. I'm doing more profiling now.

**Comment by mattruschnv** [comment] 2019-04-10 18:15
Has anyone tried using mutexes to guard the individual data structures rather than using one per layer? If not, would anyone object if I were to try?

**Comment by jzulauf-lunarg** [comment] 2019-04-10 19:08
That's one of a couple approaches we've kicked around.  If you wanted to protected the various structures, then you'd have to at least change the pointer contents to shared pointers, however, you then have the potential for unsafe access of the records retrieved, so you might have to lock per  entry as well.

Another approach we've considered is implementing read/writer locks where the Validate entry points would (ideally) only be readers, and the only the state update sections of Record entry points would have to be writers.

Probably would be interested in seeing a least a sketch of your approach prior to having you do a bunch of work.

**Comment by jeffbolznv** [comment] 2019-04-10 19:28
I'm not familiar with all the structures the validation layers maintain. But is it possible to organize them so that they are all associated with the appropriate Vulkan object, and then rely on the "externsync" behavior requirements of the spec? There would probably be a couple exceptions to this, like a global handle->object hashmap that would require simultaneous access (reader/writer might work here).

**Comment by mark-lunarg** [comment] 2019-04-10 19:44
We're just getting into an effort to characterize the perf issues, and everything is on the table at this point.

**Comment by jzulauf-lunarg** [comment] 2019-04-10 19:51
@jeffbolznv  -- that's certainly a possibility for some accesses.  Though for something like BeginRenderPass, only the commandBuffer and the commandPool are externally synchronized, while behind the scenes the render pass, frame buffer, image views, and images that underlying them are all being inspected.

But as Mark says, "everything is on the table at this point"..

**Comment by jeffbolznv** [comment] 2019-04-10 22:41
> while behind the scenes the render pass, frame buffer, image views, and images that underlying them are all being inspected

Inspected is fine. 99% of the time that parameters are not externsync, it's because they're treated as read-only by the command. And usually those objects (like render pass, framebuffer, image view, image) can't be modified after they're created.

**Comment by mark-lunarg** [comment] 2019-04-10 23:08
But their state might be updated.  I suppose it might be possible to separate much of the inter-object state from the stuff that shouldn't change.  Teasing those apart will be a challenge, and maybe a perf-hit in its own right, but we can take a look.

**Comment by mattruschnv** [comment] 2019-04-10 23:38
Is c++ 14 available on all relevant build targets? Switching some of them over to shared_lock, if possible, might not be too difficult to try. That being said, I'm not sure how to enforce all of the layers to be read only for the relevant entry points.

**Comment by jzulauf-lunarg** [comment] 2019-04-10 23:42
I don't believe we can go to '14.  For enforcement I was thinking of using method const-ness as a first pass.  As entry points become const clean, use reader locks for them.  But that's just one possible approach.

**Comment by jzulauf-lunarg** [comment] 2019-04-10 23:51
@jeffbolznv ... but they can be deleted.  They shouldn't be while they're referenced... but they can. (and there's a whole stack of unstated "is the underlying content needed by the referenced handle still valid?" validity requirements -- but that a long side discussion)  

Thus the need to shared_ptr-ize  the "mostly immutable" data (only mostly because of the "in-use" and cross-reference updates).  Also the current cross referencing is done in the handle domain, and that would have to be converted to work directly with the (likely) shared pointers.  (Something I've referred to as "de-handling" -- and it would save a few cycles spent in the hash functions and maps.)

**Comment by jeffbolznv** [comment] 2019-04-11 02:54
I thought the object_lifetime layer checks that the object initially exists and tracks whether a deletion occurs while in use, and other layers don't have to redundantly guarantee that the objects stay alive?

**Comment by jzulauf-lunarg** [comment] 2019-04-11 15:02
@jeffbolznv  -- it only does shallow tracking.  It looks at the handles referenced directly by a command.  It can check that the image view referenced in a descriptor update exists, but doesn't have the state to know that a *image* or *memory* objects backing that image view is valid.  To the extent this is covered, it's done in core validation.  

BTW, the class of valid usage statements this would imply would be large, and in the words of one wag "are explicitly omitted" from the spec.  So the "must be a valid ... handle" can/should be used for the deep validity checking, but their omission can lead to a sort of "out of sight/out of mind".

**Comment by mark-lunarg** [comment] 2019-04-11 16:03
To be clear, "lock taking nearly 70% of CPU cycles" is not a performance regression or behavior change,  and we are counting on a performance increase using the new layer.  What is different for the khronos layer is that the locks are grabbed using a helper function instead of being directly held by lower-level validation routines.  This is probably clear to everyone but I'm hoping to avoid misconceptions.  Of course, the new layer and the old layers use a much-too-large synchronization hammer, and this remains to be addressed.

**Comment by mattruschnv** [comment] 2019-04-11 16:33
Correct, I never meant to imply a delta when I opened this issue. However, it is severely limiting the usefulness of the validation layers with respect to games, so I believe it is something that should be prioritized. Fine tuning the synchronization (increased number of mutexes / shared mutexes and limit the time locks are held) is the clearest path I can see through this. It will, unfortunately, add complexity to the code.

**Comment by mark-lunarg** [comment] 2019-04-11 16:56
:+1:

**Comment by JasperNV** [comment] 2019-05-02 19:57
Currently, each layer takes its own lock around commands three separate times per dispatch, and uses virtual functions to do so. Would it make sense to instead generate a single unified dispatch like this:

```cpp
bool lock_needed = parameter_validation_enabled || core_validation_enabled || buffer_validation_enabled || ...;
{
    if (lock_needed)
        lock();
    parameter_validation->PreCallValidateFunction(...);
    core_validation->PreCallValidateFunction(...);
    buffer_validation->PreCallValidateFunction(...);
    if (lock_needed)
        unlock();
}
Function();
{
    if (lock_needed)
        lock();
     parameter_validation->PostCallRecordFunction();
     ...
}
```

This skips the vcall overhead and would severely reduce the time spent in locking/unlocking mutexes.

**Comment by mark-lunarg** [comment] 2019-05-02 20:25
@JasperNV, I don't have numbers on the lock/unlock time, so I don't know offhand how much of a win we'd get.  
A couple of points on the locks -- we could certainly code-gen the chassis to do something like this, but some of the validation objects need locks and some don't. For instance, parameter validation doesn't, nor does threading, but that's easily dealt with.  OTOH, currently each validation object has its own lock, so a thread goofing around in object_tracker won't block a thread kicking around in core validation.  In this model they'd share a lock and would hold it longer.  
However, the best thing to do would probably be to quickly modify the chassis.cpp generation to do this and see if it nets anything -- I didn't notice any significant deltas during the prototyping, but if it turned out to be so it'd be an easy change.

**Comment by jzulauf-lunarg** [comment] 2019-05-02 21:33
I believe each layer object also has it's *own* lock, s.t. more than one thread can execute on different layers at the same time.

**Comment by JasperNV** [comment] 2019-05-02 22:08
Ahh, sorry, I misread the code. I thought that it was still chaining to the parent validation object so all locks were basically held at the same time. Glad to see that's not the case anymore.

**Comment by mark-lunarg** [comment] 2019-06-20 20:39
This will be rolled into the perf tracking issue, #1001.

**Closed by mark-lunarg** 2019-06-20 20:39 UTC
Labels: performance, triaged
