### ISSUE TITLE
False positive with semaphore lifetime tracking

### ISSUE THREAD

**Issue by ShabbyX** [KhronosGroup/Vulkan-ValidationLayers#5568] opened 2023-04-04 02:12 UTC
Since 27ba73e03b844b74c31fdedfa83b68b605c60cbf, ANGLE's been hitting a validation error saying that a semaphore being destroyed is in use by the command buffers.

I finally got around to looking into it, and the failure is coming from when ANGLE is destroying semaphores used for `vkQueuePresentKHR`. This is happening on surface destruction after a call to `vkQueueWaitIdle`. Additionally, if `VK_EXT_swapchain_maintenance1` is supported, the present fences are waited on, if any.

On the platform I'm hitting this, `VK_EXT_swapchain_maintenance1` is not supported. However, `vkQueueWaitIdle` is supposed to have been enough to destroy the semaphores (because there is no alternative). This might be a bug, or a race condition with the above change?

Context: anglebug.com/7729

Need to unsuppress `VUID-vkDestroySemaphore-semaphore-01137` in RendererVk.cpp before running the test.

**Comment by jeremyg-lunarg** [comment] 2023-05-05 19:30
This is Issue https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/12   I suspect that the commit mentioned above changed timing so that this problem started happening in ANGLE.

Playing with the tests on a platform that doesn't provide `VK_EXT_swapchain_maintenance1` I saw the following:
* vkQueuePresentKHR(... semaphore_a)
* vkAcquireNextImageKHR(..., fence_b)
* a bunch of queue submissions
* vkGetFenceStatus(fence_b)
* vkDestroySemaphore(semaphore_a)
* VUID-vkDestroySemaphore-semaphore-01137

I do NOT see ANGLE calling vkQueueWaitIdle() in the tests that hit this error.  I agree that a call to that function should prevent this error. But I also think the call sequence I observed should also not trigger the error.

**Comment by jeremyg-lunarg** [comment] 2023-05-05 19:33
FYI @artem-lunarg

**Comment by ShabbyX** [comment] 2023-05-08 00:25
ANGLE used to call `vkQueueWaitIdle()`, but now it's just checking the fence of the last submission and waits on it if it's not ready. In the sequence above, the fence was already signaled so there's no wait.

> But I also think the call sequence I observed should also not trigger the error.
Agreed, it's supposed to be the same as `vkQueueWaitIdle()`.

**Comment by artem-lunarg** [comment] 2023-08-14 21:48
UPDATE: managed to reproduce `VUID-vkDestroySemaphore-semaphore-01137` in these tests:
`dEQP-EGL.functional.swap_buffers_with_damage.no_resize.render`
`dEQP-EGL.functional.swap_buffers_with_damage.no_resize.clear_clear`

**Comment by artem-lunarg** [comment] 2023-08-18 21:18
@ShabbyX the api dump shows that the tests often initiate resource deletion immediately after the last `vkQueuePresentKHR`, without `vkQueueWaitIdle` or fence status polling. The error is reported for the semaphore that was used in the last `vkQueuePresentKHR`. I think that's expected behavior in this case. The queue operation inserted by `vkQueuePresentKHR` that inspects the wait semaphore might not have started yet after `vkQueuePresentKHR` returns, so deleting semaphore is unsafe.

I have attached API dump for `dEQP-EGL.functional.swap_buffers_with_damage.no_resize.render` test:

[apidump_semaphore_ea7170000000031.txt](https://github.com/KhronosGroup/Vulkan-ValidationLayers/files/12383875/apidump_semaphore_ea7170000000031.txt)

I saw you participated in the discussions related to present semaphore deletion and as I understand without  `VK_EXT_swapchain_maintenance1` it's tricky to get it right and `vkQueueWaitIdle` is not a perfect solution. I think we can still support `vkQueueWaitIdle` to mark that the present semaphore is not in use anymore since many apps use this method, and drivers probably aware of this.

I'll check more tests if they generate 01137 in other scenarios and also will try to reproduce Jeremy's use case.

**Comment by artem-lunarg** [comment] 2023-08-19 17:50
@jeremyg-lunarg I can reproduce your test case. It looks like it's a valid behavior. Image acquire does not happen on the queue and waiting for acquire fence does not guarantee that previous present operation (which happens on the queue) finished. 

Strictly speaking, waiting on the queue also does not guarantee that present operation finished because *present queue batch* is not included in the synchronization scope for *fence signaling order* (and queue wait is equivalent to wait on the fence). I believe we still assume that `vkQueueWaitIdle` is a *practical* clean up solution for no-VK_EXT_swapchain_maintenance1 apps. Adding `vkQueueWaitIdle` in the end of the suggested test, to ensure (kind of) that present request is finished, allows the test to pass.

Some references for documentation purposes :
That vkQueuePresentKHR was removed from signal operation synchronization scope:
https://github.com/KhronosGroup/Vulkan-Docs/issues/1150#issuecomment-662959159

One suggestion to return back it to submission order so it can be picked up by QueueWaitIdle (did not happen though):
https://github.com/KhronosGroup/Vulkan-Docs/issues/152#issuecomment-1347426688
Also entire issue 152 is a very informative discussion.

**Comment by artem-lunarg** [comment] 2023-08-28 11:21
I run a bunch of test sessions on the latest angle and used different versions of vvl starting from the latest code, also tried the commit mentioned in the description of this ticket https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/27ba73e03b844b74c31fdedfa83b68b605c60cbf, a commit just before that change https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/19314aa5901ce13273adac4fa630239e37544dfa, and in addition tested subsequent fix https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/45e2d1fc81142ef6c903fc10bae3c86f821242e6 and commits around it.

Based on this I can confirm that all these vvl versions (including the latest one) report the same issue that `vkQueuePresent` is followed by `vkDestroySemaphore` (for the semaphore that present is waiting on) without intermediate `vkGetFenceStatus` or queue idle wait. Also I'd like to highlight this separately: this behavior was not introduced in https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/27ba73e03b844b74c31fdedfa83b68b605c60cbf, and it is reproduceable before it, although the timings might indeed be different.

For some runs, angle inserts `vkGetFenceStatus` between `vkQueuePresent` and `vkDestroySemaphore` in that cases the error is not reported. But for the other runs we have `vkDestroySemaphore` after `vkQueuePresent` without intermediaries. VVL expects queue/fence wait after present since it's the *practical* pre-`VK_EXT_swapchain_maintenance1` way to signal intent to wait for the present during the application exit sequence.

The attached api dumps are from the latest vvl and also from the vvl commit before `27ba73e`. For each vvl version, two api dumps are provided: one for a successful run that demonstrates that `vkGetFenceStatus` was called, and another one for the test failure. 

In all test sessions, all failures are related to the usages of the semaphore in the *last* `vkQueuePresentKHR` call, after which follows application clean up sequence that destroys resources.

[api_latest_vvl_(8366ffa)_error_and_no_fence_check.txt](https://github.com/KhronosGroup/Vulkan-ValidationLayers/files/12453573/api_latest_vvl_.8366ffa._error_and_no_fence_check.txt)
[api_latest_vvl_(8366ffa)_no_error_and_there_is_fence_check.txt](https://github.com/KhronosGroup/Vulkan-ValidationLayers/files/12453575/api_latest_vvl_.8366ffa._no_error_and_there_is_fence_check.txt)
[apidump_19314aa_(before_27ba73e)_no_error_and_there_is_fence_check.txt](https://github.com/KhronosGroup/Vulkan-ValidationLayers/files/12453576/apidump_19314aa_.before_27ba73e._no_error_and_there_is_fence_check.txt)
[apidump_19314aa_(before_27ba73e)_error_and_no_fence_check.txt](https://github.com/KhronosGroup/Vulkan-ValidationLayers/files/12453577/apidump_19314aa_.before_27ba73e._error_and_no_fence_check.txt)

The fix suggestion is to ensure the fence status is always checked after the last `vkQueuePresent` and before the resource clean up sequence (or to call `vkQueueWaitIdle` earlier). I'm not sure why in some case angle does not do this, maybe because it is mostly concerned with submit status, and the last `vkQueueSubmit`'s fence check reported READY status. But even if submit is ready we still can't remove semaphore immediately after `vkQueuePresent`, because present operation might still be pending and did not test wait semaphore yet (even if we now it's READY due to after-submit test, present still need to have it alive to read its status).

**Comment by artem-lunarg** [comment] 2023-08-28 11:46
Closing this as not a VVL bug. 

If there are scenarios that `01137` is reported for the use cases when `vkQueuePresentKHR` is followed by a fence/queue check, that would be a VVL bug.

So far, all verified `01137` errors is an expected behavior when the semaphore is being destroyed while there is a pending queue operation (present) that references this semaphore.

**Closed by artem-lunarg** 2023-08-28 11:46 UTC
Labels: Bug, Synchronization, WSI
