### ISSUE TITLE
vkCmdDecodeVideoKHR-pDecodeInfo-07149: Race to check the test case

### ISSUE THREAD

**Issue by dabrain34** [KhronosGroup/Vulkan-ValidationLayers#5190] opened 2023-01-30 14:02 UTC
**Environment:**
 - OS: Linux
 - GPU: NVidia
 - SDK or header version if building from repo: main
 - Options enabled (synchronization, best practices, etc.):

**Describe the Issue**

During a video decode command, the Validation layer spawns the error vkCmdDecodeVideoKHR-pDecodeInfo-07149 but the test is done in PreCallValidateCmdDecodeVideoKHR when the bound_video_picture_resources array is filled up in PostCallRecordCmdDecodeVideoKHR

**Expected behavior**

To have the bound_video_picture_resources filled up before the test.

**Valid Usage ID**
vkCmdDecodeVideoKHR-pDecodeInfo-07149

**Additional context**

Issue  reproducible with vk-gl-cts

**Comment by dabrain34** [comment] 2023-01-30 14:09
May I understand that the pSetupReferenceSlot shall be NULL on first frame ?

**Comment by dabrain34** [comment] 2023-01-31 11:28
@aqnuep ^

**Comment by aqnuep** [comment] 2023-01-31 20:54
The bound_video_picture_resources (which tracks the reference picture resources bound for the current video scope) are filled in PostCallRecord**CmdBeginVideoCodingKHR**, not in PostCallRecordCmdDecodeVideoKHR, as the issue suggest.

This is the expected behavior as decode commands are not allowed to refer to any picture resources as reference pictures if they weren't bound at BeginVideoCoding-time.

It seems that you forgot to specify the video picture resource you intend to set up in the current video coding scope (by specifying it in pSetupReferenceSlot) in VkVideoBeginCodingInfoKHR::pReferenceSlots with a slotIndex == -1, indicating that the picture is not associated with any DPB slot at begin-time.

This is probably also the reason why you assume that pSetupReferenceSlot needs to be NULL on the first frame, which is incorrect.

Please refer to the specification describing the behavior of vkCmdBeginVideoCoding, in particular how bound reference picture resources work, and the description of VUID 07149, which states the following:

> If pDecodeInfo->pSetupReferenceSlot is not `NULL`, then pDecodeInfo->pSetupReferenceSlot->pPictureResource must match one of the bound reference picture resources

In any case, the validation code here works as intended.

**Comment by aqnuep** [comment] 2024-03-01 14:24
Closing as the VVL behavior is as expected by the spec.

**Closed by aqnuep** 2024-03-01 14:24 UTC
Labels: Video
