### ISSUE TITLE
message_id_filter only works with hex message IDs

### ISSUE THREAD

**Issue by adevaykin** [KhronosGroup/Vulkan-ValidationLayers#2378] opened 2020-12-08 10:41 UTC
**Describe the Issue**
`message_id_filter` documentation says it should be a comma-delimited set of VUIDs, decimal or hexadecimal validation message IDs that should be muted. In practice this is not the case - I only managed to mute messages by their hexadecimal IDs - neither strings nor decimal IDs worked.

**Environment:**
 - OS: Windows 10
 - GPU: Nvidia GTX 1070
 - SDK or header version if building from repo: 1.2.154.1
 - Options enabled (synchronization, best practices, etc.):

**Comment by mark-lunarg** [comment] 2020-12-08 14:34
@adevaykin, would you please share the lines from your `vk_layer_settings.txt` file that are not working?  Thanks!

**Comment by mark-lunarg** [comment] 2020-12-15 17:20
@adevaykin, we've so far been unable to reproduce this behavior so I'm going to temporarily close this issue.  If you get a chance to share the issue repro details here, I will reopen it and look at it right away -- thanks!

**Comment by adevaykin** [comment] 2020-12-16 08:12
@mark-lunarg sorry, I totally forgot to provide an example. This particular configuration has had no effect on messages:
```khronos_validation.message_id_filter = "VUID-vkBindBufferMemory-memory-02726","VUID-vkBindImageMemory-memory-02728"```

Thanks!

**Comment by mark-lunarg** [comment] 2020-12-16 14:57
@adevaykin, thank you!  Will take another look today.

**Closed** 2020-12-16 20:50 UTC

**Comment by mark-lunarg** [comment] 2020-12-16 20:52
@adevaykin, hoping that PR took care of the problem but please let us know if it persists.  We have a void in our testing around the `vk_layer_settings.txt` file and we appreciate the reports!

**Comment by adevaykin** [comment] 2020-12-16 20:56
@mark-lunarg thank you! Can't believe I didn't try without quotes... :)

**Comment by mark-lunarg** [comment] 2020-12-16 21:07
But we said to use them in the doc!  Ah well.
