### ISSUE TITLE
Incorrect `PRESENT_AFTER_WRITE` after signalling with `ALL_COMMANDS_BIT`

### ISSUE THREAD

**Issue by glebov-andrey** [KhronosGroup/Vulkan-ValidationLayers#7479] opened 2024-02-08 14:04 UTC
**Environment:**
 - SDK or header version if building from repo: current `main` (9b64c5a78c16003de0ec8cd3b429023073a9128b)
 - Options enabled (synchronization, best practices, etc.): synchronization (with queue submit validation)

**Describe the Issue**

With queue submit synchronization validation enabled, I'm getting a `PRESENT_AFTER_WRITE` error which appears to be incorrect.
Here's the sequence of commands:
- draw to swapchain image
- ```
  vkCmdPipelineBarrier2:
    srcStageMask  VK_PIPELINE_STAGE_2_COLOR_ATTACHMENT_OUTPUT_BIT
    srcAccessMask VK_ACCESS_2_COLOR_ATTACHMENT_WRITE_BIT
    dstStageMask  VK_PIPELINE_STAGE_2_NONE
    dstAccessMask VK_ACCESS_2_NONE
    oldLayout     VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL
    newLayout     VK_IMAGE_LAYOUT_PRESENT_SRC_KHR
  ```
- ```
  vkQueueSubmit2:
    ...
    VkSemaphoreSubmitInfo:
      stageMask VK_PIPELINE_STAGE_2_ALL_COMMANDS_BIT
  ```
- `vkQueuePresentKHR`: wait for signaled semaphore

**Expected behavior**

As discussed here (https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7024#issuecomment-1831517932) `ALL_COMMANDS` should be enough to synchronize the layout transition with the semaphore signal operation. Assuming that's true, this error should not occur.

**Additional context**

This looks similar to part of #6177 but in that case the semaphore signal stage mask was `VK_PIPELINE_STAGE_2_COLOR_ATTACHMENT_OUTPUT_BIT`.

<details>
<summary>Full validation error</summary>

```
Validation Error: [ SYNC-HAZARD-PRESENT-AFTER-WRITE ] Object 0: handle = 0x56498585ce20, name = Graphics queue, type = VK_OBJECT_TYPE_QUEUE; | MessageID = 0xe17ab4ae | vkQueuePresentKHR():  Hazard PRESENT_AFTER_WRITE for present pSwapchains[0] , swapchain VkSwapchainKHR 0x9638f80000000036[], image index 0 VkImage 0x2723ba0000000037[], Access info (usage: SYNC_PRESENT_ENGINE_SYNCVAL_PRESENT_PRESENTED_SYNCVAL, prior_usage: SYNC_IMAGE_LAYOUT_TRANSITION, write_barriers: 0, queue: VkQueue 0x56498585ce20[Graphics queue], submit: 12, batch: 0, batch_tag: 336, command: vkCmdPipelineBarrier2, command_buffer: VkCommandBuffer 0x7fe1d899bae0[], seq_no: 5, VkImage 0x2723ba0000000037[], reset_no: 1).
```

</details>

**Comment by artem-lunarg** [comment] 2024-02-08 14:54
@glebov-andrey  Did you get this error previously with submit synchronization enabled?
Recently submit synchronization was enabled by default and I wonder if it hits your workload the first time.

**Comment by artem-lunarg** [comment] 2024-02-08 14:56
Recently I also fixed bug that could lead to incorrect synchronization with ALL_COMMANDS https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7465, but it looks you tested with today's code, so it should be a submit synchronization issue.

**Comment by glebov-andrey** [comment] 2024-02-08 15:04
@artem-lunarg This error is specific to queue submit validation. If I explicitly disable it via the environment then there are no errors.
Yes, I specifically pulled the latest code today.

**Comment by artem-lunarg** [comment] 2024-02-08 15:14
Thanks, one more question to be sure I understand this. Did you run with submit validation previously and it worked for you, or do you think it was broken recently? People started reporting the issues recently because we enabled submit validation by default in the latest sdk and some reports detect issues that were always present. I'm trying to understand it could be your use case or it worked for you before and got broken recently.

**Comment by glebov-andrey** [comment] 2024-02-08 15:22
@artem-lunarg I just checked with our "stable" version of VVL (d104a0ee52e8b592635ec44b040813160f18068c from 2023-12-08) and the same error occurs. Other than that it's hard to tell because we haven't been using queue submit validation (because of #7024) - I'm currently working on figuring out which errors are real and which are false positives.

**Comment by artem-lunarg** [comment] 2024-02-08 15:34
Okay, I guess this way always they case. We are actively working on fixing submit validation issues, meanwhile you might disable submit validation in vkconfig or programmatically (more details on how to do this: https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7457#issuecomment-1930462155)

**Comment by artem-lunarg** [comment] 2024-02-09 01:45
@glebov-andrey  There is this fix https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7480, it should cover at least handling ALL_COMMANDS on the signal side. If you have a chance to try it please let me know if it helps. Still, I did not check if something is needed on the wait site of Present, so there is possibility that fix alone is not enough.

**Comment by glebov-andrey** [comment] 2024-02-09 06:47
@artem-lunarg Thanks! That fixes the issue, at least for my `PRESENT_AFTER_WRITE` case. It also seems to have fixed some of the other inter-queue issues.

Looking at the code changes I was wondering though, shouldn't the `ALL_COMMANDS` also include `SYNC_QUEUE_FAMILY_OWNERSHIP_TRANSFER_BIT` (not that it's used anywhere yet)? Also maybe the change should be part of `sync_utils::ExpandPipelineStages()`?

**Comment by glebov-andrey** [comment] 2024-02-09 07:31
Regarding the inter-queue errors I mentioned in the previous comment:

Previously they made some sense (considering that timeline semaphores aren't fully supported):
```Validation Error: [ SYNC-HAZARD-WRITE-AFTER-WRITE ] Object 0: handle = 0x563efc384c00, name = Graphics queue, type = VK_OBJECT_TYPE_QUEUE; | MessageID = 0x5c0ec5d6 | vkQueueSubmit2():  Hazard WRITE_AFTER_WRITE for entry 0, VkCommandBuffer 0x563f017cfdd0[], Submitted access info (submitted_usage: SYNC_IMAGE_LAYOUT_TRANSITION, command: vkCmdPipelineBarrier2, seq_no: 1, ...<RESOURCE LIST>..., reset_no: 1, debug_region: async compute tasks). Access info (prior_usage: SYNC_IMAGE_LAYOUT_TRANSITION, write_barriers: 0, queue: VkQueue 0x563efc384ea0[Transfer queue], submit: 1, batch: 0, batch_tag: 17, command: vkCmdPipelineBarrier2, command_buffer: VkCommandBuffer 0x563f00274aa0[], seq_no: 17, ...<RESOURCE LIST>..., reset_no: 3).```
(note that `write_barriers: 0`).

With #7480 applied `write_barriers` is now a list of what seems like all possible flags:
```
SYNC_DRAW_INDIRECT_INDIRECT_COMMAND_READ|SYNC_DRAW_INDIRECT_TRANSFORM_FEEDBACK_COUNTER_READ_EXT|SYNC_VERTEX_SHADER_ACCELERATION_STRUCTURE_READ|SYNC_VERTEX_SHADER_DESCRIPTOR_BUFFER_READ_EXT|SYNC_VERTEX_SHADER_SHADER_BINDING_TABLE_READ|SYNC_VERTEX_SHADER_SHADER_SAMPLED_READ|SYNC_VERTEX_SHADER_SHADER_STORAGE_READ|SYNC_VERTEX_SHADER_SHADER_STORAGE_WRITE|SYNC_VERTEX_SHADER_UNIFORM_READ|SYNC_TESSELLATION_CONTROL_SHADER_ACCELERATION_STRUCTURE_READ|SYNC_TESSELLATION_CONTROL_SHADER_DESCRIPTOR_BUFFER_READ_EXT|SYNC_TESSELLATION_CONTROL_SHADER_SHADER_BINDING_TABLE_READ|SYNC_TESSELLATION_CONTROL_SHADER_SHADER_SAMPLED_READ|SYNC_TESSELLATION_CONTROL_SHADER_SHADER_STORAGE_READ|SYNC_TESSELLATION_CONTROL_SHADER_SHADER_STORAGE_WRITE|SYNC_TESSELLATION_CONTROL_SHADER_UNIFORM_READ|SYNC_TESSELLATION_EVALUATION_SHADER_ACCELERATION_STRUCTURE_READ|SYNC_TESSELLATION_EVALUATION_SHADER_DESCRIPTOR_BUFFER_READ_EXT|SYNC_TESSELLATION_EVALUATION_SHADER_SHADER_BINDING_TABLE_READ|SYNC_TESSELLATION_EVALUATION_SHADER_SHADER_SAMPLED_READ|SYNC_TESSELLATION_EVALUATION_SHADER_SHADER_STORAGE_READ|SYNC_TESSELLATION_EVALUATION_SHADER_SHADER_STORAGE_WRITE|SYNC_TESSELLATION_EVALUATION_SHADER_UNIFORM_READ|SYNC_GEOMETRY_SHADER_ACCELERATION_STRUCTURE_READ|SYNC_GEOMETRY_SHADER_DESCRIPTOR_BUFFER_READ_EXT|SYNC_GEOMETRY_SHADER_SHADER_BINDING_TABLE_READ|SYNC_GEOMETRY_SHADER_SHADER_SAMPLED_READ|SYNC_GEOMETRY_SHADER_SHADER_STORAGE_READ|SYNC_GEOMETRY_SHADER_SHADER_STORAGE_WRITE|SYNC_GEOMETRY_SHADER_UNIFORM_READ|SYNC_FRAGMENT_SHADER_ACCELERATION_STRUCTURE_READ|SYNC_FRAGMENT_SHADER_COLOR_ATTACHMENT_READ|SYNC_FRAGMENT_SHADER_DEPTH_STENCIL_ATTACHMENT_READ|SYNC_FRAGMENT_SHADER_DESCRIPTOR_BUFFER_READ_EXT|SYNC_FRAGMENT_SHADER_INPUT_ATTACHMENT_READ|SYNC_FRAGMENT_SHADER_SHADER_BINDING_TABLE_READ|SYNC_FRAGMENT_SHADER_SHADER_SAMPLED_READ|SYNC_FRAGMENT_SHADER_SHADER_STORAGE_READ|SYNC_FRAGMENT_SHADER_SHADER_STORAGE_WRITE|SYNC_FRAGMENT_SHADER_UNIFORM_READ|SYNC_EARLY_FRAGMENT_TESTS_DEPTH_STENCIL_ATTACHMENT_READ|SYNC_EARLY_FRAGMENT_TESTS_DEPTH_STENCIL_ATTACHMENT_WRITE|SYNC_LATE_FRAGMENT_TESTS_DEPTH_STENCIL_ATTACHMENT_READ|SYNC_LATE_FRAGMENT_TESTS_DEPTH_STENCIL_ATTACHMENT_WRITE|SYNC_COLOR_ATTACHMENT_OUTPUT_COLOR_ATTACHMENT_READ|SYNC_COLOR_ATTACHMENT_OUTPUT_COLOR_ATTACHMENT_READ_NONCOHERENT_EXT|SYNC_COLOR_ATTACHMENT_OUTPUT_COLOR_ATTACHMENT_WRITE|SYNC_COMPUTE_SHADER_ACCELERATION_STRUCTURE_READ|SYNC_COMPUTE_SHADER_DESCRIPTOR_BUFFER_READ_EXT|SYNC_COMPUTE_SHADER_SHADER_BINDING_TABLE_READ|SYNC_COMPUTE_SHADER_SHADER_SAMPLED_READ|SYNC_COMPUTE_SHADER_SHADER_STORAGE_READ|SYNC_COMPUTE_SHADER_SHADER_STORAGE_WRITE|SYNC_COMPUTE_SHADER_UNIFORM_READ|SYNC_HOST_HOST_READ|SYNC_HOST_HOST_WRITE|SYNC_COMMAND_PREPROCESS_NV_COMMAND_PREPROCESS_READ_NV|SYNC_COMMAND_PREPROCESS_NV_COMMAND_PREPROCESS_WRITE_NV|SYNC_CONDITIONAL_RENDERING_EXT_CONDITIONAL_RENDERING_READ_EXT|SYNC_TASK_SHADER_EXT_ACCELERATION_STRUCTURE_READ|SYNC_TASK_SHADER_EXT_DESCRIPTOR_BUFFER_READ_EXT|SYNC_TASK_SHADER_EXT_SHADER_BINDING_TABLE_READ|SYNC_TASK_SHADER_EXT_SHADER_SAMPLED_READ|SYNC_TASK_SHADER_EXT_SHADER_STORAGE_READ|SYNC_TASK_SHADER_EXT_SHADER_STORAGE_WRITE|SYNC_TASK_SHADER_EXT_UNIFORM_READ|SYNC_MESH_SHADER_EXT_ACCELERATION_STRUCTURE_READ|SYNC_MESH_SHADER_EXT_DESCRIPTOR_BUFFER_READ_EXT|SYNC_MESH_SHADER_EXT_SHADER_BINDING_TABLE_READ|SYNC_MESH_SHADER_EXT_SHADER_SAMPLED_READ|SYNC_MESH_SHADER_EXT_SHADER_STORAGE_READ|SYNC_MESH_SHADER_EXT_SHADER_STORAGE_WRITE|SYNC_MESH_SHADER_EXT_UNIFORM_READ|SYNC_RAY_TRACING_SHADER_ACCELERATION_STRUCTURE_READ|SYNC_RAY_TRACING_SHADER_DESCRIPTOR_BUFFER_READ_EXT|SYNC_RAY_TRACING_SHADER_SHADER_BINDING_TABLE_READ|SYNC_RAY_TRACING_SHADER_SHADER_SAMPLED_READ|SYNC_RAY_TRACING_SHADER_SHADER_STORAGE_READ|SYNC_RAY_TRACING_SHADER_SHADER_STORAGE_WRITE|SYNC_RAY_TRACING_SHADER_UNIFORM_READ|SYNC_FRAGMENT_SHADING_RATE_ATTACHMENT_FRAGMENT_SHADING_RATE_ATTACHMENT_READ|SYNC_FRAGMENT_DENSITY_PROCESS_EXT_FRAGMENT_DENSITY_MAP_READ_EXT|SYNC_TRANSFORM_FEEDBACK_EXT_TRANSFORM_FEEDBACK_COUNTER_READ_EXT|SYNC_TRANSFORM_FEEDBACK_EXT_TRANSFORM_FEEDBACK_COUNTER_WRITE_EXT|SYNC_TRANSFORM_FEEDBACK_EXT_TRANSFORM_FEEDBACK_WRITE_EXT|SYNC_ACCELERATION_STRUCTURE_BUILD_ACCELERATION_STRUCTURE_READ|SYNC_ACCELERATION_STRUCTURE_BUILD_ACCELERATION_STRUCTURE_WRITE|SYNC_ACCELERATION_STRUCTURE_BUILD_INDIRECT_COMMAND_READ|SYNC_ACCELERATION_STRUCTURE_BUILD_MICROMAP_READ_EXT|SYNC_ACCELERATION_STRUCTURE_BUILD_SHADER_STORAGE_READ|SYNC_ACCELERATION_STRUCTURE_BUILD_TRANSFER_READ|SYNC_ACCELERATION_STRUCTURE_BUILD_TRANSFER_WRITE|SYNC_ACCELERATION_STRUCTURE_COPY_ACCELERATION_STRUCTURE_READ|SYNC_ACCELERATION_STRUCTURE_COPY_ACCELERATION_STRUCTURE_WRITE|SYNC_ACCELERATION_STRUCTURE_COPY_TRANSFER_READ|SYNC_ACCELERATION_STRUCTURE_COPY_TRANSFER_WRITE|SYNC_MICROMAP_BUILD_EXT_MICROMAP_READ_EXT|SYNC_MICROMAP_BUILD_EXT_MICROMAP_WRITE_EXT|SYNC_MICROMAP_BUILD_EXT_SHADER_STORAGE_READ|SYNC_MICROMAP_BUILD_EXT_TRANSFER_READ|SYNC_MICROMAP_BUILD_EXT_TRANSFER_WRITE|SYNC_COPY_TRANSFER_READ|SYNC_COPY_TRANSFER_WRITE|SYNC_RESOLVE_TRANSFER_READ|SYNC_RESOLVE_TRANSFER_WRITE|SYNC_BLIT_TRANSFER_READ|SYNC_BLIT_TRANSFER_WRITE|SYNC_CLEAR_TRANSFER_WRITE|SYNC_INDEX_INPUT_INDEX_READ|SYNC_VERTEX_ATTRIBUTE_INPUT_VERTEX_ATTRIBUTE_READ|SYNC_SUBPASS_SHADER_HUAWEI_ACCELERATION_STRUCTURE_READ|SYNC_SUBPASS_SHADER_HUAWEI_DESCRIPTOR_BUFFER_READ_EXT|SYNC_SUBPASS_SHADER_HUAWEI_INPUT_ATTACHMENT_READ|SYNC_SUBPASS_SHADER_HUAWEI_SHADER_BINDING_TABLE_READ|SYNC_SUBPASS_SHADER_HUAWEI_SHADER_SAMPLED_READ|SYNC_SUBPASS_SHADER_HUAWEI_SHADER_STORAGE_READ|SYNC_SUBPASS_SHADER_HUAWEI_SHADER_STORAGE_WRITE|SYNC_SUBPASS_SHADER_HUAWEI_UNIFORM_READ|SYNC_INVOCATION_MASK_HUAWEI_INVOCATION_MASK_READ_HUAWEI|SYNC_CLUSTER_CULLING_SHADER_HUAWEI_ACCELERATION_STRUCTURE_READ|SYNC_CLUSTER_CULLING_SHADER_HUAWEI_DESCRIPTOR_BUFFER_READ_EXT|SYNC_CLUSTER_CULLING_SHADER_HUAWEI_SHADER_BINDING_TABLE_READ|SYNC_CLUSTER_CULLING_SHADER_HUAWEI_SHADER_SAMPLED_READ|SYNC_CLUSTER_CULLING_SHADER_HUAWEI_SHADER_STORAGE_READ|SYNC_CLUSTER_CULLING_SHADER_HUAWEI_SHADER_STORAGE_WRITE|SYNC_CLUSTER_CULLING_SHADER_HUAWEI_UNIFORM_READ|SYNC_IMAGE_LAYOUT_TRANSITION
```
So we end up with `submitted_usage: SYNC_IMAGE_LAYOUT_TRANSITION`, `prior_usage: SYNC_IMAGE_LAYOUT_TRANSITION, write_barriers: ...|SYNC_IMAGE_LAYOUT_TRANSITION` which seems odd.

Is this just because timeline semaphores aren't supported or maybe something else?

**Comment by artem-lunarg** [comment] 2024-02-19 18:26
@glebov-andrey https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7532 fixes similar issues. If you have opportunity to check it, please let me know if it works for you.

**Comment by artem-lunarg** [comment] 2024-02-20 08:37
I tend to think it's due to timeline semaphores. In another issue (https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7455) similar errors are fixed when binary semaphores are used (code works with both types of semaphores), but one error remains where timeline option is turned on.

**Comment by artem-lunarg** [comment] 2024-02-20 08:49
@glebov-andrey I'm going to close this issue since the original error is fixed and the one that present here seemingly fixed for binary semaphores.

Ideally I'd like to have a self-contained report that describes timeline semaphore issue. So thinking to prepare two tests one with binary semaphore that works and another with timeline that does not. Then hopefully somewhere during spring I can add timelines support. Do you think the original scenario can be relevant to reproduce timeline semaphore issue (swapchain uses binary semaphores, so not sure in which part timelines are used)?

**Comment by glebov-andrey** [comment] 2024-02-20 14:11
> I'm going to close this issue since the original error is fixed and the one that present here seemingly fixed for binary semaphores.

Sounds good.

> Do you think the original scenario can be relevant to reproduce timeline semaphore issue (swapchain uses binary semaphores, so not sure in which part timelines are used)?

Well the `PRESENT_AFTER_WRITE` case specifically can't use timeline semaphores so that's that (... unless we use a `vkQueueSubmit->vkWaitSemaphores->[host]->vkQueuePresentKHR` dependency chain).

But if I understand the error correctly, then the problem was that `ALL_COMMANDS` only included "ordinary" stages, not other "special" types of operations, like in this case - `SYNC_IMAGE_LAYOUT_TRANSITION_BIT` (but also I would assume `SYNC_QUEUE_FAMILY_OWNERSHIP_TRANSFER_BIT` (#7024), and perhaps the `VkEvent` reset operation too (I couldn't find any reference to it in `sync_validation_types.h`))?

So the same problem with `ALL_COMMANDS` not covering certain "special" operations could also affect inter-queue (or queue-host-queue) synchronization using timeline semaphores - but that's basically #7024 already.

The only reason I mentioned the `WRITE-AFTER-WRITE`/`SYNC_IMAGE_LAYOUT_TRANSITION` errors here is because they changed to having the rather odd combination of usage flags in https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7479#issuecomment-1935454512. Other than that, they are already part of #7024.

**Comment by artem-lunarg** [comment] 2024-02-20 14:42
> they changed to having the rather odd combination of usage flags

That's something I'd like to improve. ALL_COMMANDS is not used directly internally but expanded into atomic parts.  We should do the opposite before reporting and detect if a bit pattern includes all supported flags and print something like `SYNC_ALL_COMMANDS_READ_AND_WRITE`/`SYNC_ALL_COMMANDS_READ`/`SYNC_ALL_COMMANDS_WRITE`

**Closed by artem-lunarg** 2024-02-20 14:42 UTC
Labels: Synchronization
