### ISSUE TITLE
vkCmdPushDescriptorSetKHR validation issues?

### ISSUE THREAD

**Issue by fhoenig** [KhronosGroup/Vulkan-ValidationLayers#4775] opened 2022-11-09 17:55 UTC
**Describe the Issue**
I call vkCmdPushDescriptorSetKHR for set 0, then set 2 then do a draw call.
After the draw call, the third call to vkCmdPushDescriptorSetKHR the validation layer crashes on "image_info was nullptr". 
Digging into the callstack I can clearly see that I pass the right arguments. However deeper into the validation layer in the call stack, I see some structs that changed the type to Image. See screenshot.

**Valid Usage ID**
The first draw call spits out this following error. Even though set 0 was bound via a successful `vkCmdPushDescriptorSetKHR` call.
```
"[Validation] Code 0 : Validation Error: [ UNASSIGNED-CoreValidation-DrawState-DescriptorSetNotBound ] Object 0: handle = 0x287dcf800c0, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0xcde11083 | vkCmdDraw(): VkPipeline 0xec25c90000000093[] uses set #0 but that set is not bound."
```

**Environment:**
 - OS: Windows 10
 - GPU: Quadro RTX 6000
 - SDK or header version if building from repo: *VulkanSDK-1.3.231.1*
 - Options enabled (synchronization, best practices, etc.):
```
Vulkan Development Status:
- Layers override: "Validation" configuration
- VULKAN_SDK environment variable: C:\Vulkan
- Vulkan Loader version: 1.3.201
- User-Defined Layers locations:
    - VK_LAYER_PATH variable: None
    - Per-configuration paths: None
    - VK_ADD_LAYER_PATH variable: None
- `vk_layer_settings.txt` uses the default platform path:
    C:\Users\Florian\AppData\Local\LunarG\vkconfig\override
- Available Layers:
    - VK_LAYER_NV_optimus
    - VK_LAYER_RENDERDOC_Capture
    - VK_LAYER_NV_nsight
    - VK_LAYER_VALVE_steam_overlay
    - VK_LAYER_VALVE_steam_fossilize
    - VK_LAYER_EOS_Overlay
    - VK_LAYER_EOS_Overlay
    - VK_LAYER_OBS_HOOK
    - VK_LAYER_OBS_HOOK
    - VK_LAYER_LUNARG_api_dump
    - VK_LAYER_LUNARG_gfxreconstruct
    - VK_LAYER_KHRONOS_synchronization2
    - VK_LAYER_KHRONOS_validation
    - VK_LAYER_LUNARG_monitor
    - VK_LAYER_LUNARG_screenshot
    - VK_LAYER_KHRONOS_profiles (BETA)
- Physical Devices:
    - Quadro RTX 6000 (Discrete GPU) with Vulkan 1.3.205

```

**Additional context**

![2022-11-09 09_40_47-Start](https://user-images.githubusercontent.com/362728/200902993-de1cf920-6dd7-4def-af4a-bc07d8e14eb2.png)
![2022-11-09 09_38_41-Start](https://user-images.githubusercontent.com/362728/200902995-1f7b7b48-22d0-4f61-9f85-81e8910fdb69.png)
![2022-11-09 09_35_59-Start](https://user-images.githubusercontent.com/362728/200902996-0955cafa-0ce7-4b40-9b67-02e5d6c2f60f.png)

**Comment by fhoenig** [comment] 2022-11-09 19:09
API Dump after changing the pipeline to use consecutive set numbering:

**The draw call still says:**

 "[Validation] Code 0 : Validation Error: [ UNASSIGNED-CoreValidation-DrawState-DescriptorSetNotBound ] Object 0: handle = 0x1f90d6ad120, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0xcde11083 | vkCmdDraw(): VkPipeline 0x8168780000000092[] uses set #0 but that set is not bound."


```
Thread 2, Frame 0, Time 684106 us:
vkCmdBindPipeline(commandBuffer, pipelineBindPoint, pipeline) returns void:
    commandBuffer:                  VkCommandBuffer = 000002A4D2A680F0
    pipelineBindPoint:              VkPipelineBindPoint = VK_PIPELINE_BIND_POINT_GRAPHICS (0)
    pipeline:                       VkPipeline = 8168780000000092

Thread 2, Frame 0, Time 684153 us:
vkCmdPushDescriptorSetKHR(commandBuffer, pipelineBindPoint, layout, set, descriptorWriteCount, pDescriptorWrites) returns void:
    commandBuffer:                  VkCommandBuffer = 000002A4D2A680F0
    pipelineBindPoint:              VkPipelineBindPoint = VK_PIPELINE_BIND_POINT_GRAPHICS (0)
    layout:                         VkPipelineLayout = D68CBB0000000091
    set:                            uint32_t = 0
    descriptorWriteCount:           uint32_t = 1
    pDescriptorWrites:              const VkWriteDescriptorSet* = 000002A4D2A15910
        pDescriptorWrites[0]:           const VkWriteDescriptorSet = 000002A4D2A15910:
            sType:                          VkStructureType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET (35)
            pNext:                          const void* = NULL
            dstSet:                         VkDescriptorSet = 0000000000000000
            dstBinding:                     uint32_t = 0
            dstArrayElement:                uint32_t = 0
            descriptorCount:                uint32_t = 1
            descriptorType:                 VkDescriptorType = VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER (6)
            pImageInfo:                     const VkDescriptorImageInfo* = UNUSED
            pBufferInfo:                    const VkDescriptorBufferInfo* = 000002A4D2982720
                pBufferInfo[0]:                 const VkDescriptorBufferInfo = 000002A4D2982720:
                    buffer:                         VkBuffer = 96FBE2000000005E
                    offset:                         VkDeviceSize = 0
                    range:                          VkDeviceSize = 18446744073709551615
            pTexelBufferView:               const VkBufferView* = UNUSED

Thread 2, Frame 0, Time 684242 us:
vkCmdPushDescriptorSetKHR(commandBuffer, pipelineBindPoint, layout, set, descriptorWriteCount, pDescriptorWrites) returns void:
    commandBuffer:                  VkCommandBuffer = 000002A4D2A680F0
    pipelineBindPoint:              VkPipelineBindPoint = VK_PIPELINE_BIND_POINT_GRAPHICS (0)
    layout:                         VkPipelineLayout = D68CBB0000000091
    set:                            uint32_t = 1
    descriptorWriteCount:           uint32_t = 1
    pDescriptorWrites:              const VkWriteDescriptorSet* = 000002A4D2A15910
        pDescriptorWrites[0]:           const VkWriteDescriptorSet = 000002A4D2A15910:
            sType:                          VkStructureType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET (35)
            pNext:                          const void* = NULL
            dstSet:                         VkDescriptorSet = 0000000000000000
            dstBinding:                     uint32_t = 0
            dstArrayElement:                uint32_t = 0
            descriptorCount:                uint32_t = 1
            descriptorType:                 VkDescriptorType = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER (1)
            pImageInfo:                     const VkDescriptorImageInfo* = 000002A4D2982720
                pImageInfo[0]:                  const VkDescriptorImageInfo = 000002A4D2982720:
                    sampler:                        VkSampler = 4B7DF1000000002F
                    imageView:                      VkImageView = 0980B0000000002E
                    imageLayout:                    VkImageLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL (5)
            pBufferInfo:                    const VkDescriptorBufferInfo* = UNUSED
            pTexelBufferView:               const VkBufferView* = UNUSED

Thread 2, Frame 0, Time 684293 us:
vkCmdPushConstants(commandBuffer, layout, stageFlags, offset, size, pValues) returns void:
    commandBuffer:                  VkCommandBuffer = 000002A4D2A680F0
    layout:                         VkPipelineLayout = D68CBB0000000091
    stageFlags:                     VkShaderStageFlags = 16 (VK_SHADER_STAGE_FRAGMENT_BIT)
    offset:                         uint32_t = 0
    size:                           uint32_t = 4
    pValues:                        const void* = 000000D103EFE094

Thread 2, Frame 0, Time 684317 us:
vkCmdBindVertexBuffers(commandBuffer, firstBinding, bindingCount, pBuffers, pOffsets) returns void:
    commandBuffer:                  VkCommandBuffer = 000002A4D2A680F0
    firstBinding:                   uint32_t = 0
    bindingCount:                   uint32_t = 1
    pBuffers:                       const VkBuffer* = 000002A4D1EB60D8
        pBuffers[0]:                    const VkBuffer = EC25C90000000093
    pOffsets:                       const VkDeviceSize* = 000000D103EFDF58
        pOffsets[0]:                    const VkDeviceSize = 0

Thread 2, Frame 0, Time 684346 us:
vkCmdBindVertexBuffers(commandBuffer, firstBinding, bindingCount, pBuffers, pOffsets) returns void:
    commandBuffer:                  VkCommandBuffer = 000002A4D2A680F0
    firstBinding:                   uint32_t = 1
    bindingCount:                   uint32_t = 1
    pBuffers:                       const VkBuffer* = 000002A4D1CCDD38
        pBuffers[0]:                    const VkBuffer = 56C9BD0000000040
    pOffsets:                       const VkDeviceSize* = 000000D103EFDF58
        pOffsets[0]:                    const VkDeviceSize = 0

Thread 2, Frame 0, Time 684367 us:
vkCmdSetScissor(commandBuffer, firstScissor, scissorCount, pScissors) returns void:
    commandBuffer:                  VkCommandBuffer = 000002A4D2A680F0
    firstScissor:                   uint32_t = 0
    scissorCount:                   uint32_t = 1
    pScissors:                      const VkRect2D* = 000000D103EFDF48
        pScissors[0]:                   const VkRect2D = 000000D103EFDF48:
            offset:                         VkOffset2D = 000000D103EFDF48:
                x:                              int32_t = 0
                y:                              int32_t = 0
            extent:                         VkExtent2D = 000000D103EFDF50:
                width:                          uint32_t = 1280
                height:                         uint32_t = 720

Thread 2, Frame 0, Time 684400 us:
vkCmdDraw(commandBuffer, vertexCount, instanceCount, firstVertex, firstInstance) returns void:
    commandBuffer:                  VkCommandBuffer = 000002A4D2A680F0
    vertexCount:                    uint32_t = 4
    instanceCount:                  uint32_t = 1
    firstVertex:                    uint32_t = 0
    firstInstance:                  uint32_t = 0

```

**Comment by spencer-lunarg** [comment] 2022-11-10 04:19
From looking at the API dump (thanks for giving it right away!) I think the problem is 

1. The validation layers don't have ` VUID-VkWriteDescriptorSet-dstSet-00320` covered
2. your `dstSet` is `VK_NULL_HANDLE` from what I see here

**Comment by fhoenig** [comment] 2022-11-10 05:42
From: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdPushDescriptorSetKHR.html

"Each element of pDescriptorWrites is interpreted as in [VkWriteDescriptorSet](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkWriteDescriptorSet.html), except the dstSet member is ignored."

So that's not it.

**Comment by spencer-lunarg** [comment] 2022-11-10 07:29
ok sorry, haven't touched the push descriptors in a while... I haven't had time to look deeper into this, will find time today/tomorrow to dig into this too. Hopefully can use your API dump to create a internal Validation Layer test to reproduce

**Comment by spencer-lunarg** [comment] 2022-11-10 13:23
So looking more into this, what is `VkPipelineLayout = D68CBB0000000091` look like, want to make sure you have a compatible pipeline layout

**Comment by fhoenig** [comment] 2022-11-10 16:21
So I just changed Sascha's pushdescriptors example to use more than one set and I am seeing the same problem.
Maybe I still misunderstand how to use this extensions.

[multiset_diff.txt](https://github.com/KhronosGroup/Vulkan-ValidationLayers/files/9982783/multiset_diff.txt)

**Comment by SaschaWillems** [comment] 2022-11-10 18:17
I just did some experimenting with my sample using @fhoenig code changes, and while the layer message before the crash is a bit misleading, validation layers will output a proper message at pipeline layout creation:

> ERROR: [2143647270][VUID-VkPipelineLayoutCreateInfo-pSetLayouts-00293] : Validation Error: [ VUID-VkPipelineLayoutCreateInfo-pSetLayouts-00293 ] Object 0: handle = 0x2963d650170, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x7fc57626 | vkCreatePipelineLayout() Multiple push descriptor sets found. The Vulkan spec states: pSetLayouts must not contain more than one descriptor set layout that was created with VK_DESCRIPTOR_SET_LAYOUT_CREATE_PUSH_DESCRIPTOR_BIT_KHR set (https://vulkan.lunarg.com/doc/view/1.3.231.1/windows/1.3-extensions/vkspec.html#VUID-VkPipelineLayoutCreateInfo-pSetLayouts-00293)

So you're only allowed to have one set using push descriptors.

But yes, it would be nice if the message at draw time would tell you about that limitation, just as the message at pipeline layout creation.

**Comment by fhoenig** [comment] 2022-11-10 19:02
Interesting. I do not get this validation message. 
Maybe the documentation should be more clear upfront about the fact that you can only use one `set`.

Thank you Sascha!

**Comment by spencer-lunarg** [comment] 2022-11-13 06:01
So trying to reproduce it too, I am always getting the `VkPipelineLayoutCreateInfo-pSetLayouts-00293` error first and after that it is hard to give better error messages as everything assume the stuff before it was valid as well

> it would be nice if the message at draw time would tell you about that limitation

You will hit the 

> VUID-vkCmdPushDescriptorSetKHR-set-00365
>
> set must be the unique set number in the pipeline layout that uses a descriptor set layout that was created with VK_DESCRIPTOR_SET_LAYOUT_CREATE_PUSH_DESCRIPTOR_BIT_KHR

already

----

The clean up in #4781 I think helps enough to close this issue, if there are other suggestion always happy to reopen

**Closed by spencer-lunarg** 2022-11-13 06:01 UTC
Labels: Enhancement
