### ISSUE TITLE
Flags or enum bits are not validated against the instance or device support

### ISSUE THREAD

**Issue by Rua** [KhronosGroup/Vulkan-ValidationLayers#4415] opened 2022-08-13 17:27 UTC
For any flag or enum bit anywhere in the API, if that bit is only available from a certain API version onwards, or only with a particular extension, then there is no validation error for using that bit without the necessary version and/or enabled extension. For example, `VK_IMAGE_LAYOUT_PRESENT_SRC_KHR` is only available in the `VK_KHR_swapchain` extension. If this extension is not enabled, but the layout is used anywhere, for example as the old or new layout of an image layout transition, then there is no message from the validation layer about this.

According to the "Valid Usage for Extensions" and "Valid Usage for Newer Core Versions" sections of the spec, this is invalid usage. It also makes sense that, when a device with no support for `VK_KHR_swapchain` is told to transition an image to `VK_IMAGE_LAYOUT_PRESENT_SRC_KHR`, it has no way of fulfilling that request, as it doesn't know what that layout means.

As far as I can tell from the source code, no check against the instance or device is performed on bits on any flag or enum anywhere in Vulkan, so the problem exists for all of them. There is a check using the `validate_flags` function in stateless_validation.h, but this only checks whether the bits are valid generally, not whether they are supported by the current instance and/or device.

**Comment by sjfricke** [comment] 2022-08-14 04:53
I think this might be a duplicate of https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/2787

**Comment by ncesario-lunarg** [comment] 2022-08-15 15:32
I believe @sjfricke is correct. @paul-lunarg if you'd like to take this, I have a prototype [here](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4228), but haven't had a chance to finish it yet.

**Comment by spencer-lunarg** [comment] 2022-10-14 07:49
closing as a duplication of https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/2787 but still a very known issue

**Closed by spencer-lunarg** 2022-10-14 07:49 UTC
