### ISSUE TITLE
Missing checks "vkAllocateDescriptorSets" when trying to allocate missing descriptor types.

### ISSUE THREAD

**Issue by SergioAlapontARM** [KhronosGroup/Vulkan-ValidationLayers#5311] opened 2023-02-20 11:26 UTC
I ran into an issue when allocating descriptor sets from a pool that didn't define valid entries for such descriptor types in the "pPoolSizes" array.

The descriptor pool was allocated as shown next:
`vkCreateDescriptorPool(device=0x6c414c0020, pCreateInfo={sType=VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO, pNext=NULL, flags=<>, maxSets=128, poolSizeCount=3, pPoolSizes=[
  pPoolSizes={type=VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE, descriptorCount=768},
  pPoolSizes={type=VK_DESCRIPTOR_TYPE_STORAGE_IMAGE, descriptorCount=128},
  pPoolSizes={type=VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC, descriptorCount=256}
]}, pAllocator={pUserData=NULL, pfnAllocation=0x6c70f21040, pfnReallocation=    0x6c70f211ac, pfnFree=0x6c70f21408, pfnInternalAllocation=0x6c70f217f0, pfnInternalFree=0x6c70f21824}, pDescriptorPool=0x7cb34a000000406c)`

Following calls to "vkAllocateDescriptorSets" whose set layout contain "VK_DESCRIPTOR_TYPE_ACCELERATION_STRUCTURE_KHR" will trigger an "VK_ERROR_OUT_OF_POOL_MEMORY" error but no error are shown in the validation layers about what was the source of this error.

**Comment by spencer-lunarg** [comment] 2023-10-24 07:31
This was brought up in https://gitlab.khronos.org/vulkan/vulkan/-/issues/3347 as well

The result was https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5167

The issue is the return value of `VK_ERROR_OUT_OF_POOL_MEMORY` is "defined behavior" 

My goal is to add validation support to help users who by accident still try to use the "allocated" descriptor after... but since it is being tracked in #5167 I am going to close this issue as a duplicate

**Closed by spencer-lunarg** 2023-10-24 07:31 UTC
Labels: Incomplete
