### ISSUE TITLE
Block texture dimension validation error

### ISSUE THREAD

**Issue by frustum** [KhronosGroup/Vulkan-ValidationLayers#3497] opened 2021-11-02 17:03 UTC
There is a wrong vkCmdCopyImage-dstOffset-00150|151 error reporting during last mipmaps copying when the source texture is RGBAu32, and the destination texture is block format texture.

The source extent size is 1x1 with RGBAu32 format that represents the minimal single compressed block. The error is reported when the destination mipmap is lower than 4x4 in size. But this data is valid for 2x2 and 1x1 mipmaps.

buffer_validation.cpp:3092 is not checking formats.
// extent_check = ExceedsBounds(&(region.dstOffset), &dst_copy_extent, &subresource_extent);

**Comment by ziga-lunarg** [comment] 2021-11-02 17:07
I believe this is the same error as with #1908 and #1946.

I am currently waiting for clarification from Vulkan-Docs here: https://github.com/KhronosGroup/Vulkan-Docs/issues/1637

**Comment by frustum** [comment] 2021-11-02 17:12
Yes, it is the same. Both Nvidia and AMD drivers handle such copying well.
Direct3D12/11 and Metal do not report errors.
Thank you.

**Comment by ziga-lunarg** [comment] 2023-10-29 17:16
Closing as a duplicate of #1946

**Closed by ziga-lunarg** 2023-10-29 17:16 UTC
Labels: SpecChange
