### ISSUE TITLE
No warning before a crash if pipeline layout has _no_ descriptor sets, but the shader declares uniform inputs

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-ValidationLayers#83] opened 2018-05-14 01:50 UTC
**Issue by [jherico](https://github.com/jherico) (MIGRATED)**
_Monday Apr 30, 2018 at 19:00 GMT_
_Originally opened as https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/2624_

----

I'm working on a shader where the inputs are declared like so:

```

layout (location = 0) in vec4 inPos;

layout (binding = 0) uniform Camera {
    mat4 projection;
    mat4 view;
} camera;

layout(push_constant) uniform PushConsts {
    mat4 orientation;
    vec4 color;
} pushConsts;
```

currently my pipeline layout creation code looks like this:

```
vk::PushConstantRange pushConstantRange{ vk::ShaderStageFlagBits::eVertex, 0, sizeof(SkyGrids::PushContstants) };
_skyGrids.pipelineLayout = _device.createPipelineLayout({ {}, 0, nullptr, 1, &pushConstantRange });
```

If I comment out the camera uniform block in the inputs of my shader, my pipeline gets created just fine.  However, if I leave it there, when I try to create a pipeline I get an initialization error back, but no validation message beforehand.  

Should not the validation layers be able to detect that you're attempting to create a shader that requires a descriptor set, when you've supplied none in the pipeline layout?

**Comment by karl-lunarg** [comment] 2018-05-14 01:50
<a href="https://github.com/chrisforbes"><img src="https://avatars1.githubusercontent.com/u/128877?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [chrisforbes](https://github.com/chrisforbes) (MIGRATED)**
_Monday Apr 30, 2018 at 19:05 GMT_

----

Yes, we should be detecting this case.

**Comment by chrisforbes** [comment] 2018-08-01 15:34
I think we'd need to see more of the shader.

**Comment by mark-lunarg** [comment] 2018-08-01 16:05
@jherico, can you provide some additional details?  We are unable to reproduce the behavior with the information we have.

**Comment by jherico** [comment] 2018-08-02 03:16
I'll try to see if I can reproduce it.

**Comment by mark-lunarg** [comment] 2018-08-27 19:41
@jherico, have you had a chance to investigate further, or can you share the source for the shaders causing the issue? This has bubbled to the top of my list.  Thanks!

**Comment by mark-lunarg** [comment] 2018-10-29 19:21
@jherico, if you cannot reproduce the issue, are you OK with us closing this report?

**Comment by tobine** [comment] 2018-12-13 19:30
@jherico Closing for now due to can't repoduce. If you're still seeing this issue please re-open with further repro details.

**Closed by tobine** 2018-12-13 19:30 UTC
Labels: Incomplete
