### ISSUE TITLE
The shader_validation.cpp and .h files use spirv.hpp from glslang, not spirv-headers.

### ISSUE THREAD

**Issue by dj2** [KhronosGroup/Vulkan-ValidationLayers#1768] opened 2020-04-27 15:57 UTC
In https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/layers/shader_validation.cpp#L34 we use `<SPIRV/spirv.hpp>`. This will the spirv header from GLSLang and not from SPIRV-Headers. This should probably be changed to `<spirv/unified1/spirv.hpp>` to pull in the SPIRV-Headers file.

The same for the .h file.

**Comment by mark-lunarg** [comment] 2020-04-27 16:13
@dj2, yikes.  In my VVL tree, I have 7 copies of spirv.hpp, in 5 different sizes.  It *looks* like the version we're using (from the glslang install dir) is the same as the one in the unified1 dir, other than whitespace, and I think we're relying on the Glslang install to get the header files into a location where the builds can pick them up.  Do you know what the difference is between these two files, and can you explain why we'd want the other one?

**Comment by dj2** [comment] 2020-04-27 16:51
The glslang file is a copy of the spirv-headers file. We intend to make the glslang install copy go away, the `SPIRV/` folder will move to `glslang/SPIRV` at which point the path will break. The SPIRV-Headers versions are the source of truth so should be used over the glslang copies.

It gets a bit weird in that if you're on a case-insensitive file system you'll need to install spirv-headers before glslang I think on order to get the 'spirv' folder instead of 'SPIRV'

**Comment by mark-lunarg** [comment] 2020-04-27 17:28
Sorry, trying to get some context.  So the upstream glslang repo will change what it currently installs, and we'll need to change our repos that use spirv-tools to work properly with the new structure?  If this is the case, can you point us to a glslang branch that we could start working with?

**Comment by dj2** [comment] 2020-04-27 17:31
You need to switch to spirv-headers install, not spirv-tools. The GLSLang change was originally reverted and we added an entry in the README that the folder is going to go away. As long as you have spirv-headers installed you should just be able to change to use `spirv/unified1/spirv.hpp` and everything should work. That's the SPIRV-Headers path for the same file.

**Comment by mark-lunarg** [comment] 2020-04-27 18:19
Just to be clear, when we install glslang through CMake, the spirv folder will be installed to glslang/spirv, and this is what we should use going forward?  Or are you saying we need to install spirv-headers alongside glslang and spirv-tools?

**Comment by dj2** [comment] 2020-04-27 18:28
I'm saying you should install spirv-headers and use the header from there _not_ the one from glslang.

**Comment by mark-lunarg** [comment] 2020-04-27 18:36
What if it doesn't match the one used by glslang -- then we're linking to one version to get the tools, and we are compiling with headers that may not match?  This is why we used the one specified by spirv-tools, so we always knew we had a 'good' version.

**Comment by dj2** [comment] 2020-04-27 18:39
spirv-tools should not be pointing at `SPIRV/spirv.hpp` anywhere? If it is, that's a bug, heh.

**Comment by mark-lunarg** [comment] 2020-04-27 18:51
Dan, thanks for your patience -- as I understand it, glslang clones spirv-tools into `glslang/external`, and then clones spirv-headers into `glslang/external/spirv-tools/external/spirv-headers`, and the version of spirv-headers is controlled by the glslang `known-good.json` file.  Will this also be changing as part of the deprecation?

**Comment by dj2** [comment] 2020-04-27 18:58
No, that should stay the same as far as I understand.

**Comment by mark-lunarg** [comment] 2020-04-27 20:17
OK, thanks for the clarification.

**Comment by jeremy-lunarg** [comment] 2020-04-27 20:17
Why doesn't glslang use the "unified1" header?

**Comment by dj2** [comment] 2020-04-27 20:18
@johnkslang would be the one to answer that.

**Comment by jeremy-lunarg** [comment] 2020-04-27 20:43
Ah, I see. I think it is using the unified1 header. As @mark-lunarg pointed out, the only difference is whitespace.

**Comment by johnkslang** [comment] 2020-04-28 04:40
At this point, glslang is always using a copy of a recent one from unified1, one verified to work. I don't think we can see issues these days with that scheme.

Originally, problems were caused by people editing the glslang copy to do prototype work, rather than first reserving enumerants in the SPIR-V copy.  Later, it was possible for official reservations to contradict the glslang prototyping.  People can still do that offline, but I no longer allow it in the official repos.

Because of that, even though it seems wrong, it's not really a bad thing to pick up glslang's copy instead of SPIR-V repo copy, because it's from the SPIR-V repo anyway.  Fixing it is fine too.

**Comment by jeffbolznv** [comment] 2020-04-28 04:45
I'm in favor of switching the validation layers to use spirv.hpp directly from spirv-headers. It can be a hassle to have to update the known-good glslang just to be able to implement basic validation support for an extension, like updating the OpCapability vs Vulkan feature enable checking. Only the tests rely on glslang, the layers ought not need any of its source files.

**Comment by johnkslang** [comment] 2020-04-28 07:24
Agreed that is better.

**Comment by jeremy-lunarg** [comment] 2020-04-28 14:40
@johnkslang

**Comment by johnkslang** [comment] 2020-04-29 12:59
Yes.

**Closed** 2020-05-04 23:08 UTC
