### ISSUE TITLE
`VkQueryPool` was reset, but validation layers do not recognize this!

### ISSUE THREAD

**Issue by Xeais** [KhronosGroup/Vulkan-ValidationLayers#2822] opened 2021-05-20 11:37 UTC
### Describe the Issue
Without activated validation layers everything runs flawlessly. Activated they insist on the messages given below. The query pool is definitely reset at the beginning of the concerning command buffer.

### Valid Usage ID
> Validation[0]: Validation Error: [ UNASSIGNED-CoreValidation-DrawState-QueryNotReset ] Object 0: handle = 0x29026b99958, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x9cacd67a | vkCmdWriteTimestamp(): VkQueryPool 0xf2d4f10000000034[] and query 0: query not reset. After query pool creation, each query must be reset before it is used. Queries must also be reset between uses.

... continues for more queries.

### Environment
 - OS: Windows 10
 - GPU: GTX 980M
 - SDK or header version if building from repo: **1.2.176.1**
 - Options enabled (synchronization, best practices, etc.): Nothing that should matter for this case.

**Comment by sfricke-samsung** [comment] 2021-05-20 13:58
> Without activated validation layers everything runs flawlessly

So the worst thing about undefined behavior is it sometimes works on some implementations but might not on others

... but not dismissing it might not be a validation layer bug

before calling the first `vkCmdWriteTimestamp()` are you calling `vkCmdResetQueryPool` or `vkResetQueryPool`?

**Comment by ncesario-lunarg** [comment] 2021-05-20 14:36
@Xeais could you please provide a code sample reproducing the issue?

**Comment by Xeais** [comment] 2021-05-25 11:57
> > Without activated validation layers everything runs flawlessly
> 
> So the worst thing about undefined behavior is it sometimes works on some implementations but might not on others
> 
> ... but not dismissing it might not be a validation layer bug
> 
> before calling the first `vkCmdWriteTimestamp()` are you calling `vkCmdResetQueryPool` or `vkResetQueryPool`?
> 
> Edit: Also I a long time ago looked into `vkCmdWriteTimestamp` stuff as the spec had some strange wordings for time stamps because it doesn't have the `vkCmdBeginQuery`/`vkCmdEndQuery` wrappings around it

Thank you for the fast answer, unfortunately, I couldn't be equally fast.

So, over some period of time I tried many ways to reset that query pool - before, after and in between, 😉, `vkCmdWriteTimestamp()`: no success.

@ncesario-lunarg A high-level overview: `vkCmdWriteTimestamp()` is used for timing (functions: BeginGPUTimer/EndGPUTimer ) in a class called 'FrameProfiler'. The actual timing then occurs in the renderer-class; the query pool is reset at the beginning of every rendering-cycle via `vkCmdResetQueryPool`. Actually, that's it. The simplicity makes it even more frustrating that the Validation Layers still insist on more resets with regard to `vkCmdWriteTimestamp()`.

**Comment by ncesario-lunarg** [comment] 2021-05-27 15:47
Thanks for the additional info @Xeais.

> vkCmdResetQueryPool() right before every call to vkCmdWriteTimestamp()

From the [spec](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/chap18.html#queries-operation):
> After query pool creation, each query must be reset before it is used. Queries must also be reset between uses.

As far as I know, `vkCmdWriteTimestamp` is a query, so I think this sounds correct.

> One BeginGPUTimer() had to be moved outside of a render pass.

If your `FrameProfiler` class is calling `vkCmdResetQueryPool` and/or `vkCmdCopyQueryPoolResults`, you might be running into one of the following which would require these calls to be used _outside_ of a render pass:
- [VUID-vkCmdResetQueryPool-renderpass](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/chap18.html#VUID-vkCmdResetQueryPool-renderpass)
- [VUID-vkCmdCopyQueryPoolResults-renderpass](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/chap18.html#VUID-vkCmdCopyQueryPoolResults-renderpass)

I'm going to close this as it looks like it is resolved, but please re-open if there is still an issue here.

**Closed by ncesario-lunarg** 2021-05-27 15:47 UTC
