### ISSUE TITLE
Nvidia Reflex + Synchronization Validation Bug

### ISSUE THREAD

**Issue by timeester3648** [KhronosGroup/Vulkan-ValidationLayers#6701] opened 2023-10-15 18:53 UTC
**Environment:**
 - OS: Windows 11
 - GPU and driver version: RTX 3080 (Game Ready Driver 537.58)
 - SDK or header version if building from repo: SDK 1.3.261.1 (header version 261)
 - Options enabled (synchronization, best practices, etc.): synchronization only (since GPU assisted crashes when using descriptor buffer)

**Describe the Issue**
2 main issues. The main bigger one:

The semaphore returned by `NvLL_VK_InitLowLatencyDevice`, because this semaphore is most likely not created through the usual Vulkan API calls, causes a ~20 second long stall, and a validation error. More info under **Additional Context**.

The second issue is with `NvLL_VK_DestroyLowLatencyDevice`:
The semaphore should not be destroyed by yourself, Nvidia does it for you, but if you do not, you get a validation error saying that not all children of the device are destroyed, and if you do the error goes away. Still, it will crash sometimes, since it is not a valid semaphore anymore. You also get a validation error about destroying an invalid semaphore. More info under **Additional Context**.

**Expected behavior**
To have the semaphore act as it would if it was created normally like when you make the semaphore through the Vulkan API.
And to not get the validation errors when Nvidia destroys the semaphore for you.

**Additional context**

<details>
<summary>Code and terminal output</summary>

Validation message (first issue):

```sh
Validation Error: [ UNASSIGNED-VkSemaphore-state-timeout ] Object 0: handle = 0xfab64d0000000002, type = VK_OBJECT_TYPE_SEMAPHORE; | MessageID = 0x57e65a33 | Timeout waiting for timeline semaphore state to update. This is most likely a validation bug. completed_.payload=0 wait_payload=1

```

Caused by the code snippet directly from the official Nvidia Reflex Integration Guide (1.8):

```
// semaphore here is the semaphore returned by NvLL_VK_InitLowLatencyDevice

uint64_t signalVaIue;
// This here also causes ~20 second stalls, but only after the first vkWaitSemaphores call
vkGetSemaphoreCounterValue(vkDevice, semaphore, &signalValue);
signalValue += 1;

VkSemaphoreWaitInfo semaphoreWaitInfo;
semaphoreWaitInfo.pNext = NULL;
semaphoreWaitInfo.flags = 0;
semaphoreWaitInfo.semaphoreCount = 1u;
semaphoreWaitInfo.pSemaphores = &semaphore;
semaphoreWaitInfo.pValues = &signalValue;

status = NvLL_VK_Sleep(vkDevice, signalValue);
// This here causes ~20 second stalls
vkWaitSemaphores(vkDevice, &semaphoreWaitInfo, 1000000000000000000);
```

Validation message (second issue):

```sh
Validation Error: [ VUID-vkDestroySemaphore-semaphore-parameter ] Object 0: handle = 0x1b5ba37f880, type = VK_OBJECT_TYPE_INSTANCE; | MessageID = 0x3f4efd34 | vkDestroySemaphore(): Invalid VkSemaphore Object 0x1b5bd8387c0. The Vulkan spec states: If semaphore is not VK_NULL_HANDLE, semaphore must be a valid VkSemaphore handle (https://vulkan.lunarg.com/doc/view/1.3.261.0/windows/1.3-extensions/vkspec.html#VUID-vkDestroySemaphore-semaphore-parameter)
Validation Error: [ UNASSIGNED-Threading-Info ] Object 0: handle = 0x1b5bd8387c0, type = VK_OBJECT_TYPE_SEMAPHORE; | MessageID = 0x5d6b67e2 | Couldn't find VkSemaphore Object 0x1b5bd8387c0. This should not happen and may indicate a bug in the application.
Validation Error: [ UNASSIGNED-Threading-Info ] Object 0: handle = 0x1b5bd8387c0, type = VK_OBJECT_TYPE_SEMAPHORE; | MessageID = 0x5d6b67e2 | Couldn't find VkSemaphore Object 0x1b5bd8387c0. This should not happen and may indicate a bug in the application.

```

Caused by the code snippet directly from the official Nvidia Reflex Integration Guide (1.8):

```
status = NvLL_VK_DestroyLowLatencyDevice(vkDevice);
```

</details>

**Comment by artem-lunarg** [comment] 2023-10-16 17:48
> semaphore is most likely not created through the usual Vulkan API calls

Actually it's a regular Vulkan API call. I played a  bit with reflex initialization and found it calls `vkCreateSemaphore` (nothing special except it uses `VkQueryLowLatencySupportNV` in the pNext chain to enable reflex specific behavior) and if I put breakpoint in validation layer I can intercept it. It uses `Device` parameter passed to `NvLL_VK_InitLowLatencyDevice` in `vkCreateSemaphore` call.

(FYI, @pdaniell-nv, about the next part)
It looks like there is a bug in the Reflex library in how it works with a semaphore handle in the presence of the *validation layer*. When the validation layer is active, `vkCreateSemaphore` returns a *wrapped* handle. The validation layer always maps this wrapped handle back to the native driver's handle before calling the driver's endpoint. 

The semaphore handle passed to `vkDestroySemaphore` should be the value from corresponding `vkCreateSemaphore` (when validation is enabled it will be a wrapped handle). Debugging session has shown that `NvLL_VK_DestroyLowLatencyDevice` calls `vkDestroySemaphore` and passes to it native driver semaphore handle. Validation layer works with wrapped handles, so it reports that it's unknown handle.

The second problem (UNASSIGNED-Threading-Info, `Couldn't find VkSemaphore Object`) is most likely has the same origin (I did not try to reproduce). `vkGetSemaphoreCounterValue` and `vkWaitSemaphores` in the above example works with a wrapped semaphore handle, but `NvLL_VK_Sleep` might work with native driver handle which is again unknown to validation layer.. 

@timeester3648 as a temporary workaround you can disable Handle Wrapping in Vulkan configurator (it fixes the issue for me with semaphore destruction). Also the recommendation to check nvidia's bugrackers/forums. In case I don't find something that I missed or misunderstood, I'm going to close this ticket soon.

<img src="https://github.com/KhronosGroup/Vulkan-ValidationLayers/assets/121836235/5f53aebd-b62a-4a06-bf41-adcd0a85d435" width=45% height=45%>

**Comment by chansen-nv** [comment] 2023-10-16 18:32
I've identified the bug in the NV code and am working on the fix for this.

**Closed** 2023-10-16 18:36 UTC
Labels: Synchronization
