### ISSUE TITLE
vkQueueSubmit() crash when Queue null

### ISSUE THREAD

**Issue by pc-john** [KhronosGroup/Vulkan-ValidationLayers#5793] opened 2023-05-04 08:37 UTC
**Environment:**
 - OS: Win10
 - GPU: Quadro RTX 3000
 - SDK: 1.3.243
 - Options enabled: most of validation using vkconfig

**Description**

Crash inside validation layers when queue parameter of vkQueueSubmit() is null. Code to reproduce:

<pre>
device.queueSubmit(
	vk::Queue(),
	vk::SubmitInfo(
		0, nullptr, nullptr,  // waitSemaphoreCount, pWaitSemaphores, pWaitDstStageMask
		1, &commandBuffer,    // commandBufferCount+pCommandBuffers
		0, nullptr            // signalSemaphoreCount, pSignalSemaphores
	),
	renderingFinishedFence
);
</pre>

**Expected behavior**

According to VUID-vkQueueSubmit-queue-parameter: "queue must be a valid VkQueue handle". So, validation layers shall not crash on null handle but fire with VUID error.

**Comment by spencer-lunarg** [comment] 2023-05-05 04:18
I wrote a small test

```
TEST_F(VkLayerTest, QueueSubmitNullQueue) {
    ASSERT_NO_FATAL_FAILURE(Init());

    m_commandBuffer->begin();
    m_commandBuffer->end();

    auto submit_info = LvlInitStruct<VkSubmitInfo>();
    submit_info.commandBufferCount = 1;
    submit_info.pCommandBuffers = &m_commandBuffer->handle();
    vk::QueueSubmit(VK_NULL_HANDLE, 1, &submit_info, VK_NULL_HANDLE);
}
```

@charles-lunarg it seems this is aborting in the `vkQueueSubmit` trampoline and never makes it to the Validation Layers

**Comment by charles-lunarg** [comment] 2023-05-05 04:37
The loader code is this:
```
LOADER_EXPORT VKAPI_ATTR VkResult VKAPI_CALL vkQueueSubmit(VkQueue queue, uint32_t submitCount, const VkSubmitInfo *pSubmits,
                                                           VkFence fence) {
    const VkLayerDispatchTable *disp = loader_get_dispatch(queue);
    if (NULL == disp) {
        loader_log(NULL, VULKAN_LOADER_ERROR_BIT | VULKAN_LOADER_VALIDATION_BIT, 0,
                   "vkQueueSubmit: Invalid queue [VUID-vkQueueSubmit-queue-parameter]");
        abort(); /* Intentionally fail so user can correct issue. */
    }

    return disp->QueueSubmit(queue, submitCount, pSubmits, fence);
}
```

This code is only called when an application links to the loader and does not load the `vkQueueSumit` function pointer using `vkGetDeviceProcAddr`. 
`vkQueueSumit` here will check if you gave an invalid handle (NULL), log a message about it, and intentionally abort.

> According to VUID-vkQueueSubmit-queue-parameter: "queue must be a valid VkQueue handle". So, validation layers shall not crash on null handle but fire with VUID error.

No. Valid usage is about what constitutes valid usage of vulkan. If you do not comply with these valid usage statements, *anything* is liable to happen. Crashing? Totally allowed. I don't want things to crash in general, and will try to avoid it where possible, but it in this case I much prefer to crash loudly over silently continuing. Passing NULL is a very bad mistake to make, and thankfully an easy one to fix. It is a bit annoying that the validation layers can't be the one to report the message, but its impossible to do that, as the queue handle is used to get the next function in the chain. No queue handle, no calling down chain, no validation layers.

When you say "inside the validation layers" is that because you have a callstack showing the crash occurs inside the validation layers?

**Comment by spencer-lunarg** [comment] 2023-05-05 04:48
Ok, so to sum this up

- The VVL are not crashing, the loader is
- Without the Dispatch handle (in this case the `queue`), loader can never call down the chain

> When you say "inside the validation layers" is that because you have a callstack showing the crash occurs inside the validation layers?

@pc-john - I guess this is the question we both want for clarification

**Comment by charles-lunarg** [comment] 2023-05-05 05:06
A wrinkle is that the `loader_log()` function will not write to the debug callbacks without a valid instance, and since the vkQueue handle here is NULL, there is no way to get the instance. It will write to stderr if the VK_LOADER_DEBUG env-var is set, which means its not writing to stderr by default. Thus, the abort is extremely surprising since there is no callbacks or stderr messages indicating the reason. 

That brings up the question - should loader_log be able to write to stderr in this case (and similar cases where an abort() would occur anyway)?

**Comment by pc-john** [comment] 2023-05-05 06:45
> > When you say "inside the validation layers" is that because you have a callstack showing the crash occurs inside the validation layers?
> 
> @pc-john - I guess this is the question we both want for clarification

Thanks for looking on the issue and sorry for not providing enough details. If not using call through device function pointer, it really crashes inside vulkan-1.dll . Based on @charles-lunarg comment, it probably crashes on the first line of the loader:

<pre>
    const VkLayerDispatchTable *disp = loader_get_dispatch(queue);
</pre>

However, if device function pointer is used, I see the following on the call stack:

<pre>
VkLayer_khronos_validation.dll!vulkan_layer_chassis::QueueSubmit(VkQueue_T * queue, [...]) Line 1159
[my vkQueueSubmit call through function pointer]
</pre>

Hm, thinking about the way forward...

Crash in the first case (static call) seems to me good solution. Otherwise we would need additional "if", incurring additional overhead. However, the second case (call through the function pointer) already reaches validation layers. This is what I see on my call stack. Could we probably check for queue==nullptr there? @charles-lunarg pointed out that there would be no instance and no debug callbacks. Hacky way would be to use any instance the application created, because null Queue might belong to any of them or to none at the same time while the most applications create only one Instance. But not sure about such solution. For me personally, it is important to see validation error in the console and in Visual Studio output window, and to "break" application execution and to show visual studio debugger if debugger is running.

Thanks for the support!

**Comment by spencer-lunarg** [comment] 2023-05-05 08:53
Ok, so for sake of tracking this, going to close this issue and move over to https://github.com/KhronosGroup/Vulkan-Loader/issues/1190 - I also agree that having the Loader display these errors to normal stderr log is important as if you are hitting this, I doubt anyone would consider it a "spam" message

**Comment by pc-john** [comment] 2023-05-05 09:34
Oh. I am now a little confused. I was expecting that the problem is in validation layer and cannot be helped in the Loader. Validation layer is receiving null Queue when vkQueueSubmit() is called through the function pointer. It is probably easy to test for the null there and raise validation error.

I am not sure if anything can be done for it inside Vulkan Loader as we would explicitly need to test for null and we probably do not want this overhead.

**Comment by spencer-lunarg** [comment] 2023-05-05 09:42
> However, if device function pointer is used, I see the following on the call stack

Ok, sorry I misread this, let me try to reproduce that way and see why it is not throwing the correct error

**Comment by pc-john** [comment] 2023-05-11 08:33
Not sure, but is https://github.com/KhronosGroup/Vulkan-Loader/issues/1190 really related to this issue? Shall we close it? Let's recall that the problem here is related just to null handle that reached into the Validation Layer by dynamically loaded function pointer.

**Comment by juan-lunarg** [comment] 2023-05-18 20:38
If you load `vkQueueSubmit` via `vkGetDeviceProcAddr` you still crash. The validation layers don't properly report the vuid.

Instead it crashes in the validation layers.

```
VKAPI_ATTR VkResult VKAPI_CALL QueueSubmit(
    VkQueue                                     queue,
    uint32_t                                    submitCount,
    const VkSubmitInfo*                         pSubmits,
    VkFence                                     fence) {
    auto layer_data = GetLayerDataPtr(get_dispatch_key(queue), layer_data_map); <- Crahes right here.
```

Despite the fact we have validation layer code written for `VUID-vkQueueSubmit-queue-parameter` it was never going to be hit.

**Comment by mark-lunarg** [comment] 2023-05-18 21:20
Passing a NULL handle for any dispatchable object (instance, physical device, device, command buffer, or queue) will cause huge problems.

**Comment by juan-lunarg** [comment] 2023-05-18 22:12
Agreed see draft PR on a possible way to handle this type of issue

**Comment by pc-john** [comment] 2023-05-19 08:09
Thanks! I guess it will work well on Linux and print message. But it will probably not work on MSVC, particularly when building GUI only application (no console). Not sure, but there is a kind of function to print into Output window in MSVC.

**Comment by juan-lunarg** [comment] 2023-05-19 17:28
> But it will probably not work on MSVC, particularly when building GUI only application (no console). Not sure, but there is a kind of function to print into Output window in MSVC

Hmm. Thoughts @charles-lunarg? We would want to align on a similar solution in the loader and validation.

**Comment by charles-lunarg** [comment] 2023-05-19 17:34
Not much validation layers can do in that case. It might not be a bad idea to also write to the output window as long as that doesn't complicate the build.

Also I created loader issue [#1190](https://github.com/KhronosGroup/Vulkan-Loader/issues/1190) in response to this issue - because the loader could be a bit more helpful in this error case than it currently is. It definitely is good to align on a solution that both validation and the loader can implement, so I was holding off on fixing up the loader until then.

**Comment by spencer-lunarg** [comment] 2024-04-12 01:12
So I re-wrote my small test from https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5793#issuecomment-1535679031

and see the loader is now printing 

```
ERROR:             vkQueueSubmit: Invalid queue [VUID-vkQueueSubmit-queue-parameter]
```

by default, which will warn people

I am unable to reproduce a case where a null queue handle gets to `vulkan_layer_chassis::QueueSubmit` so unless there is another way to test this, I am closing this issue as an developer will now properly be alerted here

**Closed by spencer-lunarg** 2024-04-12 01:12 UTC
Labels: Bug
