### ISSUE TITLE
Potentially wrong READ_AFTER_WRITE synchronization validation error when descriptor indexing is used.

### ISSUE THREAD

**Issue by nikitablack** [KhronosGroup/Vulkan-ValidationLayers#4078] opened 2022-05-04 12:18 UTC
**Describe the Issue**

I'm using descriptor indexing and dynamic rendering and here is what I do:

1. Barrier for transition render target `UNDEFINED` -> `COLOR_ATTACHMENT_OPTIMAL`
2. Draw to the render target
3. Barrier for transition render target `COLOR_ATTACHMENT_OPTIMAL `-> `COLOR_ATTACHMENT_OPTIMAL `
4. Draw to the render target -> **the layers complain here**
5. Barrier for transition render target `COLOR_ATTACHMENT_OPTIMAL` -> `SHADER_READ_ONLY_OPTIMAL`
6. Barrier for transition a swapchain image `UNDEFINED` -> `COLOR_ATTACHMENT_OPTIMAL`
7. Draw the render target via fullscreen triangle to the swapchain image
8. Barrier for transition swapchain image `COLOR_ATTACHMENT_OPTIMAL` -> `PRESENT`
9. Present

I have a single `variable`, `partially bound`, `update after bind` descriptor of type `VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER` where I incrementally write infos for different draw commands. For step 4 it's a font image with index 0, for step 7 it's the render target with index 1.

The layer says:

> SYNC-HAZARD-READ_AFTER_WRITE(ERROR / SPEC): msgNum: 1287084845 - Validation Error: [ SYNC-HAZARD-READ_AFTER_WRITE ] Object 0: handle = 0x55f255e89650, name = render target image view, type = VK_OBJECT_TYPE_IMAGE_VIEW; | MessageID = 0x4cb75b2d | vkCmdDrawIndexed: Hazard READ_AFTER_WRITE for VkImageView 0x55f255e89650[render target image view], in VkCommandBuffer 0x55f257e1ec70[], and VkPipeline 0x55f2552922b0[egui pipeline], VkDescriptorSet 0x55f254df40d0[], type: VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, imageLayout: VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL, binding #0, index 1. Access info (usage: SYNC_FRAGMENT_SHADER_SHADER_STORAGE_READ, prior_usage: SYNC_IMAGE_LAYOUT_TRANSITION, write_barriers: SYNC_COLOR_ATTACHMENT_OUTPUT_COLOR_ATTACHMENT_WRITE, command: vkCmdPipelineBarrier, seq_no: 1, reset_no: 3).

The part binding #0, index 1 confuses me - in step 4, I'm using binding 0 with index 0 to sample a font texture. Binding 0 with index 1 is used in step 7.  In other words, in step 4 I'm drawing to the attachment that is used in step 7 as sampled image. My rendering looks correct and validation layers are silent (except Synchronization, of course).

**Valid Usage ID**
If applicable, please include the validation messages encountered leading up to the issue

**Environment:**
 - OS: Ubuntu 18.04
 - GPU: NVidia Quadro P1000
 - SDK or header version if building from repo: 1.3.211
 - Options enabled (synchronization, best practices, etc.): Synchronization

**Comment by ncesario-lunarg** [comment] 2022-05-25 20:57
My guess is that this is related to https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/3450? i.e., we do not currently have the ability to determine which descriptors are used and which aren't at draw time, and so both 0.0 and 0.1 are assumed to be used. A fix for this is planned for future work, but won't be done in the short term.

FYI @Tony-LunarG @jeremyg-lunarg in case this is not correct.

**Comment by jeremyg-lunarg** [comment] 2022-05-25 21:34
> My guess is that this is related to #3450? i.e., we do not currently have the ability to determine which descriptors are used and which aren't at draw time, and so both 0.0 and 0.1 are assumed to be used. A fix for this is planned for future work, but won't be done in the short term.
> 
> FYI @Tony-LunarG @jeremyg-lunarg in case this is not correct.

I agree.

**Comment by ncesario-lunarg** [comment] 2022-05-25 22:02
Assigning this to @jeremyg-lunarg for now, but that may change later on.

**Comment by jeremyg-lunarg** [comment] 2023-02-01 14:59
This is a duplicate of https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/3450 . Determining which descriptor indices are actually used in a shader requires instrumenting the SPIR-V code to report which indices are used and then feeding that information back into sync validation (core validation too). I'm working on this, but it is a fairly long term project.

**Closed by jeremyg-lunarg** 2023-02-01 14:59 UTC
Labels: DescriptorIndexing
