### ISSUE TITLE
Validation layer doesn't catch missing transition for vkCmdCopyQueryPoolResults

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-ValidationLayers#44] opened 2018-05-14 01:44 UTC
**Issue by [Jasper-Bekkers](https://github.com/Jasper-Bekkers) (MIGRATED)**
_Wednesday Sep 06, 2017 at 17:54 GMT_
_Originally opened as https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/2053_

----

> vkCmdCopyQueryPoolResults is considered to be a transfer operation, and its writes to buffer memory must be synchronized using VK_PIPELINE_STAGE_TRANSFER_BIT and VK_ACCESS_TRANSFER_WRITE_BIT before using the results.

This rule appears to slip through the validation layer causing incorrect timestamp query results on at least AMD hardware.

Could be a duplicate of #2014

**Comment by mark-lunarg** [comment] 2018-05-14 15:28
This is a duplicate of #38, tracking there.

**Closed by mark-lunarg** 2018-05-14 15:28 UTC
Labels: incomplete
