### ISSUE TITLE
vkSetDebugUtilsObjectNameEXT not working with VkMemory

### ISSUE THREAD

**Issue by giordi91** [KhronosGroup/Vulkan-ValidationLayers#1434] opened 2019-12-13 10:46 UTC
I have been using the DebutUtils extensions with great success and is amazing! 
I am facing an issue when setting a debug name to a VkMemory backing up a texture I am rendering into. 
The validation layer triggers properly for other objets like a VkSampler. But for VkMemory I get:

```
ERROR: OBJ ERROR : For VkDevice 0x268a3d8b270[], VkDeviceMemory 0xbbfc8c0000000029[] has not been destroyed. 
```
The debug name is set using the following macro:
```
#define SET_DEBUG_NAME(resource, type, name)                                   \
  {                                                                            \
    VkDebugUtilsObjectNameInfoEXT debugInfo_{};                                \
    debugInfo_.sType = VK_STRUCTURE_TYPE_DEBUG_UTILS_OBJECT_NAME_INFO_EXT;     \
    debugInfo_.objectHandle = (uint64_t)resource;                              \
    debugInfo_.objectType = type;                                              \
    debugInfo_.pObjectName = name;                                             \
    VK_CHECK(vkSetDebugUtilsObjectNameEXT(vk::LOGICAL_DEVICE, &debugInfo_));   \
  }
```

And is used with:
```
 SET_DEBUG_NAME(outTexture.deviceMemory, VK_OBJECT_TYPE_DEVICE_MEMORY,
                 (textureName + "Memory").c_str());
```

My SDK installation is:
```
Vulkan Instance Version: 1.1.126
```
I can provide full Vulkan Info if necessary. I am using VS2019 16.4 on Windows 10 with latest updates. I did compile latest vulkan layers and still having the same issue.Please see below:
![image](https://user-images.githubusercontent.com/2525797/70794526-bc050680-1d95-11ea-8da1-69c733432114.png)

Let me know if any more info are required.

**Comment by mark-lunarg** [comment] 2019-12-17 19:43
@giordi91, from the error message, it looks like this object was not destroyed, and is generating an error reported at DestroyDevice-time or DestroyInstance-time.  The test I am using here seems to output the correct VkDeviceMemory object name regardless of where the error is generated.  Perhaps you can either share a quick repro case, or a more detailed set of pseudo-code (or api dump!) to enable us to find the root cause of your issue.  Thanks!

**Comment by mark-lunarg** [comment] 2019-12-19 17:57
Closing for now as we cannot reproduce.  If more information becomes available, please reopen this issue or comment here, and we'll address it right away, thanks!

**Closed by mark-lunarg** 2019-12-19 17:57 UTC
Labels: question
