### ISSUE TITLE
 Test crashes/failures for Radeon RX 6800 XT (RADV NAVI21) on Ubuntu 22.04 using Mesa 23.2.1 driver

### ISSUE THREAD

**Issue by johnzupin** [KhronosGroup/Vulkan-ValidationLayers#7650] opened 2024-03-06 20:13 UTC
On Ubuntu 22.04 using the Mesa 23.2.1 radv driver, and running on a Radeon RX 6800 XT GPU, the following tests crash/fail. This was seen on VVL version `v1.3.278-89-g7a42a6fb1`.

Crashes:

- `*GpuAVRayQuery*`
- `PositiveGraphicsLibrary.VertexInputIgnoreStages`
- `PositiveGraphicsLibrary.FragmentOutputIgnoreStages`
- `PositiveRayTracing.StridedDeviceAddressRegion`
- `PositiveRayTracing.BasicTraceRays`
- `NegativeWsi.SwapchainPresentModeInfoImplicit`
- `PositiveWsi.CreateSwapchainWithPresentModeInfo`
- `PositiveGpuAVRayTracing.BasicTraceRays`
- `PositiveGpuAVRayTracing.BasicTraceRaysDynamicRayFlags`
- `PositiveGpuAVRayTracing.BasicTraceRaysMultipleStages`
- `PositiveGpuAVRayTracing.DynamicRayFlagsSkipTriangle`
- `PositiveGpuAVRayTracing.DynamicTminTmax`

Failures: 

- `PositiveDescriptors.CopyAccelerationStructureMutableDescriptors`

**Comment by johnzupin** [comment] 2024-03-06 20:15
The previously closed issue was https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7549, I've rerun the tests again since the machines didn't get into CI at that time.

**Comment by spencer-lunarg** [comment] 2024-03-21 07:54
- `PositiveGraphicsLibrary.VertexInputIgnoreStages`/`PositiveGraphicsLibrary.FragmentOutputIgnoreStages` were remove
- `GpuAVRayQuery` is fixed in Mesa 24
- `CopyAccelerationStructureMutableDescriptors` should be fixed (or getting fixed with https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7609)
- Ray Tracing tests are working in Mesa 24
- Can't reproduce the WSI issues, but currently no way to test those remotely anyways

**Closed by spencer-lunarg** 2024-03-21 07:54 UTC
Labels: CI/Tests
