### ISSUE TITLE
Improve message of UNASSIGNED-CoreValidation-DrawState-InvalidImageLayout

### ISSUE THREAD

**Issue by ziga-lunarg** [KhronosGroup/Vulkan-ValidationLayers#8782] opened 2024-10-30 18:08 UTC
The message from `UNASSIGNED-CoreValidation-DrawState-InvalidImageLayout` says something like:

```
UNASSIGNED-CoreValidation-DrawState-InvalidImageLayout(ERROR / SPEC): msgNum: 1303270965 - Validation Error: [ UNASSIGNED-CoreValidation-DrawState-InvalidImageLayout ] Object 0: handle = 0x12c4d7a3ea0, type = VK_OBJECT_TYPE_COMMAND_BUFFER; Object 1: handle = 0x68356000000af83e, type = VK_OBJECT_TYPE_IMAGE; | MessageID = 0x4dae5635 | vkQueueSubmit(): pSubmits[0].pCommandBuffers[0] command buffer VkCommandBuffer 0x12c4d7a3ea0[] expects VkImage 0x68356000000af83e[] (subresource: aspectMask VK_IMAGE_ASPECT_COLOR_BIT array layer 0, mip level 0) to be in layout VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL--instead, current layout is VK_IMAGE_LAYOUT_UNDEFINED.
    Objects: 2
        [0] 0x12c4d7a3ea0, type: 6, name: NULL
        [1] 0x68356000000af83e, type: 10, name: NULL
```

But it would be really helpful if it could tell me which is the actual command inside the command buffer that requires this layout, otherwise it is hard to track down.

**Comment by spencer-lunarg** [comment] 2024-12-09 04:50
currently working on this right now, but for simplicity, closing this as found it is a duplicate of https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5846

**Closed by spencer-lunarg** 2024-12-09 04:50 UTC
Labels: Enhancement
