### ISSUE TITLE
vkCmdSetViewport: in 1.1 viewport height can be negative but layer warns it is not greater than 0.0

### ISSUE THREAD

**Issue by francoisbertelatschrodinger** [KhronosGroup/Vulkan-ValidationLayers#503] opened 2018-12-03 01:54 UTC
I am using SDK 1.1.92.1 (27-Nov-2018) on macOS Mojave 10.14.1 on a mid-2012 MacBook Pro.
I am creating a Vulkan instance by passing VK_API_VERSION_1_1 as value of apiVersion of the vk::ApplicationInfo struct.

With this context, I get this message from the validation layer:

validation layer: vkCmdSetViewport: pViewports[0].height (=-270.000000) is not greater 0.0. The Vulkan spec states: height must be greater than 0.0 (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkViewport-height-01772)

However, the 1.1.94 spec for vkCmdSetViewport says:

https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VkViewport

25.8. Controlling the Viewport

"The application can specify a negative term for height, which has the effect of negating the y coordinate in clip space before performing the transform. When using a negative height, the application should also adjust the y value to point to the lower left corner of the viewport instead of the upper left corner. Using the negative height allows the application to avoid having to negate the y component of the Position output from the last vertex processing stage in shaders that also target other graphics APIs."

and the "Valid Usage" section says:
"The absolute value of height must be less than or equal to VkPhysicalDeviceLimits::maxViewportDimensions[1]"

**Comment by karl-lunarg** [comment] 2018-12-03 03:00
Are you using MoltenVK?  If so, MoltenVK currently implements Vulkan 1.0, not 1.1.  With Vulkan 1.0, you have to enable either the `VK_KHR_maintenance1` or `VK_AMD_negative_viewport_height` extension in order to use negative viewport heights.  Both are supported by MoltenVK.  See the "Obsoletion by VK_KHR_maintenance1 and Vulkan 1.1" note in the description for "VK_AMD_negative_viewport_height" in the Vulkan spec.

The MoltenVK "driver" _should_ return `VK_ERROR_INCOMPATIBLE_DRIVER` when creating an instance if you put anything bigger than 1.0 in the `apiVersion` member.   See the information in the Vulkan spec under the description for `VkApplicationInfo` structure to see how to handle all this.

If MoltenVK is NOT returning `VK_ERROR_INCOMPATIBLE_DRIVER`, then that's probably a problem with MoltenVK and you should report it [there](https://github.com/KhronosGroup/MoltenVK).

**Comment by francoisbertelatschrodinger** [comment] 2018-12-03 16:17
Yes, I am using MoltenVK. Indeed vk::createInstance() is returning vk::Result::eSuccess both when apiVersion = VK_API_VERSION_1_0 and apiVersion = VK_API_VERSION_1_1.
As soon as I enable VK_KHR_maintenance1 or VK_AMD_negative_viewport_height, the validation layer message disappear.

**Comment by karl-lunarg** [comment] 2018-12-03 16:34
Thanks for the reply and for trying the extensions.  Since the layers are working as designed, I'll go ahead and close this issue.  But please comment or reopen if needed.

It would also probably be best if you opened a new issue in the MoltenVK [repo](https://github.com/KhronosGroup/MoltenVK) indicating that it is returning the wrong result status code when asking for 1.1.  That way, you can more easily track the status of the problem and maybe get an indication from the MoltenVK developers on when they plan to support 1.1.

**Comment by francoisbertelatschrodinger** [comment] 2018-12-03 16:35
I just did report the issue to MoltenVK: https://github.com/KhronosGroup/MoltenVK/issues/358

**Closed by karl-lunarg** 2018-12-03 16:34 UTC
