### ISSUE TITLE
PreprocessShaderBinary can hang with incorrect/truncated SPIRV

### ISSUE THREAD

**Issue by simoneves** [KhronosGroup/Vulkan-ValidationLayers#1910] opened 2020-06-06 00:31 UTC
OK, so I made the rookie mistake of setting `VkShaderModuleCreateInfo::codeSize` to the number of words, not the number of bytes, but what happens was that `vkCreateShaderModule` went into an infinite loop.

Three hours later, after installing the latest Vulkan SDK to see if it was a fixed bug (still hung), hacking one of the Vulkan SDK examples to feed it the same SPIRV (didn't hang), then building the Validation Layers in Debug so I could actually see what was going on, stepping through the `spirv_inst_iter` loop in that function and seeing it encounter an `OpUndef` and then hit the `assert` in `spirv_inst_iter::len()`, I realized that it must be hitting garbage, and then realized my mistake.

In a Release build, it doesn't trigger the `assert`, adds the zero to `it`, and gets stuck in an infinite loop.

I would propose that this code be made more robust, please! At the very least, encountering an `OpUndef` should be an error case and kick it out of the loop to report an error.

**Comment by simoneves** [comment] 2020-06-10 23:10
Not that I saw, but I'll try it again.

**Comment by mark-lunarg** [comment] 2020-06-24 14:29
@simoneves, any new information?  We'll need a repro case to proceed further.

**Comment by mark-lunarg** [comment] 2020-07-01 15:28
Closing due to inactivity.  If a repro case is found, please comment here to get the issue reopened, or create a new issue -- Thanks!

**Comment by TestingPlant** [comment] 2021-07-09 04:45
Using this vertex shader:
```glsl
#version 460 core

void main() {}
```
compiled with `glslc`, and code like
```cpp
std::basic_string<std::uint32_t> bytecode = getBytecode(...);

VkShaderModuleCreateInfo createInfo = {};
createInfo.sType = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO;
createInfo.codeSize = bytecode.size(); // Since bytecode is a string of uint32_t's, this will only give 1/4 of the actual number of bytes
createInfo.pCode = bytecode.data();

VkShaderModule shaderModule;
vkCreateShaderModule(device, &createInfo, nullptr, &shaderModule);
```
causes `vkCreateShaderModule` to hang for me too. Interrupting it with gdb shows that it's stuck in `PreprocessShaderBinary` from this validation layer.

If relevant, I'm using Arch Linux's package for this, more specifically `vulkan-validation-layers` on version 1.2.182-1.

**Comment by ncesario-lunarg** [comment] 2021-07-09 18:14
@TestingPlant I tried this out on a small test app, and got the following before the hang:
```
Validation Error: [ UNASSIGNED-CoreValidation-Shader-InconsistentSpirv ] Object 0: handle = 0x55fb162c3610, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x6bbb14 | SPIR-V module not valid: End of input reached while decoding OpName starting at word 135: missing ID operand at word offset 1.
```
Do you see something like this before the hang?

**Comment by TestingPlant** [comment] 2021-07-17 02:45
I found out that I was using both this validator and Renderdoc's validator (`VK_LAYER_RENDERDOC_Capture`), it causes it to hang, but if I only use this layer, this layer works correctly.

I'm thinking it might be a bug in Renderdoc rather than this, but I can no longer reproduce the issue with the same code after finding out only using this layer makes it work correctly.

**Comment by ncesario-lunarg** [comment] 2021-07-19 14:19
👍 thanks @TestingPlant, I'm going to close this for now as it looks like there is no VVL issue, but please re-open if that is not the case.

**Closed by ncesario-lunarg** 2021-07-19 14:19 UTC
